---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-webhook-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: renovate-webhook-token-secret
    template:
      engineVersion: v2
      data:
        token: "{{ .RENOVATE_WEBHOOK_TOKEN }}"
  dataFrom:
    - extract:
        key: renovate
