---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: renovate-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.0
    digest: sha256:74ffa88c7d805ba3b924a1a288c41323cf58e0d48e200de4e23edcf726d72734
  url: oci://ghcr.io/mogenius/helm-charts/renovate-operator
