---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: renovate-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.7.0
    digest: sha256:502ba722d5eb392860441bee595b949efbc3b8d4fdc7dbed83c12084d15d1a12
  url: oci://ghcr.io/mogenius/helm-charts/renovate-operator
