---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: imagemaid
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: imagemaid-secret
    template:
      data:
        PLEX_TOKEN: "{{ .PLEX_API_KEY }}"
        DISCORD: "{{ .KOMETA_DISCORD_WEBHOOK }}"
  dataFrom:
    - extract:
        key: plex
    - extract:
        key: kometa
