---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name postgres
  annotations:
    # required for seamless bootstrap: https://github.com/cloudnative-pg/cloudnative-pg/issues/5778#issuecomment-2783417464
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-standard-trixie@sha256:81bad466fe006454482678c6c67a24c1e30454b519011e0196cba2e4c83e1e1a

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - k8s-04

  certificates:
    serverCASecret: postgres-server-cert
    serverTLSSecret: postgres-server-cert
    clientCASecret: postgres-client-ca
    replicationTLSSecret: postgres-client-cert

  storage:
    size: 8Gi
    storageClass: longhorn-fast

  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised

  plugins:
    - name: &plugin barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: &store cloudflare-r2-store

  externalClusters:
    - name: &src source
      plugin:
        name: *plugin
        parameters:
          barmanObjectName: *store
          serverName: *name

  ##### RECOVERY #####

  ## Uncomment the below section to enable recovery from r2.
  ## Complete this prior to bootstrapping the cluster.

  bootstrap:
    recovery:
      source: *src

  monitoring:
    enablePodMonitor: true

  postgresql:
    pg_hba:
      - hostssl   all all all cert clientcert=verify-full map=pooler-map
    pg_ident:
      - pooler-map pooler-rw all

    shared_preload_libraries:
      - "timescaledb"

    parameters:
      timescaledb.telemetry_level: "off" # For TimescaleDB (Tracearr)
      timescaledb.max_tuples_decompressed_per_dml_transaction: "0" # For TimescaleDB (Tracearr)
      max_locks_per_transaction: "4096" # For TimescaleDB (Tracearr) DEFAULT: 128

    extensions:

      - name: timescaledb
        image:
          # renovate: datasource=docker depName=ghcr.io/mrdynamo/timescaledb-bridge
          reference: ghcr.io/mrdynamo/timescaledb-bridge:2.27.0@sha256:c71e61dbfe78454c764bc2fa735d8e9459ec1dd6a92b7363c05b4083395e921f

      - name: timescaledb_toolkit
        image:
          # renovate: datasource=docker depName=ghcr.io/mrdynamo/timescaledb-toolkit
          reference: ghcr.io/mrdynamo/timescaledb-toolkit:1.22.0@sha256:a31d737187415c8ce52229ab6f96aeebf4c4bd690cbc86400b93a201488a274d

  managed:
    roles:

      - name: pooler-rw
        ensure: present
        login: true
        superuser: false
        disablePassword: true

      - name: authentik
        ensure: present
        login: true
        superuser: false
        disablePassword: true

      - name: dispatcharr
        ensure: present
        login: true
        superuser: false
        disablePassword: true

      - name: gatus
        ensure: present
        login: true
        superuser: false
        disablePassword: true

      - name: litellm
        ensure: present
        login: true
        superuser: false
        disablePassword: true

      - name: paperless
        ensure: present
        login: true
        superuser: false
        disablePassword: true

      - name: pgadmin
        ensure: present
        login: true
        superuser: true
        disablePassword: true

      - name: tracearr
        ensure: present
        login: true
        superuser: false
        disablePassword: true
