---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-postgres-s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudnative-pg-postgres-s3-secret
    template:
      data:
        ACCESS_KEY_ID: "{{ .CLOUDFLARE_R2_ACCESS_KEY_ID }}"
        ACCESS_SECRET_KEY: "{{ .CLOUDFLARE_R2_ACCESS_SECRET_KEY }}"
        REGION: "{{ .CLOUDFLARE_R2_REGION }}"
  dataFrom:
    - extract:
        key: cloudflare
