---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-secret
    template:
      data:
        ALERTMANAGER_DISCORD_WEBHOOK: "{{ .ALERTMANAGER_DISCORD_WEBHOOK }}"
        ALERTMANAGER_PUSHOVER_TOKEN: "{{ .ALERTMANAGER_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        HOMEASSISTANT_WEBHOOK_POWERCYCLE_K8S_04: "{{ .HOMEASSISTANT_WEBHOOK_ENDPOINT }}{{ .HOMEASSISTANT_WEBHOOK_ID_POWERCYCLE_K8S_04 }}"
  dataFrom:
    - extract:
        key: alertmanager
    - extract:
        key: pushover
    - extract:
        key: homeassistant