# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:nRUTLkiLuD9KZXsIgG4nhCfnJWvQJHnXQeTE8W0G0uA//bFmfMrCTA==,iv:PK26m+MLZbxtfJZZXhgI31/jG+fk3+q7zHO5jTnOUdQ=,tag:g2dSURx/yK5k9UMoQccq+g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5ICtsOTFzcmV5
        N0lHQXZVdEFERjRZc1B3c09UZWErNGRvaXFsalhWcEVPUFpCQ3BwRjFva3hHdlc5
        b2ErdkVBU3I2TDNtRlpKVlJlSVlYK25qajRvempmc3pQc0hQWHUwTUVtNDhNNUI0
        dHlRcVpMdXZxZ0Z2bVV4WklLNjhmVk1wWDBZeFpnN0FxL0svTkxrK3BvTlU3bzBj
        L3lRVll6MG1hWDdOY1Q3Tm9MQlp5UWJYd0ZBZzFhR0NiUldkL1hDNnRpZ2FPYzh4
        cHN3K1dUQ2Z0dTNtYUNESExIa3dRU2RlSHdYMzhWbmduS2h1enJKSENoSGV5OGpF
        RmNWUFhXRk9ROGZJUkZNcXJQdHpUTmZpTVVZcFkyQlBITUNJbE9IeVFzVTNDRStl
        S0tvaGxyRmFhMUR5WEFpbi9WcFdjWXIrb0t2bU5VZ29kMTh6RDZZTVFnQTFsbm10
        WHJ4cXR2a205eE42azZsbFpnc0RyemdPVDFNajYxREFUWlR3dmhmMDVLNEhHbi9x
        M3hzN2ViTFQ0anUyaDNyVnJUd1UvWGNTMVo4TEJCYWFaelUwR1hnUXJ3VC82N20z
        Z0lYbEFjcmVCMkpHUkFlWFF2R3dlb0tvLzVia2p4aXhQUS9kN0g0WkRONEl0STA2
        RE1ySWlDcjloQ3l4OUk2bXNRUG1kcm90b08yZ3RQYW5jMmtWYVZqYlVIMnkxVDZt
        MHdmTStGeG1lUUtqL3JXajFZekZYOHc1UU12WXV4ckIrUHBrWmN0ZVRVdHVlRkpQ
        WTRZTktXY2g3R201SUZVSDIrN1gzNVAzTHpTSE9YbHJGLzRhbEpJcHZla1cwSTlZ
        OFh2Mmc3ckJ1cGFXSTJ1cnVDOWltWlJyazlUTW1yK1lQMENMRXloaHRjeEV0Y25n
        UkF0T3BoWUJVdTRTOG1QZ0ZpQi9BTWxlNGRSR252OGZFWGRQRDhaaG5mQXZTa2My
        OHhMbDVBZWlteFdWRmN5OTFHblFyOUVOTlRBQjBHd2RDdzNEMzhYK1B3ZlN0dGdU
        Y0xpTUNCYlZ2YXVFMnZrdmdMd2Y0UDJuNHovLzFKQ1M1UmdjTmY4TUdsQXNQNlRt
        MTVFOVUrNTZ2Q0VieGpGOWUxSnRBdGFjcnBjd3hUSlFuWEZNZWJNK3FvRTFFTUdl
        dENXSFFjMHg3c01Vam1XdzNvamRic0srUjZKRlhIaVAydkRLbGZSU3ZVRVVUS04z
        YWFmR1NFRkdTbm9zNG5JS3hlclNlbmo4SDdXWTV0Wjc3QnFKcXE1K0pLVG0rR3JL
        NkNEOG5UMmhucGYzRFZETVVoQUxHbVlUdUR4L0dRaVMrK0pIQXVXYzgzcFQrNEJt
        K2VsSTZzN3V4YVJDNWc5aHZES0QrYjl3MDBsbWYzVFdKN3pJOWp3T1Judk5mRktG
        V1ROZVhGRk5UQzN0OG0zSWRCWUhhWDRtQ1c5VW9ObGNMTC9RalR2UURmYnZxcFRt
        cEVvQ09CN2ZrZ0R1ajljV0UzS3FJN2NIRHM1YmFVd2pTMUUwQnByVjExWjRFcm1h
        elpISVlLYzY4cDQ0L29RSmJXb3E3cHhVbHdsSWxnRmJzNTA1RHcvMlMzM1dvcHJ2
        SjRTSmRpaHJXSlNTVFRNdUpMTXFZU0ZnNVh3UnJPZjJLWXR5YW03T0l6REREZFFm
        RnltTFNNK2xvejhXQ2cvU0tIaUR2ajBzTkQ2YnhBMG1ZckVTVjhjd0Q0NCtiZXFz
        YXFXZVdIbXBxZEcwdzBoODlIajN6NnVEZDRROXFaaXNpSjRRY2dyZGhySnAybzk0
        S2Z2cWNtMStBSHV2dW5wTnFkTE5FSzdRaEliQi9RRVZFK0VvR3pobUZMejVjUm1W
        am1MUDJZbDZQL1hxQ3JWdzlHVmVlNWdMRXF3TC9OcXRvV0xiNzc1dzZzM2NsRXJi
        RTJPZE1INXVXRm1sVFdwZHNMeHh6R0ZkdDJQMlBKZEZmdXpsd2N2a1BzOFhLdwpJ
        cUF3czdBV3RQQ1VLZStXQXJZMXEzQVNZNmwrOGlkZnNnMUlIdTNHbzM0Ci0tLSBN
        M3hCZ0ZXUXFWVVowTk1Lbng5M3N0L3hWSFEwaWRjeDNxWm1yMUlkVzVVCoOpx92Y
        srh0J+wn1o0427TUmwF3GsXrnzxLnphsXP6V61xy2xpBCpgH5GmH0bqWP3ceSJdE
        86nkMjMonvQsHMk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq17jrq9vucnth9v4e4gx5zvpsr6szqlcnp9mwt0rmyfyzeww97dyejlxsuvgnu4spgqgzwp9ms0dvrz4gtvc9lw6sxnjywpkq773nptcfqgvccxf6tnfq24eq4prfez8azp7k739mdcdmfx3plew9nl58e8vzwppgegzsmm4y477ycgnqcn2vpknyr3x7zm3eqd6yjrfeygt6582fp4fxpzjp5qdm3g6ncydqpq9g47p77p7cervten3snr0tr2zcptxurpfjgx6p2ux0up8a88qx8m0q6q2yreusmwe862h7rjshm8yyzmse5xsc9ydnkdjt3kz2au3lwqujsz0wy44yvvae99xxtcxejh96vjj5gcej9vwkkzq6k329lexv4qqv9rrz89r5v4qn3vd0sq3c8n8ve84gfdx75rse0xdthm9eafen5wfmc2v8ektj4yz6qlk9dm89q5xzy9vvyscc3vlrmwzfkt09eq9h3npzxr92ths4fn3zct5x9yrv5k87st3s3pqft52qplqtjlzgkpq4pp967mvtxejnnjnsf6y9yqfavh9xqgjehk0pl8sxf8z3pr3kf90esvw6fc9y8j52qnxyrrtfwk8rjj686nfp7matvx7w8cyewnz466wdl2k6l97zpe43s8t0rf32qufadeh96jz427ajnx02xzwaamvsqy65ppwpc639j244kxcpqqej9scfz5k3znxmeprr4rpdnevl6sktult2geu7psahqtpyau0pztpjlvap4zvpxdj0tqa9763pq7c626qcrs69yjyzd48pw670m7fmzh2a3kjger7xuhz6l8se2zqtsxz2e9vlshjjh3n6fz4xzpwqtcrt8f5jnnt8nqk7hj236d7rt5dzxt8sujy025uexsuqtdgfwm8v2j8fh90whg9kxhpswctytua5kete82c90jevuqytaxlqtped4kuu4wzsawnkhw3000xzp9uvtrxwerddlvzknzz3lueydzkzfg8qswae65e8lefj8feywjp9el06r3murqlzd27lm70z289re5zp3ftxsy2fmp0rnvuu2h04qywtgwp0s9w0tqzy8l7jz88mn34qgjglhrpj6tp2l02467twzx3jnt9204pvfwy7rxyucqvajxe5hddf8vlxlfza262fux4ggpfqh59zyjl8jm9vx064nhhcv52d39gtyntg9vsxx0gzamzzruyqf8mhed9l2hgzvgvnmzrjt856phzmuymy9edafdxx27st3ehjncz2u39h3jgars8y98p9pmqjpcajuryc6pgul2qznyxdp79jcnt4cwfzxkuyphc2n5krhd0628lzhs8d2y4et3579sfc65y0kf6u7rve8wf4yswuh74jqrhfue0rgg2qhcpxvt9mexnac0fm8f5w5g4fy92hheyqvens9xpc9t0vz3sqcjamkp2ewtvqg4dhnwxapzv2zvervr8rfzmvzau6r27q8dg6rj74az6grle535tlq0s7xyylxud3xn5znfdxf0ju3jhyxxe7zy9yxdp9zp6v2e26zydsdymk5cgppt0qegkk995l6vjxt9f7t4wrch7vd3ljxu3wkyvppg29zw4ee29fqqwm84p5edjpn4fnqm3fsr5nhnnz6ft29e020chr0v7s64ppeyl36nu63zq8lc0f7ly0jx4495vv49ayqxypmzxadnd66xmxwxs7vwlczdkmtetymgkws09rtzkg903g4qpyn3nr6uk8ch69ksr5kc268e5r3dwnnw9uupgch34n2sn85hc3xt3ggys5x8sqmr3u3gllg0y3yq5fg0pmkrvafr8qfwtdve55gdlaavdqeqq2fq04sznlnpa3xctc7rtj5gc54sugwjn5gzr6jcczu95ynpeefsd0r7ngkq3r7vhupsk7uu57dqv4x2fme
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-09-22T18:18:37Z"
  mac: ENC[AES256_GCM,data:kPmKXbZsH0M8p72ChlPtVikJmWt4TsJIl+BTodTYBG5bw+jozBj5AwTUx7v6NJiTBKCQt99ZKV8QntZh8k4g4JevCjIupuxJTmFuDFaDZu3Fm5qyzLUFxypgQ8yoOr+xuVGt6yL3o7GIeta9U9pzXG4951qJzw8Q+xf8Iz2oW68=,iv:/7VSOmDWsSnKO/VQdSN4R7XAM/5UYIOMd9zButt35iU=,tag:vwKFeWW4JJsLRiXZ8PCuxQ==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
