# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:nRUTLkiLuD9KZXsIgG4nhCfnJWvQJHnXQeTE8W0G0uA//bFmfMrCTA==,iv:PK26m+MLZbxtfJZZXhgI31/jG+fk3+q7zHO5jTnOUdQ=,tag:g2dSURx/yK5k9UMoQccq+g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SVFxdVp6SDMycE4wZGs5
        VWY2cUJYYXNDclk1VjdYUDZ0cE56Wlc5TjBnCk12Ri9mK1pUMjRGZHkzSW1GdG95
        QWFHQmtDY2d3aWtaWWxmL0NhQythbU0KLS0tIDVzWVNNNDRielI1SjVFN0VFQ2Ju
        RlY5UGdXQk5BbEozYXE2MThydzJsS1EKc6JFVSHb9AakeQUTTWXm1GYTfYianCFa
        cDiN774oIyHKv8bE1BbMjeqfvLZeon1kWbaGJ4Vc6K99mhK2bhi8kw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yum2rd54mjqlzzpklr209h8qukjngtj5pnn74ugwntzkl6d9fvfqrrzmns
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE5Oc0llS0Ex
        T2ZRQkRPbDljRFBtSWt4Z2lvODdGWnVNUDJFdElWQTVQbHhsRkdTVzZhRDVvNVhL
        NHBLVExRTHVDMFRzQkdLNWIvajlTTGxRQnh6ODh1a1I5Q3I4MnFaeW9YdG5xTmRW
        dFpwMTFmbi9va0NleW9iL0hyMk80dFFHUXltTis0NGdITFM4NysyVlgxeGY2QXBh
        UmcvQ29zeXBLd2cvTG5wbktlM0Y1NGxlL0pKVld6OGVXQ2pKcGhiY3puaWVDUlEr
        eG9ObWkvdUw5Q1JHV1h3WUdhRHJhWkNNNVdES25ETlFIT3JaV2dSSU5RNXNwVm43
        Rml2djFTQU5OSGNSN0ZOM1hRdmxmK3krS1VFNElkM0RJQ3I0ZGd4R0gwZnNSMkNa
        ZHAxRWZRWlR0eDNkcFRhSyswcGhEeHBDTjRkem5wcDA1WUpXOTRsMU1hdHZiNS9Y
        UGtaYnVGRHpOekhGSVdNN3Q0Y0RVMkZZdkkrdTFGZkV3d0NGOWpldVE4M1R1UkRw
        UzVwWVo5MytLeW9RdlBDWDR5Q1RUV1RYenFhSFdYNmFaQmpuODNFeXNsR2Z1elNh
        WGorWXZORnF4Ris1MmlYNGVKeS94VzIwNEVDWmJpdm1lSmhKaTJUaG03T0dHV0x0
        bEVIZGpkVTRybWdTUW96T1BDUDhTazEyb0Y0NEN1cTVZOHFCOU10UjRYelRvSjMr
        QjRzWHEzOUYvTGZlMStuN21iVHF6MlhHNWpKVHZrWmF2VlhURWlWdnhZcmk0Q2pl
        UlhwVytPUmNNRTdKZERqczJIR1N4c1R4UkpMWXlDaFVRS09mWUJPMVRPOTJaQWZp
        bHVRT3VoOW1IQlVKemxCdm5qbmh0ZzdKZENmK2JteXA3dnRHMHEzOVAxbTRsRXZD
        YzgrTkh2TmZZQk9UK3N2QWlKWjdwMzU5c21CU21ROGszVGZxZTJ3OW1Dc29waFpr
        TXliY3c3V3VmakRTTFZSR05PRmpDMHFjQWcvbnRTcU1ydU5SWHliVW5XU20rUDRZ
        elhGS1pBeWNNT0ZpNzZ4dm16NWJiUk9YQ2VqaHV3WVFHRGErQ1JyK1VDM25uK1BM
        MFI1b2Fzc2JnL21wNG9tOGwwaHhpZDU2TjBsYzJTUjFsbUNZSElFbWRFdU5iWUk1
        TzduVGRuRk9VNUxGSXRsV1hiYlQ2VEkzeUNXdzFwVFdGTGFNdVpKZElSRzZDZG8w
        eW5BcHVneWJUODIrQlpJMWsxenlzd3N4QXg5V0dvUTMrczJjNkhVckg4QVFXZzZO
        eldBR0hCeHFJdHZnejdOdGgraEo3YjlPVjBTbWhVQUdhT241Zk5IdDE4R2lGM1kx
        MTJYNVFEdGF6RU5ZR1J0VkVyZnRRZlNVVEw3TlkyM3Z1L1FPS1VJOWl0OVNpeTNU
        K0t0dVRtOFJwYUJ4S293Zk9WTUhRZ3JFSkwvaTdLRkFnb1JaQ2FITjZ1TUdDNnVs
        ZjVlYTI3QU9FL1pnVUNzN042RlVrVE1iRXNyYkxGUVRNMW1VVU00Y0hJakVqUVNM
        OVpFZlh0OEhISWh5c0JQOHNET1g1eVZucEFOcTg3WThibWRoeUVheVF1eExweHlG
        ckZvMG9samlaN20vRE9Va2p4RHFBZmZKYXFVQXlJNmxrRHJuaWVZWS9lcXo5Wlpt
        dnRXWmlPVDNoUkk3c0xTNzM2Qzgzb3l6UE1FUEdrZk52amIwY3BVcGUvRTRhaWtP
        QnFZcENkYlpSTVVZSTNTOXN0NzNQQ2RFUHUzRVIvRWVRc25FSkprNUI5M3dqRHdu
        S0hKamloL2E0N3k2RVhxSVVvUTJmSk1WTUdVd2crTm1iMWl3WGdEY29Bd1htT2Jl
        eWp0K0F1VXhtSTVVWC9kTXFoMXdZWG95ayswRktWRDNHbU5LcjhDdkJNVHdVQW16
        bzNweFUzTGF3Q0R3OGRid2lGNHBRUXB2Wkx3azF4SDRoRmthQlBMRVRHOHZTQQps
        eHJ6WVlHenpaeFExeVBMcW9xTUd5TVllM0dhd0F5di9NSllrR1h5RHMwCi0tLSA4
        L1IxcVhIcmNvM3YvSVN5K1ZGaEpBTGFnRFVLWEozK1JlTXQvM1k3SzZzCtmq0lYF
        O+dv9Wut7Dr0xWwiYHMsl5KyuArXznkwYPOSyEDHIPaiqWCVM6b/se8fgIvXBM7p
        VIWeJaVC+uD7bNo=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq17jrq9vucnth9v4e4gx5zvpsr6szqlcnp9mwt0rmyfyzeww97dyejlxsuvgnu4spgqgzwp9ms0dvrz4gtvc9lw6sxnjywpkq773nptcfqgvccxf6tnfq24eq4prfez8azp7k739mdcdmfx3plew9nl58e8vzwppgegzsmm4y477ycgnqcn2vpknyr3x7zm3eqd6yjrfeygt6582fp4fxpzjp5qdm3g6ncydqpq9g47p77p7cervten3snr0tr2zcptxurpfjgx6p2ux0up8a88qx8m0q6q2yreusmwe862h7rjshm8yyzmse5xsc9ydnkdjt3kz2au3lwqujsz0wy44yvvae99xxtcxejh96vjj5gcej9vwkkzq6k329lexv4qqv9rrz89r5v4qn3vd0sq3c8n8ve84gfdx75rse0xdthm9eafen5wfmc2v8ektj4yz6qlk9dm89q5xzy9vvyscc3vlrmwzfkt09eq9h3npzxr92ths4fn3zct5x9yrv5k87st3s3pqft52qplqtjlzgkpq4pp967mvtxejnnjnsf6y9yqfavh9xqgjehk0pl8sxf8z3pr3kf90esvw6fc9y8j52qnxyrrtfwk8rjj686nfp7matvx7w8cyewnz466wdl2k6l97zpe43s8t0rf32qufadeh96jz427ajnx02xzwaamvsqy65ppwpc639j244kxcpqqej9scfz5k3znxmeprr4rpdnevl6sktult2geu7psahqtpyau0pztpjlvap4zvpxdj0tqa9763pq7c626qcrs69yjyzd48pw670m7fmzh2a3kjger7xuhz6l8se2zqtsxz2e9vlshjjh3n6fz4xzpwqtcrt8f5jnnt8nqk7hj236d7rt5dzxt8sujy025uexsuqtdgfwm8v2j8fh90whg9kxhpswctytua5kete82c90jevuqytaxlqtped4kuu4wzsawnkhw3000xzp9uvtrxwerddlvzknzz3lueydzkzfg8qswae65e8lefj8feywjp9el06r3murqlzd27lm70z289re5zp3ftxsy2fmp0rnvuu2h04qywtgwp0s9w0tqzy8l7jz88mn34qgjglhrpj6tp2l02467twzx3jnt9204pvfwy7rxyucqvajxe5hddf8vlxlfza262fux4ggpfqh59zyjl8jm9vx064nhhcv52d39gtyntg9vsxx0gzamzzruyqf8mhed9l2hgzvgvnmzrjt856phzmuymy9edafdxx27st3ehjncz2u39h3jgars8y98p9pmqjpcajuryc6pgul2qznyxdp79jcnt4cwfzxkuyphc2n5krhd0628lzhs8d2y4et3579sfc65y0kf6u7rve8wf4yswuh74jqrhfue0rgg2qhcpxvt9mexnac0fm8f5w5g4fy92hheyqvens9xpc9t0vz3sqcjamkp2ewtvqg4dhnwxapzv2zvervr8rfzmvzau6r27q8dg6rj74az6grle535tlq0s7xyylxud3xn5znfdxf0ju3jhyxxe7zy9yxdp9zp6v2e26zydsdymk5cgppt0qegkk995l6vjxt9f7t4wrch7vd3ljxu3wkyvppg29zw4ee29fqqwm84p5edjpn4fnqm3fsr5nhnnz6ft29e020chr0v7s64ppeyl36nu63zq8lc0f7ly0jx4495vv49ayqxypmzxadnd66xmxwxs7vwlczdkmtetymgkws09rtzkg903g4qpyn3nr6uk8ch69ksr5kc268e5r3dwnnw9uupgch34n2sn85hc3xt3ggys5x8sqmr3u3gllg0y3yq5fg0pmkrvafr8qfwtdve55gdlaavdqeqq2fq04sznlnpa3xctc7rtj5gc54sugwjn5gzr6jcczu95ynpeefsd0r7ngkq3r7vhupsk7uu57dqv4x2fme
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-09-22T18:18:37Z"
  mac: ENC[AES256_GCM,data:kPmKXbZsH0M8p72ChlPtVikJmWt4TsJIl+BTodTYBG5bw+jozBj5AwTUx7v6NJiTBKCQt99ZKV8QntZh8k4g4JevCjIupuxJTmFuDFaDZu3Fm5qyzLUFxypgQ8yoOr+xuVGt6yL3o7GIeta9U9pzXG4951qJzw8Q+xf8Iz2oW68=,iv:/7VSOmDWsSnKO/VQdSN4R7XAM/5UYIOMd9zButt35iU=,tag:vwKFeWW4JJsLRiXZ8PCuxQ==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
