# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:a8uRSKGFSISu41frzta14YxHPzoxzFWPqhq5U5B7EOPzeIXKHk1yCswFAdk2KSUrkJ/LPqs=,iv:hb5j2lGYMzOXx/uhaLBmkrmCusO9oM6BzUgWyIYArvI=,tag:nVxrSH1kQPPHxFZseKpMMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDM4TjQ1UU5U
            K04rSmx4NlVtUHdKNi9JTHMrZ2VSSUM5aCtTdzNOTkVua1NsSTZPMSs3SWp1emRm
            QUlMNXpLdWpRUjBsUmlHeDdwQUJaSTFZVmx4WU9Ia2YzRWd2SW9yRzR2Njk5NSt5
            WmovWEtkR1hUL2ZINXNTZWFycXh5ZUpWVThJam1wTi9Ka0x1RzJHTjJaaHA2RUdj
            bnppblBiek1vTDZucXNXTTB4dnBDK2dvY3pvekw2WE9WaWRSZkJxYW43YmtGWkNs
            cEtOYWo2bXc0NVo1ZmR5TURQelpieVNxb2pUUThOMERvT3pXM1AxVWx3dFF5cWJT
            VThaNG9PRW9TOHg3Q2ZJOVdUZ0ovRWpoOFRvSDVObUVyMk56ODh2V1hwdFEvcktN
            ZUR4N2lVaW1CL3VHeGhUUzF4VFlEMUR5WDVhWVlnMlZDMWxKUmErV3JESGtjNWU4
            T0ZoZ2ZnNGFsM0gvSXRyM3F6NWJwdHpEVTlySlJCN2dYQk45ZkZPVU5lZVlyUFp5
            VmZQdWF2NWg5MzdSc1hzWDJDTnM5TjlCdUNNdmlHd1F0UU9Sc3hFNVVjZjh4WXFH
            bnZkbnZ6RHZ4bXdXZ2xKK2xwY0gySnJFR3lCKzFzanRaazBTUXVRbTZjRVdXQVpM
            YndVdjZrRHJYMHRGOFY3TGZGY3ZUODBaNWpLL2U5bkRWaXliZjFOQmlvbld2WFhK
            QjFqejhBVzBpL25ERmpwaGU0R0QrSE9ZVE4vQWpSTlYzQkgySjR2T1pNZXRNYVV4
            UkQ2M3RNdGRCMDRINFhBZW95ZTZLekpwV2ZUbWtZRTh6ZEFJSUx5RUE3ZXJSSXNk
            M1ZJWU1jYkpYUmxNSkgzeHc4MmRuU0s4aW91aGRTTlY0cHhsNTg1WUovTDM1UlVj
            QXlQUnFROW82OVBqYjIvWDlYMSsrRzBpSjRXT2Y3TEMyNkxpMUNJSzdRV0svaldr
            TE1WeEZ6OTlBV3FGeVkwc1kvU1NBeWFDRG9LMERDS25oc3JVZ0RuTEE0WDdxSTVB
            Q1FqRlJRQThiWFlvZHlPdWJ1OVZpZGd1Q2dDTlhyNHEvTWtVUUdFNDE0MzFORDFI
            M3B1aDl2WHJzVUYrK20vdUdBK0JBOVllNG95aWZPZ0VGQ1RLb2k4cVJHK002VEVa
            L2dsd3VLaCt6T1d2TmtiaFlPTjNCYU82a2hGSDFrTzBKeGtFdW1XM0FPZ3lSdDZI
            QTZocEtjL3V5Z045MXRpT25nRjNYZkx0SlVZZ1hyemtxVnE2SXNiNGhZem1HMUFz
            SnZRczlYb3N5dGhGSDZFQXBoSWp1ZGlmZEhsZVV3UWtiMzI4WUkybXErcWZITlBX
            a254WEIva1FBQWFtZEk1S2hXTVQ3RElpanZMc0xzTFRmeEdXSEtjd0tvSFZLYjgv
            S0kxUWpxN3ZOYk1BR2xFcjRub3U4MzBLYU43aGFpdmZkdUdNUStMa0ZvZW1ZZHBW
            ODBGZ040VVQzMnVJR1pid3Vxd1FWVVM0ODRBU0d3b3RHaGN4bDE0UGtFVnRsTlBr
            YUlid3dGSTFqaXY0a3V3T2pCQ1FMVFZ3TE91Y2VaR1Fta1o5Ymh0eHdHQUFleVhI
            aUZtekE2VmlEZnlCbkM5MHQ0NXB1MjRCbEsxOVR0dW9JVll4amw0RWkzVjM5Q1ZV
            bDVTejVGZkYwRTQwQis5SFdVYU1CUU4ydFpsZE1qL3VWQnhseU5ubHYwSXB3RmRU
            MUdKYUZKcGtGNkVNRDhPVnJ6TnlpRVRVWnJaYmcwS3I3aWt0NlJuaVMybEFaUGM5
            Qkh6emNkR01uWFE0MzRBVXRXRGh4OW1Vc0REbU9uVTFHOVkvZ25XR0xZclZiMGEx
            bXdmNFdoQkRQNkN5Q09KdXQwdERLZVV2QnFQbXJsamtIUWVzdUEyVFNxTGU1VlQv
            Y0MyakRBYzBQSGI2TWFCUzB1NzdvbjRTeTJ6cER3VHMwQUI1ZThVNGRPdFdlUQpv
            Sjg3WjVIZFZXQXlpRnc2VTBNUEUyMFdUSXVOMHFnUy9kemw4VHZrckVFCi0tLSBz
            L1BNYlQwYUh3anA5ejJaZTk3NDlsa0lKaU1NeWttMjlEU3NZaUFDT1ZVCjl62HGz
            wcZjRYBVJ38rkuyBj04ebKjMd+zGavpE/kupainUjskgpzglnNeDpXFLhun+rIF+
            aAqR/LEXbktqMnE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1z3jcsx8evc570sfle3awhzqpnwf87dt3rknwq6s9kwwknd2ymct3xajqd0jm2yqely8eqdjnd9r6asv5k405v0hk3zxleenpeyakz6m5nl9ennu4nqerz5duzq6xurtmv0pd5zqz2wd7uy9apaeec8zf8t8mdjs65cvamx9gpae9uz0kf45lez0wwd42d0qnzlskqjsyc2vmptwtx6xj3amxksyjs45grvjmjaqg7j58ed45g9x88hafqmphx30hrwk9alq73eu3gadzjhy4qg4rwf5xwpwvpvkxjqkzyws3kstmwfav7r9rmuenj2xhwfgwkgeyj5ezytyrylv2mdnny7tg27r9sxg6jvctvs9uctv4eg9dyznfnj679zqz52sztpu84raye0p9d9aadr9cj3j2zpkezttdgzgmljc87d58szj65ydpnr4uc8a6s7edj2puy8x8qydyh7yl0ngdjey0z2v736s527sy5mr0ydgag0p5t3dzrajjsl7jrx9lf3t3nwaguysc9568uryf9sjfj4dpcrps2eyhvdj9rj8uc0eqh3fsscc4pkx0jfcc0wm5j72a33ffwr8yxwmqdrgyemfvcy87vl3mw5fmnz520ddp8fzq8pw2k70e8dmqakkwwkyqlcf23cwgxsvlku42n7zhx5ssd0g2zj0mja5e2cgfjdkpmdy8u08prg878y73vzgs52cpw9y8suunhcefcrccldwewwptaw4n6hrqeaqcz848yesmhym2d2nnzkt4sw9tsjd3pz9tq2teqxq37xncqfuetntcfzauevmjftezravjc03vc05d6jtl9l9lpp5cyswnzgqhxh55l9s4q6nyauevfyg8wrwsk5prlsuzkk2s6zzqyduq5z6lghzsjc9nggvw4lsek65ggayzwx4h0whd87vf96qhmltr4hupt35ughrmhpy7f93rqcvn93jy3t087ammgzv58yeq9m8ejxmxggdn2w48fyjjy4wqtsqun5z6wfrd2z2ej89r6ca9tng6nk5qq8295hye7mrqfmjsx6mevh720gcamjseszs7s7uvkw5zs9ngg90tlsev2qm73rtkpmrct825kquwqdp85utcrfaeerc83qe6k34dccn0j9ntqj7tkyyf8xpl5zgymylvn2d6ksprue8eqf845wdvkpfg8m9jgd4ftqqepqr0vtn3j26ntzgn9h382chnw3snkhvn5mz2wgz2nayslsfv0q8m254thzw4yax8l93z6475dv5efpywv9p9zu6273azs84u5qpnxgactdcekvzuengh8xyreqpxwmsmuca25w9e9rque9ytvufg3p4ngkg74zmrssn5ykmzxgfekp6qwglwpztnjpfps4ueykr78g7cx4srk72ansxxu92ev3agk6lczf6leuk0gep63zs2rtl9ja3uwjvs0c2y97qss3yngpl9rph5z6tz8quxdef8v598sqkxccyu5zw5cyj8sw24q92gwxpjqqc5hwmwree040yrsekx9kycyfyhxsu23jyhfj9jy2yvsle4frpqcerupgwfa8rgpuggzdqvzd34xkwajxzheqt9xxlfw7hd82w5kvp7txty7f2nxxmhqsvzvmxxawnc9659wc94zy6u4c0r8fzd7hzw9krfmktcsfxvjdesx3ym6l9us648f2uqcu9jw7xteft7tptglfsmfafqk523gyrxttmhcddsf5mupzs5nvtk0eqf3nfs4slzhay9dzzrcmyzxd0srzcrqew7f3gl5t9ycnc4sh0yj679dpzd846epwmcwy7exynzc0jqveq53udqhj5d0zxvzfepcpxe0ars97krgngssyvkw2hec0vswsj3q20g8xl5syte9ez3cl2sh5uvaw7080s9kj573lyvwcklu8fvtzwhzq2am6ar
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T21:51:48Z"
    mac: ENC[AES256_GCM,data:aKk97xEXQJ0iXqdtjs78b9hcSV9JWAESQBjqAycLX/Ml1LxK5Rmy356YZOewhnO4KHjWtkihr+okhxyRCjP2ILYOmX1AsH+eS0jYjKn4prefQSpmhCV6/NTWuoCEBH4YGhB8PyDt4wR47RexcEB1ZsARRHWcEXUiW8ySlrIjPdM=,iv:krV5rxiXxC9nDL9ppJnWbyORFfaWxYiX85TXhczuJgQ=,tag:RszDgZmSNMdoeCkbIMJVLQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
