---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}-tmp
spec:
  accessModes:
    - ${VOLSYNC_ACCESSMODES:=ReadWriteOnce}
  dataSourceRef:
    kind: PersistentVolumeClaim
    name: ${APP}-pvc
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY:=2Gi}
  storageClassName: ${VOLSYNC_STORAGECLASS:=longhorn}
