---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: ${APP}
  trigger:
    schedule: ${VOLSYNC_SCHEDULE:=0 * * * *}  # Cron in UTC (CST: -6, CST: -5)  DEFAULT: Hourly
  kopia:
    # actions:
    #   afterSnapshot: "kubectl patch pvc volsync-${APP}-src -p '{"metadata":{"finalizers":null}}'"
    accessModes:
      - ${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce}
    cacheAccessModes:
      - ${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}
    cacheCapacity: ${VOLSYNC_CAPACITY:=2Gi}
    cacheStorageClassName: ${VOLSYNC_CACHE_SRC_STORAGECLASS:=openebs-hostpath}
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
    parallelism: 2
    repository: ${APP}-volsync-secret
    retain:
      hourly: 24
      daily: 7
    storageClassName: ${VOLSYNC_TMP_STORAGECLASS:=longhorn-fast}
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=longhorn}
