---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: litellm-secret
    template:
      data:
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        LITELLM_SALT_KEY: "{{ .LITELLM_SALT_KEY }}"
        OLLAMA_BASE_URL: "{{ .OLLAMA_BASE_URL }}/v1"
        # MINIMAX_API_KEY: "{{ .MINIMAX_API_KEY }}"
        # MOONSHOT_API_KEY: "{{ .MOONSHOT_API_KEY }}"
  dataFrom:
    - extract:
        key: *app
    - extract:
        key: ollama
