---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emby
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: emby
  values:
    controllers:
      emby:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/emby
              tag: 4.9.1.80@sha256:28462287162b7daa3ff91ee1810e6cc26331e35f7b7c3955b303d4864f32ec6a
            env:
              TZ: America/Chicago
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /web/index.html
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 200m
                memory: 256Mi
              limits:
                memory: 2Gi
                nvidia.com/gpu.shared: 1 # Request portion of shared GPU
    defaultPodOptions:
      runtimeClassName: nvidia
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.count
                    operator: Gt
                    values: ["0"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        # type: LoadBalancer
        # annotations:
        #   lbipam.cilium.io/ips: 192.168.20.222
        # externalTrafficPolicy: Cluster
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${INTERNAL_SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        # annotations:
        #   gatus.home-operations.com/endpoint: |-
        #     conditions: ["[STATUS] == 401"]
        # hostnames:
        #   - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        # parentRefs:
        #   - name: external
        #     namespace: kube-system
        #     sectionName: https
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: 192.168.20.21
        path: /mnt/tank/media/plex
      tmp:
        type: emptyDir
      transcode:
        type: emptyDir
