# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Odk8IP7hHUyAeu0iu6EN+VHebThkYLChK69WKzZaWjQ=,iv:UuGfMlT/phTSROShFxTI3uZWEthHLimugy80puUN9HA=,tag:EjvcILfozPTikLzNiV5DRw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEs5UitCd3NK
        SitGM0FFaDRpcUFtY1JVMHFsU0dRNzRobHFiazB6Q3NiY09yMUVXNXJIL1kwbXp6
        YnkvYTZCbnBORFAwKzl0bUJDMlJtM01wWmx0Z2V1L3lOVGF5ZlBMcyt3cnBXMmY1
        Z0lFbnFzN3A3akVaRk8xMWxLT2ZBNm5tRjhmdnVpK3VLN2RiM3Mrd1V3WC9LU09W
        bDRNK21hSHJMTGttVGpES3c2OGRYZkdFYklOc01nUzN2VldiVURrTm9RQk1TdXZq
        Wjd4N3c4NDlsOE5vQXhkdnI1ZzBMV2VpTUd6Qi9vUGhBWHhlaDAva3BiSnhZSVUv
        UUVaTWtPL3ZmZXFQMU5uRllia3k5OVNXRVFPaDgwczNVblI5TnBZQzFWM2N1Sm1Z
        end0a3Evb3RabG10TEkzNm5meENZR2VTTkFSczdxczluQVl5WlcrK1dubGZwWDJB
        aVpZeDVqUW5QV2dsWlpUNmRHUGpkbFFJajgyb3oxRjlkZWY4cytYZ1NyWE5ubzZo
        YjQ2dENXSTdLTFpMenpwTW9RZWViN0JNaHQvTzllblpETHV0QmlzOWJiMVV1S2hI
        L1cyazdkb2pwbmUzR3JWRUVFQm55K2ZibUlhR0JSNU8wajZlRVd3TkJxSExuaitG
        ZkloWmRRM2dHN1dVL21IZUFLOUFZdllDdEZoVmtsWjZXR0crSkJJSi9lUDVZR1ht
        WmF0TThHZ2JyMDZyZzhabnE5NTBlN01YdFJkalI5eUtCSHNLK3UwMkFid093cXhp
        SnJ4ak5rSE8xaUZTeDlXYVoyVnJSZ3oxWndkcUl2UzlHelFBZk9Kclh6empMekMy
        OVdKb3FiVFN4NUtuNmRCZUptd2NEUDRIMnM5bmljS29tTmtXTTZhREZtVU5CUm5v
        U2dDTlFzZFYxVmFGczliUGFMdW1KZXJQUXJaSFhwT3VycDNVVFZXVVRiWHdqVmNj
        TlJ2dFhHM1lrTkJQa0YzM0FnR2FIbDkrSlc4Ky9Ga2ZoWWxRMy9GT1l0R01YaURN
        QmRMY1BaZmhyeEdGQVZvd2hsZVJYdUt4MXZNd2YweXkweEJiajZTcGNyN3N5aWNP
        Nk9RVmJuODhFYmpZUUdvM2F2TXBTZVpMQnUwU2tzMG85dnVKV3g1SHlScWZ6QUYw
        UUEwbGZEWUlEczdjNGxUUEs1c1EwQzNmaUhPYUp3ZmFFaElaVWd0WTlWVzZjODVt
        SDlKVzg0UXZGZno2M3ZnRFhkS0kveGdRRkc2OTd5QjdTUkZPYnpyckJXVHBtZWZn
        d2FNS1RkSkd6aVRmRVI2LzJsOU9yY2NlNmw1NlUvYnFWU2hQcTZ0c1pjVCsvN2NR
        OFpOT1BYbHhnT2dVYWJvN2pqbk4xQmlGbkN4MnpxQWsxNjF6bElOV29zQ2xQaHN1
        azN4UkMyWFYwR0ZKc0ZNOENWYmYzSVNZTytjL0dmNFpsTGZ2Mmx1d0FEWXl4S1Nr
        d2pxU0J5T3h2c1E3dHBSdDBnYXZvZVhxa2RLYnlKV1pGVkpaVTVmZng0WDh5M1dF
        YmIvcWpnOFkzQnhrb28wOUNKUzJhZDhINWdtQVkwQ05wamV6VW9CUXJ2MWU2Ujg1
        UHNRM29SdVdBMWY5QVExTURuVmI3dWpNaS9GTTFuZENIdU9YbzlSWkdlZEpyejRj
        NTJSWUcvZWpjMHlMSXBYc3FpcVJJVlBUVkFqbE91ZFVtV3pmQkw2QzdyWHZFTkZp
        cEdrSlVHb0xVQll3L05WblpWNlNMN1RVdVhuTjc5elJWN2RiVnBNRy9mbk9jM0xn
        QzJCODBiVlY5eWdFd2xOUHN3UmV0WWJBTVJCc0NqSlFqOTJnRTU1cUE2UG02bmN4
        bnRhaHg5eTVQaTZ4cEE1aWFuckpyTU5EYlRrRmxGbkxZZnhzaUE0TXV0cTNESS9v
        MUFiWEJIUXpmY2N3YUJJalJ5blliOHhGN0dWbStWVENCbTJLbjZiZmtiMlJDQQpv
        SWdUckVBTEIwSmRmVGYxSmZmV0ZXSG5sOXNPZ2ZYcDh5MHJGMnZtb3RjCi0tLSAy
        K2QyVFU0clordm5SZXVCeUoxZkxHbklpR3dFZFBPNnNsTmVlcmpad0pZCjIOKckT
        Qqo8xQQ6MNHhajt7otMsMCrzl3hasUe3Z4O7owPOWwXSkCJFOtDnxq+ekT1s1RKI
        LnBxaTDlpS1i4XY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq17jrq9vucnth9v4e4gx5zvpsr6szqlcnp9mwt0rmyfyzeww97dyejlxsuvgnu4spgqgzwp9ms0dvrz4gtvc9lw6sxnjywpkq773nptcfqgvccxf6tnfq24eq4prfez8azp7k739mdcdmfx3plew9nl58e8vzwppgegzsmm4y477ycgnqcn2vpknyr3x7zm3eqd6yjrfeygt6582fp4fxpzjp5qdm3g6ncydqpq9g47p77p7cervten3snr0tr2zcptxurpfjgx6p2ux0up8a88qx8m0q6q2yreusmwe862h7rjshm8yyzmse5xsc9ydnkdjt3kz2au3lwqujsz0wy44yvvae99xxtcxejh96vjj5gcej9vwkkzq6k329lexv4qqv9rrz89r5v4qn3vd0sq3c8n8ve84gfdx75rse0xdthm9eafen5wfmc2v8ektj4yz6qlk9dm89q5xzy9vvyscc3vlrmwzfkt09eq9h3npzxr92ths4fn3zct5x9yrv5k87st3s3pqft52qplqtjlzgkpq4pp967mvtxejnnjnsf6y9yqfavh9xqgjehk0pl8sxf8z3pr3kf90esvw6fc9y8j52qnxyrrtfwk8rjj686nfp7matvx7w8cyewnz466wdl2k6l97zpe43s8t0rf32qufadeh96jz427ajnx02xzwaamvsqy65ppwpc639j244kxcpqqej9scfz5k3znxmeprr4rpdnevl6sktult2geu7psahqtpyau0pztpjlvap4zvpxdj0tqa9763pq7c626qcrs69yjyzd48pw670m7fmzh2a3kjger7xuhz6l8se2zqtsxz2e9vlshjjh3n6fz4xzpwqtcrt8f5jnnt8nqk7hj236d7rt5dzxt8sujy025uexsuqtdgfwm8v2j8fh90whg9kxhpswctytua5kete82c90jevuqytaxlqtped4kuu4wzsawnkhw3000xzp9uvtrxwerddlvzknzz3lueydzkzfg8qswae65e8lefj8feywjp9el06r3murqlzd27lm70z289re5zp3ftxsy2fmp0rnvuu2h04qywtgwp0s9w0tqzy8l7jz88mn34qgjglhrpj6tp2l02467twzx3jnt9204pvfwy7rxyucqvajxe5hddf8vlxlfza262fux4ggpfqh59zyjl8jm9vx064nhhcv52d39gtyntg9vsxx0gzamzzruyqf8mhed9l2hgzvgvnmzrjt856phzmuymy9edafdxx27st3ehjncz2u39h3jgars8y98p9pmqjpcajuryc6pgul2qznyxdp79jcnt4cwfzxkuyphc2n5krhd0628lzhs8d2y4et3579sfc65y0kf6u7rve8wf4yswuh74jqrhfue0rgg2qhcpxvt9mexnac0fm8f5w5g4fy92hheyqvens9xpc9t0vz3sqcjamkp2ewtvqg4dhnwxapzv2zvervr8rfzmvzau6r27q8dg6rj74az6grle535tlq0s7xyylxud3xn5znfdxf0ju3jhyxxe7zy9yxdp9zp6v2e26zydsdymk5cgppt0qegkk995l6vjxt9f7t4wrch7vd3ljxu3wkyvppg29zw4ee29fqqwm84p5edjpn4fnqm3fsr5nhnnz6ft29e020chr0v7s64ppeyl36nu63zq8lc0f7ly0jx4495vv49ayqxypmzxadnd66xmxwxs7vwlczdkmtetymgkws09rtzkg903g4qpyn3nr6uk8ch69ksr5kc268e5r3dwnnw9uupgch34n2sn85hc3xt3ggys5x8sqmr3u3gllg0y3yq5fg0pmkrvafr8qfwtdve55gdlaavdqeqq2fq04sznlnpa3xctc7rtj5gc54sugwjn5gzr6jcczu95ynpeefsd0r7ngkq3r7vhupsk7uu57dqv4x2fme
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-14T18:26:48Z"
  mac: ENC[AES256_GCM,data:CNnEtGUVb9wl+TEmc5dvKID+q/XI+bN6MAguJ22UURpUv+SQOULVFJihtE5gESWM9yBm92B3ucH3PPDhOWo5ZfoAYm0gMi2bRLda7nZIA5Mt2kIMYI9ebbtsppMWllGHmZ7LqceV/aVT6zFsG/d6j1aO/Cee5Os/b+coHoGPTm8=,iv:tETIisRrN0rD5KOjCY3FUayYrhkxoyar7SPuA6ZlfOo=,tag:HR4TcWQr7Fkhw2efFYYq3Q==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
