# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Odk8IP7hHUyAeu0iu6EN+VHebThkYLChK69WKzZaWjQ=,iv:UuGfMlT/phTSROShFxTI3uZWEthHLimugy80puUN9HA=,tag:EjvcILfozPTikLzNiV5DRw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2REhOdzNzYXdaNk9xbTcw
        VzM4UlFmaU9YWWk2cFBOU0hScVQ4Mkx1Z1VjCjhNUUljK2x6OGd2WjVDTnFiRnpO
        SlhjaElmRHZMZEdvRnVKczhINWZsQUEKLS0tIEFKeWVSVTE4dVVZTDluQndaZ2dx
        NXNZRkFTaUhWWWlLZU94VGFaTGtHUXcKzP5U/sa62yloEtYjLMQs+P7XJkkiaf0g
        vnaMf/FcT0/C6+Di4xkfI5uyb+k/uu97ZiDBEUNeBCcOTt9lv+t5og==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yum2rd54mjqlzzpklr209h8qukjngtj5pnn74ugwntzkl6d9fvfqrrzmns
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGU0dGtCb0Jz
        ZmpxSTlCbmlKWDQ3QU5POURoMExrbkhxbElTaG9XVWhZMjlKNGJVR2tJeE1oSHha
        VzArZXVoRk10d3kxVDFSNEZBUWVzUi9oc1B0UjlLY1lDQ0RBVVhGTlNqVDc1Szhj
        aHZJaG42dVNaVWd3K2V6S0FoR3pyMVVjZVQ0RUZOS2h0T3FVNnFJeFhnOXF0WkxU
        OUhSU0R0eFMwL2FjNnQ2aVpoNkJBemwyZURlTUZESDNjV01hdWVueDM3ekFwdjV3
        d29BSGJzK256U1FJSVRFRzJOTGtZYWVLNWlBYmNlRWc4Q2h6UXNvWTR1dzFGUVU4
        T0t1SDFPSjMzQmFRS09tVU9TQUVYM2FKOWoveGluQ1V6QU1GUWdwNUl0MzlPVG00
        WXJLYkw4UG5Bbm9keFNLQVowTlRZMXJnWEJrZlZKVGFOaEV5Mm45Z0FwRWd4R2Ex
        QzlXRnlLeS84V0F5UmNhYXI2TUV0RTFaMjdXeEp5enREb2VTQ0prQzRIVjg1Vk1K
        SDJaQ2JIZEluOGhFeEdwSUxyUWZiZEF1MkxRVE1sYUxNTnJpRDh4YjQwOEdRcVcr
        VXVqZzFIZExEdkpFY0VHWHRNMk5xTU5WQkp3a1lLQWt0MzdGU0Z5KzdPV3o5L2Qy
        RTRnZktsakVZQlc2VzFuQW9DbmhTRTN4cE1yVFlZK0piclRRbllFaUdMTTFLbjZV
        aFoxcmhUbTlWV1NLd2oyV3VEYm5qYkRpdGxzUFJRWTBncWhUcWpVQi9wdnJ4dVBw
        OTEyS2x0MWNUZkNZbnNYZ080L2xja1BYUVNoeEtkSnVtc3hBMHpvZzloMnRwVjVQ
        OFlJZkxMS05Cc2NEM3pNeFp1L3VSdEx6NEl6Sk41MjdKL2x1eVpZR1lWNGY5eklC
        QTI1bjI3OGRwUC8yRkhvN010K1l5ck9OUm1GRTBEZ0h4eHo5dXgzUVZUZ2NkQjVp
        TUdEMkhVZ0pZUFBLM0htV2VUTlNOeVYrSDI5ZEttQ0ZoNGtzdmNGdUhKMUtQWmxh
        bXdSYTI5WlJRaWlpdE5KbnFVbytyUnF3V2x4SEJUYTdHMnlUejVySjVic053QU9h
        MnlDN2RNMlBjS280NElFVFVsaExEZmJHaEtnQlVsV3BDc25BZWxnOWFZdys0Y25r
        c0FrK2gvUEtZZTlPMVpGaUxTejdwVGpYZXRmU2JTeExCZllZanRCYlFxQWl6RHZZ
        RDcrSDc3LyszU2J5a1Bsdm15M2dJdHZzU2xhR0JhS3hnamdESjIxdUlPdmxXekhs
        cndUSCs0bGg2aFRNdlVkZUZjSW8xcWFlbDd3RmNDQmpqN1ZVazBzQWdQa1RvQXVm
        b0NVOWRDVmZzR01SOVlpRndQdDA0MjRCT0o1QWQyaHozM3g1Z1BHakp3Zk9IYXo2
        emZZbDRUR3BaRUVNN1l1S0tEMWlwSi8zaWsvVXFqbk5pNElOMDRXdG0vcGUySWpk
        dFVlMENLRU1NdmpndnZpd2hUam10VW43WXg0VWdKUVpWN2ZTYThSNDhYWVVUR29v
        LzV2dVZLMHBWUko0RnBXeDJYOGUzUHprOWExays0WUtXd2xKeG9OY29QUDRnZ1ky
        dXlPc3lUaXRTWnczZE5iMmVVVVJ0d0N5ZU5wWEllbVlEbDBSR2grTVptdkhTMFc5
        T0NKL0Q0Sml1eW1UVm45dVRVZHJ4RjZXMUZuN2MyZDBqOU51ZndTTDZjY0lPWWgv
        c05CQXBaU1pFMUlPSFdSU1ZHaFN0MHNQeHpCMVRDb2lEZ1MvOFNpWVVzV1ZkY2Ni
        K2ZoYVdIWTZ3aDhheGxqZGlpak04NHFJUWt6ZkkwUU1VN0Jla09scHdpeFlOL1hU
        ME1ONjQ2MnZUWWUzZFhwVURmSUVkclhrWlZ5WTNNbk5PQjVUaHRUcmNLUERmNk02
        V240bWJUTXFBWDlCSjc0OS8rd3RHZFZIbGlNK1ZQUXliY2J2bTBDS245OGtYQQpX
        eDNvRHVWVzdxZHNQMm1pMmJ2Q0ZUeDNpblhNV2cvUnBWN2tUR290R2hzCi0tLSBs
        OFdqVy82WDdRS1h2NzdyOGx1QWxwbTFiWkNRVkQwOTJaU3d2U0ErK1FjCslzAFic
        Gg1fTElIfXFsfLe8BQ5qOAqYrGLcmFIFla93yKj27QCodSJEfH7OlOALVnhK4RLc
        0S6A8Y9CBRWv0fM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq17jrq9vucnth9v4e4gx5zvpsr6szqlcnp9mwt0rmyfyzeww97dyejlxsuvgnu4spgqgzwp9ms0dvrz4gtvc9lw6sxnjywpkq773nptcfqgvccxf6tnfq24eq4prfez8azp7k739mdcdmfx3plew9nl58e8vzwppgegzsmm4y477ycgnqcn2vpknyr3x7zm3eqd6yjrfeygt6582fp4fxpzjp5qdm3g6ncydqpq9g47p77p7cervten3snr0tr2zcptxurpfjgx6p2ux0up8a88qx8m0q6q2yreusmwe862h7rjshm8yyzmse5xsc9ydnkdjt3kz2au3lwqujsz0wy44yvvae99xxtcxejh96vjj5gcej9vwkkzq6k329lexv4qqv9rrz89r5v4qn3vd0sq3c8n8ve84gfdx75rse0xdthm9eafen5wfmc2v8ektj4yz6qlk9dm89q5xzy9vvyscc3vlrmwzfkt09eq9h3npzxr92ths4fn3zct5x9yrv5k87st3s3pqft52qplqtjlzgkpq4pp967mvtxejnnjnsf6y9yqfavh9xqgjehk0pl8sxf8z3pr3kf90esvw6fc9y8j52qnxyrrtfwk8rjj686nfp7matvx7w8cyewnz466wdl2k6l97zpe43s8t0rf32qufadeh96jz427ajnx02xzwaamvsqy65ppwpc639j244kxcpqqej9scfz5k3znxmeprr4rpdnevl6sktult2geu7psahqtpyau0pztpjlvap4zvpxdj0tqa9763pq7c626qcrs69yjyzd48pw670m7fmzh2a3kjger7xuhz6l8se2zqtsxz2e9vlshjjh3n6fz4xzpwqtcrt8f5jnnt8nqk7hj236d7rt5dzxt8sujy025uexsuqtdgfwm8v2j8fh90whg9kxhpswctytua5kete82c90jevuqytaxlqtped4kuu4wzsawnkhw3000xzp9uvtrxwerddlvzknzz3lueydzkzfg8qswae65e8lefj8feywjp9el06r3murqlzd27lm70z289re5zp3ftxsy2fmp0rnvuu2h04qywtgwp0s9w0tqzy8l7jz88mn34qgjglhrpj6tp2l02467twzx3jnt9204pvfwy7rxyucqvajxe5hddf8vlxlfza262fux4ggpfqh59zyjl8jm9vx064nhhcv52d39gtyntg9vsxx0gzamzzruyqf8mhed9l2hgzvgvnmzrjt856phzmuymy9edafdxx27st3ehjncz2u39h3jgars8y98p9pmqjpcajuryc6pgul2qznyxdp79jcnt4cwfzxkuyphc2n5krhd0628lzhs8d2y4et3579sfc65y0kf6u7rve8wf4yswuh74jqrhfue0rgg2qhcpxvt9mexnac0fm8f5w5g4fy92hheyqvens9xpc9t0vz3sqcjamkp2ewtvqg4dhnwxapzv2zvervr8rfzmvzau6r27q8dg6rj74az6grle535tlq0s7xyylxud3xn5znfdxf0ju3jhyxxe7zy9yxdp9zp6v2e26zydsdymk5cgppt0qegkk995l6vjxt9f7t4wrch7vd3ljxu3wkyvppg29zw4ee29fqqwm84p5edjpn4fnqm3fsr5nhnnz6ft29e020chr0v7s64ppeyl36nu63zq8lc0f7ly0jx4495vv49ayqxypmzxadnd66xmxwxs7vwlczdkmtetymgkws09rtzkg903g4qpyn3nr6uk8ch69ksr5kc268e5r3dwnnw9uupgch34n2sn85hc3xt3ggys5x8sqmr3u3gllg0y3yq5fg0pmkrvafr8qfwtdve55gdlaavdqeqq2fq04sznlnpa3xctc7rtj5gc54sugwjn5gzr6jcczu95ynpeefsd0r7ngkq3r7vhupsk7uu57dqv4x2fme
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-14T18:26:48Z"
  mac: ENC[AES256_GCM,data:CNnEtGUVb9wl+TEmc5dvKID+q/XI+bN6MAguJ22UURpUv+SQOULVFJihtE5gESWM9yBm92B3ucH3PPDhOWo5ZfoAYm0gMi2bRLda7nZIA5Mt2kIMYI9ebbtsppMWllGHmZ7LqceV/aVT6zFsG/d6j1aO/Cee5Os/b+coHoGPTm8=,iv:tETIisRrN0rD5KOjCY3FUayYrhkxoyar7SPuA6ZlfOo=,tag:HR4TcWQr7Fkhw2efFYYq3Q==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
