# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Odk8IP7hHUyAeu0iu6EN+VHebThkYLChK69WKzZaWjQ=,iv:UuGfMlT/phTSROShFxTI3uZWEthHLimugy80puUN9HA=,tag:EjvcILfozPTikLzNiV5DRw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG5oUGgrSjUv
        MUNncXJzb0lzM0Rwcno3MDA4WVpZT3h4aTAyQkdUZmJka0RtT3ZzeTdoU3ZsRlBl
        S29mV3hWT2pNQlY1Nm5FZm1xWWkrUWJJUFBPTDVldE14Ylh0cm55Z3VTM2Z3Qlkz
        d3JsUUJrV3dCNzNuZ1R2aDdYS1VpclhUQTVoS2hRcDA3NGJJYmlTYjhjdHVjYnlt
        Z1VDYVExNzBmbituTlhmM3F3N0QwNUxNTkZtM2xYMHdFUC9OWkdkcnlxRDB3S2Vy
        SHpFWXZERXBabXFxeUhyYWJoT0RLSWo0MWFpOGcyWDFNN3N4d0tFYWw2ajJ4OVdz
        RkVhVnpITjM1VVJyM0lxaDBmRW9sUWswRUFodytFWk9KYndFb0x4OXc5NlJWbzBK
        ckZkWXhoRmRlYmkybUFPYlZBNDVkYjBqS2IwVDRVMzFjODJrOVhrTFR4RWgwOU0y
        VnMrRlRHcE9zbXhMcFRNSG1ESUJJMEJqMzFOSWVhZkFPRklLKzhxcjViU2FSb0Nx
        QzJhNVN4eDZENlBEZERNaTRMRjFtUWdVWXM5NXJDUm5TTHM5VFMxSUxwUEpnRk9u
        WkZJZzZiT1lyVGlZQ21ydVJmZTNzUW9BRFhzSkcyMU5Tb0pZNTFyUUNLcTBuTFJh
        NndaVUhPakt4QUFUQUk4Tzg0SzFUTUFVanJDaVZzaEZwMkdXUUs2eGx0ajVXazkz
        VTlycEltK0ZjLzJQVWZUUHFycURYbDNTek5qYjJGQjU3bG1NUURDQXprbFcxRVdj
        bFpLMWo0aldyRTRSNkpIM29sZ2dXMlppVEdIWU1mdldLQ1NPelhMSitDaHdvbGNK
        bmhjTEdUcndoNmJMQWpIcTRRbnRzaHV5Wml2NVE4KzhlM0VvSnFQcHV3cWVmUjBT
        MXpwYUtXQWQ4WjZsZHQwRUtsQkU0SmZDK3Rya2lWQVczMmM5T3V6Q1ZmbW93Znl0
        aUpvNkFRSDFLSFFZRHd2UXF4OWc0RmVic01raC9GcVdHZW41cm9NcERVWDI5c2x1
        TUdzcWFlM2U3eVdMN2NzN24rb0hCUG9ublZBeTNPQ0JWWXBSU2dhVE0vV2pQQ1Fq
        V1dPa1FzcFdDZk8zL25vM1JOQmZta2xnZ290NEtaMEJVODl2SE01MnExK3BaeDVW
        U0RzYU95YkNCdVhXVjhyQmFKeWlrMklMVW92ckxnOUFkRUpBZG9WaDJlajRuQTEx
        NUc0bGdiOGovbnowTHUyRStIU1plMmVnc2VpWi9GYlJFNmQ2YlVZYUxlRG9PY3Vt
        bFVkVHpnVXM3TFVMQkpPZWFyeUhxTWV4dVRwSG9zZWh4K3NZem54eFkyb0MyQyt6
        V25PcXk3VDQ3a3pGZi9vZTBuN3BHMjJXczJuVnd5RXFCWmNFaHFwWEtTamdDa2c2
        WXBLY05paklrS0czMnFCWXhCR2pTbVpKU21YR2NwZXZEejFPQWV3SSs5NXVHZVl5
        Smg0NFhQTmx1ejVWY2gzYi9yVXQ1Qm0rWmpCb2w3cUR3UG82bmZBOUhBR1V0eXVu
        bE9GNE9ZdzNKaVphcjJCV2I4WTNpWkpTZ0xuTUw5WVJvTVRhQ2RDYXNyVHppTUpt
        L284MEpCWHB6djZsN3NGZjd1NnpBc0ZQV2d0WjhsdjV0aXkvZGpobWFMcVBFdHZR
        dHo0RHdieFk2dXI3YkNXQ3ArVlBmZGFSZTFtb3ErQUF3RHRkbHEvTFUzVXlBdmp1
        VFNJTGZIdzNoTDlWRUJEaU1LS2d1WUhsNUtXb0JJZEI0TS9heG92Z25ZZUdrVVBs
        UmpiWVdpTG84c3EvZGxhT3c0RUhDOWdJNHp3SUptVVlac0ZNMWpZWm5RVXd6cy9E
        L2tITmhqVi9XVnE2RlJRdTFlTGFxd2RJQURzSGVvNlJhVUovLzFQaE8yNndGZExS
        dXJqQ1dwUEM2V21OT0FGQ05OT29kUGFxaDkrU0V1bkJiV25JcVI1NmVsUjhXZwpx
        eVl1WW8zVXVDLzFpRko4b2RZZlloNHlOajVnbDBTM0VzejFhUzBxd3p3Ci0tLSBB
        ZzRySEJxbExwSm4xemFUN1MyTGEwQi9PR1g5WEtXOFN5R2tXTlVDT0VRCiBtfahs
        YWd+r43J9OWUBzs0WUppBOwK3geDClwsnshLxoavPZ5B3iI8IJ/m5XZVlHg+Axdj
        J90LbofT3eeiGvA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1z3jcsx8evc570sfle3awhzqpnwf87dt3rknwq6s9kwwknd2ymct3xajqd0jm2yqely8eqdjnd9r6asv5k405v0hk3zxleenpeyakz6m5nl9ennu4nqerz5duzq6xurtmv0pd5zqz2wd7uy9apaeec8zf8t8mdjs65cvamx9gpae9uz0kf45lez0wwd42d0qnzlskqjsyc2vmptwtx6xj3amxksyjs45grvjmjaqg7j58ed45g9x88hafqmphx30hrwk9alq73eu3gadzjhy4qg4rwf5xwpwvpvkxjqkzyws3kstmwfav7r9rmuenj2xhwfgwkgeyj5ezytyrylv2mdnny7tg27r9sxg6jvctvs9uctv4eg9dyznfnj679zqz52sztpu84raye0p9d9aadr9cj3j2zpkezttdgzgmljc87d58szj65ydpnr4uc8a6s7edj2puy8x8qydyh7yl0ngdjey0z2v736s527sy5mr0ydgag0p5t3dzrajjsl7jrx9lf3t3nwaguysc9568uryf9sjfj4dpcrps2eyhvdj9rj8uc0eqh3fsscc4pkx0jfcc0wm5j72a33ffwr8yxwmqdrgyemfvcy87vl3mw5fmnz520ddp8fzq8pw2k70e8dmqakkwwkyqlcf23cwgxsvlku42n7zhx5ssd0g2zj0mja5e2cgfjdkpmdy8u08prg878y73vzgs52cpw9y8suunhcefcrccldwewwptaw4n6hrqeaqcz848yesmhym2d2nnzkt4sw9tsjd3pz9tq2teqxq37xncqfuetntcfzauevmjftezravjc03vc05d6jtl9l9lpp5cyswnzgqhxh55l9s4q6nyauevfyg8wrwsk5prlsuzkk2s6zzqyduq5z6lghzsjc9nggvw4lsek65ggayzwx4h0whd87vf96qhmltr4hupt35ughrmhpy7f93rqcvn93jy3t087ammgzv58yeq9m8ejxmxggdn2w48fyjjy4wqtsqun5z6wfrd2z2ej89r6ca9tng6nk5qq8295hye7mrqfmjsx6mevh720gcamjseszs7s7uvkw5zs9ngg90tlsev2qm73rtkpmrct825kquwqdp85utcrfaeerc83qe6k34dccn0j9ntqj7tkyyf8xpl5zgymylvn2d6ksprue8eqf845wdvkpfg8m9jgd4ftqqepqr0vtn3j26ntzgn9h382chnw3snkhvn5mz2wgz2nayslsfv0q8m254thzw4yax8l93z6475dv5efpywv9p9zu6273azs84u5qpnxgactdcekvzuengh8xyreqpxwmsmuca25w9e9rque9ytvufg3p4ngkg74zmrssn5ykmzxgfekp6qwglwpztnjpfps4ueykr78g7cx4srk72ansxxu92ev3agk6lczf6leuk0gep63zs2rtl9ja3uwjvs0c2y97qss3yngpl9rph5z6tz8quxdef8v598sqkxccyu5zw5cyj8sw24q92gwxpjqqc5hwmwree040yrsekx9kycyfyhxsu23jyhfj9jy2yvsle4frpqcerupgwfa8rgpuggzdqvzd34xkwajxzheqt9xxlfw7hd82w5kvp7txty7f2nxxmhqsvzvmxxawnc9659wc94zy6u4c0r8fzd7hzw9krfmktcsfxvjdesx3ym6l9us648f2uqcu9jw7xteft7tptglfsmfafqk523gyrxttmhcddsf5mupzs5nvtk0eqf3nfs4slzhay9dzzrcmyzxd0srzcrqew7f3gl5t9ycnc4sh0yj679dpzd846epwmcwy7exynzc0jqveq53udqhj5d0zxvzfepcpxe0ars97krgngssyvkw2hec0vswsj3q20g8xl5syte9ez3cl2sh5uvaw7080s9kj573lyvwcklu8fvtzwhzq2am6ar
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-14T18:26:48Z"
  mac: ENC[AES256_GCM,data:CNnEtGUVb9wl+TEmc5dvKID+q/XI+bN6MAguJ22UURpUv+SQOULVFJihtE5gESWM9yBm92B3ucH3PPDhOWo5ZfoAYm0gMi2bRLda7nZIA5Mt2kIMYI9ebbtsppMWllGHmZ7LqceV/aVT6zFsG/d6j1aO/Cee5Os/b+coHoGPTm8=,iv:tETIisRrN0rD5KOjCY3FUayYrhkxoyar7SPuA6ZlfOo=,tag:HR4TcWQr7Fkhw2efFYYq3Q==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
