---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stirling-pdf
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: stirling-pdf-secret
    template:
      data:
        SECURITY_OAUTH2_CLIENTID: "{{ .STIRLING_SECURITY_OAUTH2_CLIENTID }}"
        SECURITY_OAUTH2_CLIENTSECRET: "{{ .STIRLING_SECURITY_OAUTH2_CLIENTSECRET }}"
  dataFrom:
    - extract:
        key: stirling-pdf
