---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kometa
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kometa-secret
    template:
      data:
        KOMETA_DISCORD_WEBHOOK: "{{ .KOMETA_DISCORD_WEBHOOK }}"
        KOMETA_TMDB_API_KEY: "{{ .KOMETA_TMDB_API_KEY }}"
        KOMETA_TRAKT_CLIENT_ID: "{{ .KOMETA_TRAKT_CLIENT_ID }}"
        KOMETA_TRAKT_CLIENT_SECRET: "{{ .KOMETA_TRAKT_CLIENT_SECRET }}"
        KOMETA_TRAKT_AUTH_ACCESS_TOKEN: "{{ .KOMETA_TRAKT_AUTH_ACCESS_TOKEN }}"
        KOMETA_TRAKT_AUTH_REFRESH_TOKEN: "{{ .KOMETA_TRAKT_AUTH_REFRESH_TOKEN }}"
        KOMETA_PLEX_API_KEY: "{{ .PLEX_API_KEY }}"
        KOMETA_RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        KOMETA_SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        KOMETA_TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY }}"
  dataFrom:
    - extract:
        key: kometa
    - extract:
        key: plex
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: tautulli
