---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homeops-bot-pem
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homeops-bot-pem
    template:
      engineVersion: v2
      data:
        private_key_pem: "{{ .GITHUB_APP_PRIVATE_KEY | b64dec }}"
  dataFrom:
    - extract:
        key: github-app
---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-github
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: renovate-github
    template:
      engineVersion: v2
      data:
        DOCKERHUB_USERNAME: "{{ .DOCKERHUB_USERNAME }}"
        DOCKERHUB_TOKEN: "{{ .DOCKERHUB_TOKEN }}"
  dataFrom:
    - extract:
        key: dockerhub
