---
# yaml-schema: https://kubernetes-schemas-eov.pages.dev/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-github
  namespace: renovate
spec:
  discoveryFilters:
    - "mrdynamo/home-ops"
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: '["pnpm run bundle"]'
    - name: RENOVATE_REDIS_URL
      valueFrom:
        secretKeyRef:
          name: renovate-operator-jobs-dragonfly
          key: url
    - name: DOCKERHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: renovate-github-secret
          key: DOCKERHUB_USERNAME
    - name: DOCKERHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: renovate-github-secret
          key: DOCKERHUB_TOKEN
    - name: RENOVATE_HOST_RULES
      value: >-
        [
          {
            "hostType": "docker",
            "matchHost": "docker.io",
            "username": "$(DOCKERHUB_USERNAME)",
            "password": "$(DOCKERHUB_TOKEN)"
          }
        ]
  image: ghcr.io/renovatebot/renovate:43.136.1
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * * # Run every hour
  secretRef: homeops-bot
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-webhook-token-secret
        key: token
  provider:
    name: github
    endpoint: https://api.github.com
