mappings:

    # ifstats mapping
  - match: 'servers_(.*)_interface_(.*)_if_(.*)\s(.*)'
    match_type: regex
    name: 'truenas_interface_${3}'
    labels:
        hostname: ${1}
        device: ${2}

    # dataset metrics mapping
  - match: 'servers_(.*)_df_(.*)\s(.*)'
    match_type: regex
    name: 'truenas_dataset_${3}'
    labels:
        hostname: ${1}
        device: ${2}

    # memory metrics mapping
  - match: 'servers_(.*?)_memory_(.*?)\s(.*)'
    match_type: regex
    name: 'truenas_${2}'
    labels:
        hostname: ${1}

    # zfs arc metrics mapping
  - match: 'servers_(.*?)_zfs_arc_(.*)'
    match_type: regex
    name: 'truenas_zfs_arc_${2}'
    labels:
        hostname: ${1}

    # processes metrics
  - match: 'servers_(.*?)\.processes_(.*?)'
    match_type: regex
    name: 'truenas_processes_${2}'
    labels:
        hostname: ${1}

    # LA metrics
  - match: 'servers_(.*?)\.load\.load_(.*?)'
    match_type: regex
    name: 'truenas_load_${2}'
    labels:
        hostname: ${1}

    # rrd cache metrics
  - match: 'servers_(.*?)\.rrdcached_(.*?)'
    match_type: regex
    name: 'truenas_rrdcached_${2}'
    labels:
        hostname: ${1}

  # swap metrics
  - match: 'servers_(.*?)\.swap_(.*?)'
    match_type: regex
    name: 'truenas_swap_${2}'
    labels:
        hostname: ${1}

  # uptime metric
  - match: 'servers_(.*?)\.uptime_(.*?)'
    match_type: regex
    name: 'truenas_uptime_${2}'
    labels:
        hostname: ${1}

  # disk metrics mapping
  - match: 'servers_(.*?)\.disk-(.*)_(.*?)_(.*?)'
    match_type: regex
    name: 'truenas_${3}_${4}'
    labels:
        hostname: ${1}
        device: ${2}

  # cpu and nfs metrics mapping
  - match: 'servers_(.*?)_(.*?)-(.*)_(.*?)'
    match_type: regex
    name: 'truenas_${2}_${4}'
    labels:
        hostname: ${1}
        device: ${3}
