---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/trust.cert-manager.io/bundle_v1alpha1.json
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: root-ca
spec:
  sources:
    - secret:
        name: "cluster-ca-cert"
        key: "tls.crt"
  target:
    configMap:
      key: "ca.crt"
    secret:
      key: "ca.crt"
