---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.1.17
    digest: sha256:f8f6663fee87a64ff143dc3a190f6de0381e2c8e1dfcbd7287bf7d3e5d760e44
  url: oci://ghcr.io/home-operations/charts/tuppr
