---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.1.18
    digest: sha256:0c961c420a1f57be7d59c52570da553508036fce54290cd17bb046bd84befcaa
  url: oci://ghcr.io/home-operations/charts/tuppr
