---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./bazarr/ks.yaml
  - ./dispatcharr/ks.yaml
  - ./echo/ks.yaml
  - ./echo-internal/ks.yaml
  - ./homepage/ks.yaml
  - ./maintainerr/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./seerr/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
