---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: blackbox-exporter
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 11.9.2
    digest: sha256:ce001525a832ebea6dbee1cee93c5f73877c41749fa616fb46ecc3dcf7c568da
  url: oci://ghcr.io/prometheus-community/charts/prometheus-blackbox-exporter
