# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
# apiVersion: monitoring.coreos.com/v1
# kind: Probe
# metadata:
#   name: icmp
# spec:
#   module: icmp
#   prober:
#     url: blackbox-exporter-lan.observability.svc.cluster.local:9115
#   targets:
#     staticConfig:
#       static:
#         - expanse.internal
#         - garage-door.internal
#         - hdhomerun.internal
#         - idrac.internal
#         - kiosk.internal
#         - kvm.internal
#         - pikvm.internal
#         - receiver.internal
#         - ups.internal
#         - vacuum.internal
#         - zigbee-controller.internal
#         - zwave-controller.internal
#   metricRelabelings:
#     - targetLabel: service
#       replacement: blackbox-exporter-lan
#       action: replace
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: tcp
spec:
  module: tcp_connect
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - nas-01.ad.${SECRET_DOMAIN}:2049
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter
      action: replace
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: tcp-tst
spec:
  module: tcp_connect
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - nas-01.ad.${SECRET_DOMAIN}:2048
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter
      action: replace
