---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snapshot-controller
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.0.3
    digest: sha256:32608957de4e19e0c97890e56c56ae36c3b16b6ea96513904fd03af1edca05d2
  url: oci://ghcr.io/piraeusdatastore/helm-charts/snapshot-controller
