# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Yj80wnuS1ZrzOd95HMlkBLzyrQrnTrJ901R27ze6FrGRMtN7GVEVaiM4kNfx2N6Rsl6++Wv6Kf6679O4YjLZLV7zUEA0OgYst1tM1S3AiiLy0ssW8ZPIN8oqxJdUW8q9UeJeHP4g5c9rWtSTjPN8pKJNpj+kPdn7iNwJnw72xTIasR3WZgUWzVpONKF6zQgQyI6TJbHVHp/OEqAeQ1MYSCYMxzUzsa0fCeFewImgY5X+fz7a,iv:ep+ZMtu3RTkFyoh36MuCM0xl7/OFPlE7LPDEMnyDjtQ=,tag:AXikCwjswMVFR/0bBPP/1w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEZpc1hraTRq
        WWUySVJmNFNVT0JwV0dFRktRTExsK0t0RFpKVEExS3g5ZTlTd014RWYwdGhtNUw5
        OXVra3J0aVBPNXZkdksvTzc4WWNQbVY5Z2s5dzZCdTBXeERBaDUrbVpSR1Vnc2Qx
        L3BzR0RDYUhBZGZiSzFleWdIY2U0NVE4Qm01U3JaaWNCTDlKSElhRW9jY3Nib3N5
        WWN2M0hmc04yc0o1UlRFVFg2VUhidFFYM3FKSk5INlczc09GRi9xN2JWMjlSUW1C
        Mnd4Tkl1OFhtQlhUU2M2KzRNeG9SL1lka3dDN3kzdmU0Sm5jRitocEIweDVsLzVE
        dFpHdHZMcnJ5bnFYZ21wOEM2TGlXNWY2ZGIrM2g2Y2lNUWRJeG9IczdoUTVkYVU5
        QWRuM2RSREhwTGZnd0ZLUWQvRWZoTU1DUzk5TFNFbXJrM3pmUEdrZ0ZNQ011bTRt
        OUM5LzlhMUdNanhzY1Jia1QrZmR6VjVBZUJLNEJ0Z2xCcHQrcmU4TUpIWWd6aXc0
        QVBQeHBMOE5NcFRmelJOMDdxejJlN3lxWHEvb0ZaOElZekpKTGFxUnI4eTU4ZzBQ
        b1NiRjlhL1BtR0FQeUtwMTVLRURQNllpWkVXbmNuaGJBeWlDeDVEaUVGTHpRVCt2
        WkxIRGV1TnMyYlAzRlJ6Z3RlS0VUdkJaTDNsUkNKQnQ5NlJTUldIREZhZTNDVDZV
        S0pOTDd4NlBrQmIvR3lyVHl4UHJoeWZSckpNeVV1L0Vtby90eWNzeWhrWlJwR0xM
        dlJtemIyNFYrWlkrOFY2Ry93UjJudnRudE94eC9xYkxoRVRoaURFRjBWSGtwQnlY
        Q0Z2S01WanRZd1BUMGpObEpyZDNReDJzazYvL0RwUzhGT0NBV0RXN0J4NDhTM2Ex
        WHBEOVc4c25pWVQraWpNNS92Unp6bXNyUU56bjloM1JMN3ozdmZtMnhBYnhIU0Q2
        S3l0clE0QjV0K0c4a1dqL3d4K1Q1QVZSc2NVeXl5OSsyLzVINVA2TzlaallsSjFh
        UVBUam1MaHdVbmh5ZURwTlZoWmluRlZoUFZoeHU1cVhsSE52NG43M05EMGlubWhC
        d0hrRThvY2l5RnlBSkF1blV2QTk3SXE1cld2UkVRZ2s5WjcxaHQ1N1M4R054c3pa
        dnJnbEpJdlh2MHRJYjBSL0M0dmMyOE5oaDlSWTNQVEZjS2VZUEhNR2tweXBDUUYx
        cE4yTUdtVEFSVUtYMXJaaEVUeWcrYWIrd2dNT1pzSXJCQlJubVptSEd6cUM5eFNT
        NEJ2bU1WbklTS1lMNlRUVnVQLzBiK21LRVNsMEFnZ0VKT3RvYThCY1VOSnBITW1Z
        SS9WKzZJa05KUGF4RG4yMWlSNW1VaFNocTc0dnpsd0wyY0JrWlEzNGpLdFBxL1BM
        MGIyeG8zVUhxdjlCc29lZVlTMXlXeVFHQXBIaDFRY3RhSTlUUjdJVG5DYmdISEdN
        ZElVTm5aNTNxMEJMcW5SeWZUVGNta3ZqL2U3WFhqQ3JOMzhzY1dadFc5OUNEV0ZO
        OTdoM0tNUCtlQWdlanFXcFVqQkZBV0o3ZHEwRitVcU1CcE9pL0hQeXZRMDFMV0NC
        SmhLbUZkSmpXS1ZCTTkwdG5xVk1qc0hxUHppanpSV1FYYUJtQ0Y3V0JTR1o3UkU3
        NGhKVVd4eFhJWElpNkJhTjkxYjY1RnA1Wi90QUY0dmU3U3RKdXpzM2E0OTY3VmhT
        N1dHaHRlVkNEQThZR1BCNTVESU1nRHppUkJLaThBQXczUlg3dlRGaDF4TmFZd1py
        VXBRWEFWVWNUUC9haFhQTXIyOGlsaEcvMHp6bmp1NHc0SmdEYWdCdzVkRE1GYmhi
        SUpmRW4rZkxnc1pZejNnejlyWmh5ZWVQL0hQYlN1MVFhUEhLcTdFUDAyOVpkUXFF
        NEN0bmd0OFhMdlFicERZek04MlI0YlAwc1Z6dVoxTjd5SjdXcktaYm9OaTZaUQpF
        Rmk2a1hjSHlTVmw5RVdyNk1wVE9ZQUxBK0RVSC9PTy9pK1pQV1VwR29NCi0tLSBG
        WFIxR3RSTXpld01vTmtLU1UyelR6Tlh0cHVaM1FNNmhLNEpRTnFMek9ZCgEbdhkq
        beJY993z9Ru1SZh3DniK5qfQXDnyViyZ/3FjVpdM/ZxhCs0KuUGdRn0Ns9BzHSPZ
        t9Rfw0WEqGIxSrs=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1z3jcsx8evc570sfle3awhzqpnwf87dt3rknwq6s9kwwknd2ymct3xajqd0jm2yqely8eqdjnd9r6asv5k405v0hk3zxleenpeyakz6m5nl9ennu4nqerz5duzq6xurtmv0pd5zqz2wd7uy9apaeec8zf8t8mdjs65cvamx9gpae9uz0kf45lez0wwd42d0qnzlskqjsyc2vmptwtx6xj3amxksyjs45grvjmjaqg7j58ed45g9x88hafqmphx30hrwk9alq73eu3gadzjhy4qg4rwf5xwpwvpvkxjqkzyws3kstmwfav7r9rmuenj2xhwfgwkgeyj5ezytyrylv2mdnny7tg27r9sxg6jvctvs9uctv4eg9dyznfnj679zqz52sztpu84raye0p9d9aadr9cj3j2zpkezttdgzgmljc87d58szj65ydpnr4uc8a6s7edj2puy8x8qydyh7yl0ngdjey0z2v736s527sy5mr0ydgag0p5t3dzrajjsl7jrx9lf3t3nwaguysc9568uryf9sjfj4dpcrps2eyhvdj9rj8uc0eqh3fsscc4pkx0jfcc0wm5j72a33ffwr8yxwmqdrgyemfvcy87vl3mw5fmnz520ddp8fzq8pw2k70e8dmqakkwwkyqlcf23cwgxsvlku42n7zhx5ssd0g2zj0mja5e2cgfjdkpmdy8u08prg878y73vzgs52cpw9y8suunhcefcrccldwewwptaw4n6hrqeaqcz848yesmhym2d2nnzkt4sw9tsjd3pz9tq2teqxq37xncqfuetntcfzauevmjftezravjc03vc05d6jtl9l9lpp5cyswnzgqhxh55l9s4q6nyauevfyg8wrwsk5prlsuzkk2s6zzqyduq5z6lghzsjc9nggvw4lsek65ggayzwx4h0whd87vf96qhmltr4hupt35ughrmhpy7f93rqcvn93jy3t087ammgzv58yeq9m8ejxmxggdn2w48fyjjy4wqtsqun5z6wfrd2z2ej89r6ca9tng6nk5qq8295hye7mrqfmjsx6mevh720gcamjseszs7s7uvkw5zs9ngg90tlsev2qm73rtkpmrct825kquwqdp85utcrfaeerc83qe6k34dccn0j9ntqj7tkyyf8xpl5zgymylvn2d6ksprue8eqf845wdvkpfg8m9jgd4ftqqepqr0vtn3j26ntzgn9h382chnw3snkhvn5mz2wgz2nayslsfv0q8m254thzw4yax8l93z6475dv5efpywv9p9zu6273azs84u5qpnxgactdcekvzuengh8xyreqpxwmsmuca25w9e9rque9ytvufg3p4ngkg74zmrssn5ykmzxgfekp6qwglwpztnjpfps4ueykr78g7cx4srk72ansxxu92ev3agk6lczf6leuk0gep63zs2rtl9ja3uwjvs0c2y97qss3yngpl9rph5z6tz8quxdef8v598sqkxccyu5zw5cyj8sw24q92gwxpjqqc5hwmwree040yrsekx9kycyfyhxsu23jyhfj9jy2yvsle4frpqcerupgwfa8rgpuggzdqvzd34xkwajxzheqt9xxlfw7hd82w5kvp7txty7f2nxxmhqsvzvmxxawnc9659wc94zy6u4c0r8fzd7hzw9krfmktcsfxvjdesx3ym6l9us648f2uqcu9jw7xteft7tptglfsmfafqk523gyrxttmhcddsf5mupzs5nvtk0eqf3nfs4slzhay9dzzrcmyzxd0srzcrqew7f3gl5t9ycnc4sh0yj679dpzd846epwmcwy7exynzc0jqveq53udqhj5d0zxvzfepcpxe0ars97krgngssyvkw2hec0vswsj3q20g8xl5syte9ez3cl2sh5uvaw7080s9kj573lyvwcklu8fvtzwhzq2am6ar
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-09-22T18:18:37Z"
  mac: ENC[AES256_GCM,data:C6GERmwxcoiJR238zlWIj/2oZ8Uyo6S+kS04tXLET8iJlLBNBBNrZ6ENte9t9eI3kZnDAQaJB+dUg3AtvDPOJsHIbX2PbvLt0bl3tJ3uxA2l8gVBcJXEi3og6ZcCmp+PSgQ8dTfw6dMtYm1gQOICwmprGbo8gLfH7vd61Q+YIoU=,iv:OywPMQWFAGZ/GVM9mLTKtM7gw8AmhAVyCDLP+vS5iyM=,tag:1VxZ86mQpMsY2jfPjMxgag==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
