# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Yj80wnuS1ZrzOd95HMlkBLzyrQrnTrJ901R27ze6FrGRMtN7GVEVaiM4kNfx2N6Rsl6++Wv6Kf6679O4YjLZLV7zUEA0OgYst1tM1S3AiiLy0ssW8ZPIN8oqxJdUW8q9UeJeHP4g5c9rWtSTjPN8pKJNpj+kPdn7iNwJnw72xTIasR3WZgUWzVpONKF6zQgQyI6TJbHVHp/OEqAeQ1MYSCYMxzUzsa0fCeFewImgY5X+fz7a,iv:ep+ZMtu3RTkFyoh36MuCM0xl7/OFPlE7LPDEMnyDjtQ=,tag:AXikCwjswMVFR/0bBPP/1w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRHhCcnI4UFMzSk5rK2ZE
        aloxYWJyU0dmdmhtZm5pK1h6ZktlTDFFRTFFCldCOXc5Sk4xbFhvWURwNnMvRkxp
        NGpEckg3SFM3Z2VpM2xGeTVJcVQrVUUKLS0tIElFSVZlL25oUnlpb3l1dnpuSm11
        QnZaNFRyM0NpYXRBZGVKZXM3TlhGNGcK9rR2v+i9XfafS+W29CQf8qPqQZUPsDzy
        VNnuWiRFWnfBKDUCsq3FTLZtD7+UMB+usLpVvteWTgg5Td4sVkgv5w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yum2rd54mjqlzzpklr209h8qukjngtj5pnn74ugwntzkl6d9fvfqrrzmns
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFNvQmtIeFQ5
        Tmx6cHQ5UjFFZ3pEdGRyUjFOZHdvR1N4bU5pd1VwRUpqdmN4dktVNU16eDBRVnlH
        UTNyTHFhcjJISlNSd0FoZTQxc1N3TWJMM05rTlloa29Xb1BwcVk5c0M0UzVHQmhM
        NFVISGU1b3lqMms2UUtsVldQTmFXMkVQNDNTZkJnMWZ5dS84SXlXWnh0aHBESVNZ
        TENhTU5QTmVPSmJqM3FMVGc4UTRKdGxKYnpOMmJidDJPbHQ1WlBzQ0o5RHlJb0cv
        T2JoRmRFMkN4V0lZRFhPcEc2N2xFNTNjUmpjek9yM1c3ZUJnVG03SW82ZGwyNktW
        ejF5WEhYYXJzWUtmL0dMd3FHMVY3Rkx3THVEUUtLVHVwNW5uaHFCVzA0d1lTaTlO
        a3RteCtpTVM2K0RnK2tpbjFYY0RaakZoQzYxOWQreC9KSHZNdnp1N0tZL0k0aXdW
        MzJaaXhKWDVTU2JNc1FpVGttS1BWMFhWYzNYU09PNkN2RGZaTGNCTWtuMkdZS05W
        VEVCUWJlZFBicU43YTI2Q1pValhUZFg4SXkwazVmSDk1QXRKWEl5Rk1wUmk0S0ZZ
        SjVZbmowRnZCVUlWOWRmai9RYU1vV3ZKZmVjVWhYanNiTFUvd1htSlI1M3JKSHVj
        bUVWa1VNY2pLZUIxbE1QL2RGekQ0a0JpN1h6K0ZVT2l4NGdMcWtoU0gvelQ4K09R
        Z284MCtKMzhhNzNVV3liUkxjSk9EVmNOUGpxZkpzVDJVY1F1Z1hZYVp6cy9HbDEx
        Zmk2dHhCT1lPZkEzUHVWdk5PZkRZb2ozcTZabmlnelRLSFEzQlBLb0M1aWZ5VWlP
        T1U2M0w5QXhJN2svYkJtbkFWMGFobElOL21RYnpjVVd4ZHhDdXZFaGl5TnVXS2JI
        T2pneGlmNnJRSGpzOXFFRGt2R3lHNHFvUUZtTHRrK3cyMGRTWDJ4RWFzemlaMnI2
        dC8xWVFoeFJWcGpJRThpQ1BWYkc5MTJ5UUJuU0NNZTNuL0dINEZVcU85ZExIMnN6
        alRVV3FucnJ4anNXMkYvUWQxMXJnZXVwVFlSY1pWYm5ER0grLzhGUkthRzE5UUhh
        dHRnMjlMZnFKdFNaK2V2MzJPODVnOXFCUUk3cUV4WS9IOUFNaE5PcVMxVnExakgv
        cmordjJEcTNaSUt5OXBlbXpzdXIxVWpRUk5vVHVnVzJmVFBRbnlHRk9hS3owbzds
        Mk9oRHRXcG5CUHJaQTkxakd2QlFSbnZGVDZsSGorNkcyZ1dhenN3UXZZQXUyeW9S
        cXdzRk00TStJMzYvZ1ZMVnY2b3VjRGUyQ0xyM2RJVTNVTWdnUE1sL3R2MFFvdURi
        c2pjRmhjNldVZHRQZnVTREV4NE1FdVEybm0zRnZyUk4wRlp4YyszVkZKT1VvNUhW
        ODB4SFRjczg4cHNPNmpsWmxPRmcrQi80bjdhUzZiVG1EZnkyQVZ4MHQ3eWNaOWxj
        V2lGNEtoeEhiWGVaakJQek5mN1JDNlorRFpnTlo1bzN2V2dma2cwYlJsWGZrV3Zu
        WDBjMi9Pd0d4Y1FLL2RHOTFyYkNYdlRKVHZSZUxtVjA1eEtKLzlrdDhGajVrUGR2
        N2Y3L2dCV3RiUDk4Ujh1amxxQjV0K2orMWhMSGtUZ3NaTVZWbmNwblM1WmlCSDVI
        by9jNytPRm43TTVrSFd2NXpDVTYzVXBvVnAxOEI4ZUZNRE56K2FQQUFSRzlVUWtP
        NS9xWTQrZGhkVXdlZVh4ZHdrTkJ2YTRzTlpFQ3htZmRQc2dzay9hcE5oREdwWjJP
        L3hCK3UyUUdDOTFHWTdEMHMzeTlYb04rdUtyWVVsT1B5U1dNODZJczFQN3ExcGxD
        NURSNEExcnNmWDdLWGpjaUJMVTZkTXpxTzR2WGhrWk95UW9EVjdnRGVxN0trcW1t
        WC9mNW9kRlVJa1VHZ2Z2R0FTYmdEZThjbDZmYzljUVBsQjN0MGJzTnJtWXBUQQo2
        TDBTY05CbkhQL3loV2U2aXNjWHZEUGtJU3VUSEl3cGh5ckMwSWp0ckdrCi0tLSBw
        eDhTNHJ0YzdNODZPTlV1M0xHbHhRc0o0b2tsd1ZyL0FlYXFpaEpCeVBBCuPusVW8
        v70S/Bp41AknXj8ZRhGP1vzW7Gsn1sLyIM6DKDLijUsSV2svkVVrzbcCQKD8IaeS
        zISMdTx4T+XufIw=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq17jrq9vucnth9v4e4gx5zvpsr6szqlcnp9mwt0rmyfyzeww97dyejlxsuvgnu4spgqgzwp9ms0dvrz4gtvc9lw6sxnjywpkq773nptcfqgvccxf6tnfq24eq4prfez8azp7k739mdcdmfx3plew9nl58e8vzwppgegzsmm4y477ycgnqcn2vpknyr3x7zm3eqd6yjrfeygt6582fp4fxpzjp5qdm3g6ncydqpq9g47p77p7cervten3snr0tr2zcptxurpfjgx6p2ux0up8a88qx8m0q6q2yreusmwe862h7rjshm8yyzmse5xsc9ydnkdjt3kz2au3lwqujsz0wy44yvvae99xxtcxejh96vjj5gcej9vwkkzq6k329lexv4qqv9rrz89r5v4qn3vd0sq3c8n8ve84gfdx75rse0xdthm9eafen5wfmc2v8ektj4yz6qlk9dm89q5xzy9vvyscc3vlrmwzfkt09eq9h3npzxr92ths4fn3zct5x9yrv5k87st3s3pqft52qplqtjlzgkpq4pp967mvtxejnnjnsf6y9yqfavh9xqgjehk0pl8sxf8z3pr3kf90esvw6fc9y8j52qnxyrrtfwk8rjj686nfp7matvx7w8cyewnz466wdl2k6l97zpe43s8t0rf32qufadeh96jz427ajnx02xzwaamvsqy65ppwpc639j244kxcpqqej9scfz5k3znxmeprr4rpdnevl6sktult2geu7psahqtpyau0pztpjlvap4zvpxdj0tqa9763pq7c626qcrs69yjyzd48pw670m7fmzh2a3kjger7xuhz6l8se2zqtsxz2e9vlshjjh3n6fz4xzpwqtcrt8f5jnnt8nqk7hj236d7rt5dzxt8sujy025uexsuqtdgfwm8v2j8fh90whg9kxhpswctytua5kete82c90jevuqytaxlqtped4kuu4wzsawnkhw3000xzp9uvtrxwerddlvzknzz3lueydzkzfg8qswae65e8lefj8feywjp9el06r3murqlzd27lm70z289re5zp3ftxsy2fmp0rnvuu2h04qywtgwp0s9w0tqzy8l7jz88mn34qgjglhrpj6tp2l02467twzx3jnt9204pvfwy7rxyucqvajxe5hddf8vlxlfza262fux4ggpfqh59zyjl8jm9vx064nhhcv52d39gtyntg9vsxx0gzamzzruyqf8mhed9l2hgzvgvnmzrjt856phzmuymy9edafdxx27st3ehjncz2u39h3jgars8y98p9pmqjpcajuryc6pgul2qznyxdp79jcnt4cwfzxkuyphc2n5krhd0628lzhs8d2y4et3579sfc65y0kf6u7rve8wf4yswuh74jqrhfue0rgg2qhcpxvt9mexnac0fm8f5w5g4fy92hheyqvens9xpc9t0vz3sqcjamkp2ewtvqg4dhnwxapzv2zvervr8rfzmvzau6r27q8dg6rj74az6grle535tlq0s7xyylxud3xn5znfdxf0ju3jhyxxe7zy9yxdp9zp6v2e26zydsdymk5cgppt0qegkk995l6vjxt9f7t4wrch7vd3ljxu3wkyvppg29zw4ee29fqqwm84p5edjpn4fnqm3fsr5nhnnz6ft29e020chr0v7s64ppeyl36nu63zq8lc0f7ly0jx4495vv49ayqxypmzxadnd66xmxwxs7vwlczdkmtetymgkws09rtzkg903g4qpyn3nr6uk8ch69ksr5kc268e5r3dwnnw9uupgch34n2sn85hc3xt3ggys5x8sqmr3u3gllg0y3yq5fg0pmkrvafr8qfwtdve55gdlaavdqeqq2fq04sznlnpa3xctc7rtj5gc54sugwjn5gzr6jcczu95ynpeefsd0r7ngkq3r7vhupsk7uu57dqv4x2fme
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-09-22T18:18:37Z"
  mac: ENC[AES256_GCM,data:C6GERmwxcoiJR238zlWIj/2oZ8Uyo6S+kS04tXLET8iJlLBNBBNrZ6ENte9t9eI3kZnDAQaJB+dUg3AtvDPOJsHIbX2PbvLt0bl3tJ3uxA2l8gVBcJXEi3og6ZcCmp+PSgQ8dTfw6dMtYm1gQOICwmprGbo8gLfH7vd61Q+YIoU=,iv:OywPMQWFAGZ/GVM9mLTKtM7gw8AmhAVyCDLP+vS5iyM=,tag:1VxZ86mQpMsY2jfPjMxgag==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
