# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Yj80wnuS1ZrzOd95HMlkBLzyrQrnTrJ901R27ze6FrGRMtN7GVEVaiM4kNfx2N6Rsl6++Wv6Kf6679O4YjLZLV7zUEA0OgYst1tM1S3AiiLy0ssW8ZPIN8oqxJdUW8q9UeJeHP4g5c9rWtSTjPN8pKJNpj+kPdn7iNwJnw72xTIasR3WZgUWzVpONKF6zQgQyI6TJbHVHp/OEqAeQ1MYSCYMxzUzsa0fCeFewImgY5X+fz7a,iv:ep+ZMtu3RTkFyoh36MuCM0xl7/OFPlE7LPDEMnyDjtQ=,tag:AXikCwjswMVFR/0bBPP/1w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHNiTTFVbmFy
        cGMvMitWMHN4QWVjL0U4aUFKTXlWZExWcURvclRsQjRaZVRsbHVjYndIeUpPZTQ3
        MVVXakNHMHJlVnpKbWY0UVJ6V1BYTHI0blMzOHI5aXNKcFovVm5aMi8xV2NQa3FC
        UUlSaEJYTjFoakl4c2FjclRxWnpyaUlXYmErcHh5SlZGcm1UbEc4N3o3THEyM0Vi
        OEJMbjlKRUZQY3BGTFM1QjBiakFqKy9pSW5RaTk0VzZweVhyRzF3cHREbldhU0M5
        RHhiWWpIMEp0WWlBNE5rclpEM0VvVmNGTjJGdWRLQWMzaXhueWJZYW0zLzk0Y25m
        eklHeWZlekZWUFdHL0RCVTNpT2lFUW1MaGh5ZHhVMUE5RjFIdWwrYjVqbzdvRERi
        TVQwQk96RUdtTHk2M3NwYWVYWmtoUURITXpoU0hQVDJLZEtYMlYwaUZTYXdmVVgy
        b0wzekhuZTVTOHh1U3VMODdFM1paRmhOTTlGQ3lRVVZOcUg0WkdvcHJ6TUpSR2lm
        dWVWZ0hMT3BacnhZMGxNWEwvdFZNTWFZMk96M0pDbGZKYTB5cGE1aDFLQ285ajBa
        eHhEaElpeWI1cG9OQ2tZbmFyVVorMUtobXc2RENna0tmTzJ0TFBGMHlNcnlWWmVy
        RXlCUGsxenQxaldVSXRoVE5jUjNYUmZLcFl6Rjc2T3J0MGVWUVZXaVVIWjhraEZ1
        SFlzZ1AvbWJmSXFhbitRSWJGZ0pBWWlCdklyR0MwZFBQQktXL2hhVDArN3FzdkJz
        UmpFRmxORE91S09ZYUZ6ZEJ2akxBMkt3N21vRk9BWjBROStNYnpmMWZqckNMSFl5
        U3NMbUJ0WGN3bGZ5d1RkYjZUWDJ0ZmljL01kZ3BqaU9vaU1HSUIvSmxCdVVTV0JB
        ZDZVWXpMK0wwN2FkbkozdGpsMXgwTDRURDNZMU1VYVNobVdDQ2pFcnJtWjFtWDJo
        bEhDR1UrS1lnckVMSDliaVhmMCtHNVNsQXRBaDlWZWtETUNCa3pQZGhvaXl4a0lM
        S0cxUGdGVmJqUHhYdEJYZFYySk12Z3BkVlZ2ZzZyMEsrN214ZURxc0VGUzdHWlk3
        RG03REQ2Uit1UEFoUlR3aWo4Nm1NUFdrY1JaMjhNQmVQWit2L2Vsd1JiNHA5UEFG
        N1hyMDdZcm9kazl0dUdGaC9qenp1RG1BaTdCUFVIcDBHVzd3U2RPTU9pNmxXVXdv
        TnhjalhDN0c0YWxiZjVCYWFKbGR6eDRiOFN2YnV2b0tyZDZzWGR0aFZPaVVBOUFI
        bTNZdVVsR1YxSy84SEdlMm5GQ1BQWmlKc1BnaGluVFdzQk1vUVhJbnB3NWlKUFdt
        NytYVXBkMFloSmlDMURXb3NrcDVmRzJ5ZDhtK1hTR0NHcDhJWi9peU9uVHo5Y1I3
        dlg1M3A5akEwVnY3VS9TSWxUL0toVHVtTng2UnpheTFHVlVoVVFCYmJ2cEQyUllZ
        M2ZickhkRStYdkh0cis5VnpudkptT05zTlJHbDI2TkhrdExTejJValoxaDFLQkI3
        c2xmYTdSSEN1NUxRNVhodTU4SFRqc0c5WWdjYTViUk9Jd0VONENVZWl0bmc5Y2Zl
        YTRTaHV1YXdOYU01VlVRTFhONjFMSXhPUTlwZWlSWDcwbHdyTmlSczhKaG1uTEc3
        S1ZDQ0p6bTk1TU40dU9NemVRVEtuOXptQ1lKOW4vcnhWNTltQW5heUdTalpFUERw
        T201N0FiZ29nVExaUHIvRll0TnNRMG1Kam11bEZ0TzF3RExaZU0vdTBsZTJidGlm
        R2FraEVpWHMyUHhxZ1FkTWpnS0dXcFhvWEpDd1JIVWVDMS8rZUJkZ21mOEVyWUI4
        dDlsUU8vMVB0ZGhFaHcrVU1nZUtEOXhYU2tlUjZzMTVqSGlGczZYM0NoUnNGVEtk
        QWlkdnRGZjkybWtrUlArVWtKc0lLdVRpd1BSYUdvU0wvSENDcEc1S3Ezb0tMdwpE
        a2VhaFNkSGsrUmJJbnQ2cmtiNjNZRk5VV0Q2dVpPQlhIaUR3dlNadFp3Ci0tLSBI
        UEUxL2dYZitCVzZ0K1htdFlTbkJ3YitST3JjNkYvc0lvLzVGSkt6ZXFBCiurK1LS
        sZYlBA5Wv+9ZSS5QC6Yct4pcY3ckQMNNTdrAioMhdiQTLJgJlIIFuAnnl4WJ4E+D
        DcNCOzbIUYpzNeE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq17jrq9vucnth9v4e4gx5zvpsr6szqlcnp9mwt0rmyfyzeww97dyejlxsuvgnu4spgqgzwp9ms0dvrz4gtvc9lw6sxnjywpkq773nptcfqgvccxf6tnfq24eq4prfez8azp7k739mdcdmfx3plew9nl58e8vzwppgegzsmm4y477ycgnqcn2vpknyr3x7zm3eqd6yjrfeygt6582fp4fxpzjp5qdm3g6ncydqpq9g47p77p7cervten3snr0tr2zcptxurpfjgx6p2ux0up8a88qx8m0q6q2yreusmwe862h7rjshm8yyzmse5xsc9ydnkdjt3kz2au3lwqujsz0wy44yvvae99xxtcxejh96vjj5gcej9vwkkzq6k329lexv4qqv9rrz89r5v4qn3vd0sq3c8n8ve84gfdx75rse0xdthm9eafen5wfmc2v8ektj4yz6qlk9dm89q5xzy9vvyscc3vlrmwzfkt09eq9h3npzxr92ths4fn3zct5x9yrv5k87st3s3pqft52qplqtjlzgkpq4pp967mvtxejnnjnsf6y9yqfavh9xqgjehk0pl8sxf8z3pr3kf90esvw6fc9y8j52qnxyrrtfwk8rjj686nfp7matvx7w8cyewnz466wdl2k6l97zpe43s8t0rf32qufadeh96jz427ajnx02xzwaamvsqy65ppwpc639j244kxcpqqej9scfz5k3znxmeprr4rpdnevl6sktult2geu7psahqtpyau0pztpjlvap4zvpxdj0tqa9763pq7c626qcrs69yjyzd48pw670m7fmzh2a3kjger7xuhz6l8se2zqtsxz2e9vlshjjh3n6fz4xzpwqtcrt8f5jnnt8nqk7hj236d7rt5dzxt8sujy025uexsuqtdgfwm8v2j8fh90whg9kxhpswctytua5kete82c90jevuqytaxlqtped4kuu4wzsawnkhw3000xzp9uvtrxwerddlvzknzz3lueydzkzfg8qswae65e8lefj8feywjp9el06r3murqlzd27lm70z289re5zp3ftxsy2fmp0rnvuu2h04qywtgwp0s9w0tqzy8l7jz88mn34qgjglhrpj6tp2l02467twzx3jnt9204pvfwy7rxyucqvajxe5hddf8vlxlfza262fux4ggpfqh59zyjl8jm9vx064nhhcv52d39gtyntg9vsxx0gzamzzruyqf8mhed9l2hgzvgvnmzrjt856phzmuymy9edafdxx27st3ehjncz2u39h3jgars8y98p9pmqjpcajuryc6pgul2qznyxdp79jcnt4cwfzxkuyphc2n5krhd0628lzhs8d2y4et3579sfc65y0kf6u7rve8wf4yswuh74jqrhfue0rgg2qhcpxvt9mexnac0fm8f5w5g4fy92hheyqvens9xpc9t0vz3sqcjamkp2ewtvqg4dhnwxapzv2zvervr8rfzmvzau6r27q8dg6rj74az6grle535tlq0s7xyylxud3xn5znfdxf0ju3jhyxxe7zy9yxdp9zp6v2e26zydsdymk5cgppt0qegkk995l6vjxt9f7t4wrch7vd3ljxu3wkyvppg29zw4ee29fqqwm84p5edjpn4fnqm3fsr5nhnnz6ft29e020chr0v7s64ppeyl36nu63zq8lc0f7ly0jx4495vv49ayqxypmzxadnd66xmxwxs7vwlczdkmtetymgkws09rtzkg903g4qpyn3nr6uk8ch69ksr5kc268e5r3dwnnw9uupgch34n2sn85hc3xt3ggys5x8sqmr3u3gllg0y3yq5fg0pmkrvafr8qfwtdve55gdlaavdqeqq2fq04sznlnpa3xctc7rtj5gc54sugwjn5gzr6jcczu95ynpeefsd0r7ngkq3r7vhupsk7uu57dqv4x2fme
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-09-22T18:18:37Z"
  mac: ENC[AES256_GCM,data:C6GERmwxcoiJR238zlWIj/2oZ8Uyo6S+kS04tXLET8iJlLBNBBNrZ6ENte9t9eI3kZnDAQaJB+dUg3AtvDPOJsHIbX2PbvLt0bl3tJ3uxA2l8gVBcJXEi3og6ZcCmp+PSgQ8dTfw6dMtYm1gQOICwmprGbo8gLfH7vd61Q+YIoU=,iv:OywPMQWFAGZ/GVM9mLTKtM7gw8AmhAVyCDLP+vS5iyM=,tag:1VxZ86mQpMsY2jfPjMxgag==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
