# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Yj80wnuS1ZrzOd95HMlkBLzyrQrnTrJ901R27ze6FrGRMtN7GVEVaiM4kNfx2N6Rsl6++Wv6Kf6679O4YjLZLV7zUEA0OgYst1tM1S3AiiLy0ssW8ZPIN8oqxJdUW8q9UeJeHP4g5c9rWtSTjPN8pKJNpj+kPdn7iNwJnw72xTIasR3WZgUWzVpONKF6zQgQyI6TJbHVHp/OEqAeQ1MYSCYMxzUzsa0fCeFewImgY5X+fz7a,iv:ep+ZMtu3RTkFyoh36MuCM0xl7/OFPlE7LPDEMnyDjtQ=,tag:AXikCwjswMVFR/0bBPP/1w==,type:str]
sops:
  age:
    - recipient: age1yum2rd54mjqlzzpklr209h8qukjngtj5pnn74ugwntzkl6d9fvfqrrzmns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdzBFRm5IUnc1V0dkWmtk
        eXJqQ3ErQzl4dnJpRnJwVEM4a1p4bG1jMldrCmxnc0hxNFRPRTlnbTEzYTk1emww
        REw1T2RiUGJ4WVJRV0RnZlE4bkpuT3cKLS0tIFV1cWlGbEMzQkttMUhnUnVNSUcw
        QzBkN2Ixa3VDK290alh5TmwrZkVEQ28KWbV+PQkoKaqTt7WtyG/W5eTx3bUs7Zfn
        5yj0/GU66vpmXBv3Q9JtnxC3AzEruXx3BvS5157fD5cCIA4VZ04kKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-22T18:18:37Z"
  mac: ENC[AES256_GCM,data:C6GERmwxcoiJR238zlWIj/2oZ8Uyo6S+kS04tXLET8iJlLBNBBNrZ6ENte9t9eI3kZnDAQaJB+dUg3AtvDPOJsHIbX2PbvLt0bl3tJ3uxA2l8gVBcJXEi3og6ZcCmp+PSgQ8dTfw6dMtYm1gQOICwmprGbo8gLfH7vd61Q+YIoU=,iv:OywPMQWFAGZ/GVM9mLTKtM7gw8AmhAVyCDLP+vS5iyM=,tag:1VxZ86mQpMsY2jfPjMxgag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
