---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app headlamp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: headlamp-secret
    template:
      data:
        OIDC_CLIENT_ID: "{{ .HEADLAMP_OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .HEADLAMP_OIDC_CLIENT_SECRET }}"
        OIDC_ISSUER_URL: "{{ .HEADLAMP_OIDC_ISSUER_URL }}"
  dataFrom:
    - extract:
        key: *app
