---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: headlamp
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.42.0
    # digest: REPLACE WHEN FLUX-LOCAL #1101 IS RESOLVED
    # digest: sha256:ea8e0fa063f3d2d196ecc7d162026617b12f873a7b9176dd81ade42e94381c4a
  url: oci://ghcr.io/home-operations/charts-mirror/headlamp
