---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kometa
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    #- ../../../../components/defaults
    #- ../../../../components/gatus/guarded
    #- ../../../../components/nfs-scaler
    - ../../../../components/volsync
  dependsOn:
    - name: longhorn
      namespace: storage
  interval: 1h
  path: ./kubernetes/apps/default/kometa/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 6Gi
      VOLSYNC_SCHEDULE: 0 19 * * *  # Cron in UTC (CST: -6, CST: -5) OVERRIDE: Daily at 01:00 pm or 02:00 pm
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
