# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:JtzDU18RsGTnnjjjEcLdS1U4JNGCsVnmh3OmqzdQXDXKoq772u74mg==,iv:7+U10FlSodovPhpMstP8sg7an3S6ZXRCG8YihV67t6U=,tag:isLAop9vXbcZPlH/8QrogQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IERid3BMZ1F4
        aldnVHRXYjN4eDdSVGxXY3V6N1hsUEViWm5IMDZSRXd2TUZVZU1VMk00Zm9SVDlH
        LzdFZzh2MjR5bzBxQ2p0N2RCaUlheXFFYnZGdG8rQUJVbStySCtXRm02ZzUxcnJR
        Q2ZDejFGUm5VNzM2RDkwMlF6T2o5ZGlzZkxBUHNWS2FERUkxWm1xbStTazl6OXZB
        bGFqek1RWWtuQlhlV1F0SDJpbXFkbC9GMlBGQS9FcTBhT3VOUkVnYTlGZitVMGhu
        L2pXS2s4cnU2ZFhPdEV3dXVrOEZrQUxTK3YyWnF6WENpd2U3YXlSSnNHY1ZVQ1VX
        QU13MUx2VzFtSUpmb2lxVjBWOTVCcGFOaHJ6emxXSHhIVWdHandnVG1pV3ZKaWUr
        eitYeFpLbzJJTDZrMEJkNHFVYmdOaU1IbXBEYkFtSHczWG0weTF4V3ZjTDFVTzRq
        dzdXbUxEQjdFMnptZW5PdFJvSzVBSFpFcVNsTkRKelNXWTk0OW9BaE9ZYzBPMkZu
        OWlaUHJZYzRqbldvMkFxQUZVUHBzS3VvREMrVktuQTVJTE8zMXVJM1E1RDVhOUwx
        dTAxL2dodEZoZ1l5c0xJdndqNGh4cVJnY21nNU5XYWRTRzF5bFpNQ20xcE5GaW83
        dHlXQnM4UVJFOTIrOGN6bzR0OTRIV2xFZWNlZnVKSkVGRXk5OEoxSHJ3TW5SSlVH
        RWlSMUtxZ0dBRndiY05iMXBZbWlmOGpHNXNuQW15VjVWeTBNR004NE9vN2dObFJm
        SGorN0lVYXc1THhzL3JIeE9XckIwbE1aUzA2aG1vb1c3MFBXR3dlRE5sWUoyQlVl
        cGR4RWRhTFlYeEJqKzUxVC9kb25zSCs0Tm0zdkxvZXg5WHp3Z1JwK1lUTitNcW9s
        ejMzY2pxdEM0eW9xR3lvRVEyQVZia21iQmh1aUxkLzNJNG8wcmxmOXR1N0Q5UmFG
        anplbSt1MjhSVE1wMDF4bHREK1VEdFhrUEVXZlhrMDVQK3RaWmVsemM0YmtZZ0Mr
        bzZkTXd2QTM0RVIyZngvT0RZRC9iWTREYTI3L2pMSnVXbFlYSWZqUk9iOFAwS1Zl
        V0hJRnA4QUlHdnc3eUl0cWkrTm1MTGJQS0dsbXFoOURMWXg2TlNzWWJNNWFkYWRH
        RWd0LzNKZ0U3STNla3MvbTY1eDRrTWdnL3lrczBOWWRtYjZ1ZkJyVXp3YWJ3WS9R
        QVlWakU2S0RPbWZZSVQwbmlvMGhqQWwrUXhtc2kzUXA0c3Q2cXNROVRzZXM2cmVp
        NGRmL3ZwT1N1UVd2bGNHc1BLSzlXdTdFcVFlMW14QnZPS3ZaOFlGRFdyaCtJcHlX
        NjJDaFFEeE1xUEJRRDh5NkhLQzQ4VVBLYWdMVVZpY2FpS3RqK2lkSTcwSDhIZWhL
        Q2ZmSlVkaTQ2UnlCQnBIbmpHK0hOOExEUmhmVlloc2pnWjMyM2txdGo1L2hXTmUr
        RmFaVG9jSnVXQ0V3K2JCRHo1L1MxU1hDMkNxZEFsY1JLZmtva1J5WitxT3k5K1dx
        bzh6KzI4bU9NTTllVmdlelBCY0RBODEzaHphQy9DcW90VHhCNlhISThKQWtPYUlV
        Ky9SMVc2WXZqZzlaNHRwVncxQ1lnWGt3alZkdlNmTDdIUlVtNi8rTU9pSXlGeEJj
        WDJveTByUG8yM2VJbXlkZng1UXQ1K1ZXL1Z5N0NobFQzb0dYbURKOTBqOHpJdTJt
        NUgrbDM2d0k2N0hlbGVzZkFDb1R2bUtQQndrMWJCQkRIdDhxcnkxVGM4QW1QYVoz
        MTBxQ0NXdkZnTXhOb2dyYlJwMC9XMHJBV0JneTJTK09NeU9KTk96SmpsTVBBSWxF
        M2ROY0owSEpsTTVHWndXa0lHR1pEaEFrN0JoUVRnYTE5S29GcWl3Nis0THRjTi84
        WE9zbkRKMVZMWGFrY2Q0R25tSE53QURRcTJjTE05bWw1Q041MEU2dFFZeE1FQQpo
        ajU5WUZUTjgxcEtsSVh2V2dYYy9ZTHpLc2JUVjMzL1JaV1NwVG5NVzRZCi0tLSB6
        eGY3NkwyMW1NRnJkMTNadVhaSkEzVnZndHBBVmlXQnpTZVZxNmcxL3NjCvkeus4g
        IqPSLWhxUY+ClcmINU5XXpXNyVhWWBFV2lBYGuJRHJm6NY0My7EMfiGUw5RURHAl
        cGuK+4RnCru7EWA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1z3jcsx8evc570sfle3awhzqpnwf87dt3rknwq6s9kwwknd2ymct3xajqd0jm2yqely8eqdjnd9r6asv5k405v0hk3zxleenpeyakz6m5nl9ennu4nqerz5duzq6xurtmv0pd5zqz2wd7uy9apaeec8zf8t8mdjs65cvamx9gpae9uz0kf45lez0wwd42d0qnzlskqjsyc2vmptwtx6xj3amxksyjs45grvjmjaqg7j58ed45g9x88hafqmphx30hrwk9alq73eu3gadzjhy4qg4rwf5xwpwvpvkxjqkzyws3kstmwfav7r9rmuenj2xhwfgwkgeyj5ezytyrylv2mdnny7tg27r9sxg6jvctvs9uctv4eg9dyznfnj679zqz52sztpu84raye0p9d9aadr9cj3j2zpkezttdgzgmljc87d58szj65ydpnr4uc8a6s7edj2puy8x8qydyh7yl0ngdjey0z2v736s527sy5mr0ydgag0p5t3dzrajjsl7jrx9lf3t3nwaguysc9568uryf9sjfj4dpcrps2eyhvdj9rj8uc0eqh3fsscc4pkx0jfcc0wm5j72a33ffwr8yxwmqdrgyemfvcy87vl3mw5fmnz520ddp8fzq8pw2k70e8dmqakkwwkyqlcf23cwgxsvlku42n7zhx5ssd0g2zj0mja5e2cgfjdkpmdy8u08prg878y73vzgs52cpw9y8suunhcefcrccldwewwptaw4n6hrqeaqcz848yesmhym2d2nnzkt4sw9tsjd3pz9tq2teqxq37xncqfuetntcfzauevmjftezravjc03vc05d6jtl9l9lpp5cyswnzgqhxh55l9s4q6nyauevfyg8wrwsk5prlsuzkk2s6zzqyduq5z6lghzsjc9nggvw4lsek65ggayzwx4h0whd87vf96qhmltr4hupt35ughrmhpy7f93rqcvn93jy3t087ammgzv58yeq9m8ejxmxggdn2w48fyjjy4wqtsqun5z6wfrd2z2ej89r6ca9tng6nk5qq8295hye7mrqfmjsx6mevh720gcamjseszs7s7uvkw5zs9ngg90tlsev2qm73rtkpmrct825kquwqdp85utcrfaeerc83qe6k34dccn0j9ntqj7tkyyf8xpl5zgymylvn2d6ksprue8eqf845wdvkpfg8m9jgd4ftqqepqr0vtn3j26ntzgn9h382chnw3snkhvn5mz2wgz2nayslsfv0q8m254thzw4yax8l93z6475dv5efpywv9p9zu6273azs84u5qpnxgactdcekvzuengh8xyreqpxwmsmuca25w9e9rque9ytvufg3p4ngkg74zmrssn5ykmzxgfekp6qwglwpztnjpfps4ueykr78g7cx4srk72ansxxu92ev3agk6lczf6leuk0gep63zs2rtl9ja3uwjvs0c2y97qss3yngpl9rph5z6tz8quxdef8v598sqkxccyu5zw5cyj8sw24q92gwxpjqqc5hwmwree040yrsekx9kycyfyhxsu23jyhfj9jy2yvsle4frpqcerupgwfa8rgpuggzdqvzd34xkwajxzheqt9xxlfw7hd82w5kvp7txty7f2nxxmhqsvzvmxxawnc9659wc94zy6u4c0r8fzd7hzw9krfmktcsfxvjdesx3ym6l9us648f2uqcu9jw7xteft7tptglfsmfafqk523gyrxttmhcddsf5mupzs5nvtk0eqf3nfs4slzhay9dzzrcmyzxd0srzcrqew7f3gl5t9ycnc4sh0yj679dpzd846epwmcwy7exynzc0jqveq53udqhj5d0zxvzfepcpxe0ars97krgngssyvkw2hec0vswsj3q20g8xl5syte9ez3cl2sh5uvaw7080s9kj573lyvwcklu8fvtzwhzq2am6ar
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-09-22T18:18:37Z"
  mac: ENC[AES256_GCM,data:BJDl5gtmAc0ngX4tzDW0NO+wRusRanv+S5XogVY9PD8GG1JG71/MbOr/22rmudsjoBR+GnqZ0q0fic+bXyBu0t4pDLPcjxDvdBmcIngPruq6IQO/zGjZqp61tRINm/2R87ZK+R1ycheiInOKwrRDRlXWQWtL+7TXUIOch74WdjQ=,iv:NYZ7gHvsbAjNgyuLf1mQjmN5cEatea+L7T3L3Ivol0E=,tag:HEHvczT3Ir6H4lMFufQhmQ==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
