# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:JtzDU18RsGTnnjjjEcLdS1U4JNGCsVnmh3OmqzdQXDXKoq772u74mg==,iv:7+U10FlSodovPhpMstP8sg7an3S6ZXRCG8YihV67t6U=,tag:isLAop9vXbcZPlH/8QrogQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHAxdTZoSjJT
        aEJldEZwWjFZeVAyZTFOZ2loLzR2b3lhZC9kNW5OZFN2eTZwVVhNQlEvSlcwVkda
        ZXpYcjhhVnE4SGhyem10eWhOOFdxb1duYlUwY2VkQXZCbEdhT0E4SW8vOVd1ZjJa
        am1qN3lOU3U3SlV2NHNZbkVITnlHMzJKV280WkZjam5lK2VyUm05dElIV0Fnb0Fu
        MjhuT1RidDRJMFRNMWMzYWxicG0rR3ZCc3lrUUlzZWdjajdFUFV2RUZ4OWZQblU2
        ZGpOSjFYQ25Ba0E5aDdsSkZKUWxXOTlGWm44amVyU0VPTThhL0h4a0kzYU9vNWRo
        UGx5N0VLTlErRnh0dmJlZG5CS0R2UWdvbk5zdjdKdzVhSUt3TXU1TFF1NFBrV1Fy
        ejZ2RHRZNTJpZThOUXE1bUNqSmNXV0FPYWFUZWRadGppVjgrL2VEL3VvWHFHeG1s
        K005RHRjZDV2bThqVW5IYmFYRHBHTHNJZXp4MFZrRmcyRytpaEU4MTVIbUtjZHJY
        ckwrRFV3UWszOHB6WTlHRDVuTE43dTF0MDJJTWtLa1FwM01qLzFmR3VpQnFiK0ps
        cWtDWWt1M0hSQis4NVRnRnFiVHZUUWg2dlQvanBlWDB3bWRpOXFrbUU3VUFwL0Ix
        NWpjMWJON2ZYRjlBSU1aUGhxS3o0bTVCOGZOdTlaMENvWFNNVUZiZVRpWHpaUFVr
        NE1TNVZrUGxXbUhQVkxnNmJoZ0pucmVNM0VOY0xOTG5GaGptL3czK3RDQ1NOakUy
        RUo5d0N5VU5xc3BlNkFFUHRRa2N5TUJuN2pOckJxaWgxNng1d0dtaEl2dm1DbzhF
        UkkzdXlybndraWt1eUVuYUcrSjhtQ05BSGFoUk1UZFZjbFV3Qk40dVJKYU42WlhK
        VHJmdW1mT3ZTaFlQVVJ5NEYvZDMyWUJYWUVQcU1FVWpocXBucEV2UHhJWnlvb3Ft
        M0lja0w2ZFdIRzhMcUQ3d1hJejg3NjN5cWhNaTE5TndEb0lTZXhDM3cwbENNYTE0
        d2NCUHN6Z1ZiUGJpbWphRVQrQUdJZG5VOTRxUGVPOFQ3MUJIU1hNTzdYZTJUaDFW
        MjJhV0FYUTF4c0tzZWNmYWNPRkwrckFBNE9GNG5yMWJWV0t2ekxxdCs3dGpTRkcy
        emExNXgwRDh2VVRqQlJpWkpib2R4WXJQS2JUTmdPTEVWN1FCd0U1ZDNuZzBKNGZT
        VFA3NVZzZXFhaEQzc01oeWM4RmNtRzRjY0RRUFN0RXdsTm9ZZW92RnZ5OHZRSlpy
        TDJiL0NaTFpMQWFFRC9ZaGFRU3RnSzNoZUFSVGNlOVJRT3l2TTBVajFQU25KaG5Q
        S0lONTJadUhycEFGVktpcHR1MitOUDdRRTV3NmVxaHhzY09sMnlodm9qLzR1b2F5
        VlMyZ3d2bFQxS2NTbXMxT0RQLzVIL3BiSUJhOHA3T3VUdnRXUjlRb1pqQitLaW5m
        cEJIazlQYllDN2VEdGNlOXBPbmZYZkNvYTUxTExjT0NJRE9tN1oySVA4elBsR2JS
        RHZtWDFQV0xZc0ovbURoaDlsS2FhaHlNTjRmR0taYVRCRFczMU9LS3RMVk9JWEZI
        K3ZBNEpPV1BRdDMzR3ZBYTlyNTczYzk1V2swVDh5dGdSQ2w2Tkc0YXcvSUdPUThQ
        ZlFZeUliWm1iR0VSSGZ6SzQwU3A3V0o0Z0ZvdFhRSFNKT0dqUzdBR1g3eFVxZkNs
        UlNGTEhVNW1NNmNxL0dNUmRXRUZRTlVJQk9HMUNGdkIrSW5CUlNqd2RSVzJTVVdi
        MVNCMFYvYnNKRFB5Y2Z6S3JmRUkyaTlYa1VsbENjSkNBR0JxU05kdjBPY3dFeXZ3
        YlVrNjRYNkNzYS9kMHlXN013NEc5bDRVakdJTFYwbGdtdFRZNVBybzAxcDBETi9v
        bXdEenJ4aVdDaFc2NzNlU3pxbkxCRENKZU5Wd1FQdVB1VVNyemd3QW1vSU1IdwpH
        cmRFY3lyR20rRjdneVZnNm1LMUFFN0pqTmlxaGtRRlcvUGFHbHdqQUVjCi0tLSBX
        Q0ZWZEU1bGo5R3lSRTAzUmlPemJqaWtmZUozRm9rcE5wWmJyYWtlb0ljCqlf5WV6
        JYAzehN6a0OMGtBZH50oQRFrLfN0ZyC+QBKdsHq6sV9kBeIAThWaSC/8j4n6lfBT
        lzQrnRw49Cg6Vi8=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq17jrq9vucnth9v4e4gx5zvpsr6szqlcnp9mwt0rmyfyzeww97dyejlxsuvgnu4spgqgzwp9ms0dvrz4gtvc9lw6sxnjywpkq773nptcfqgvccxf6tnfq24eq4prfez8azp7k739mdcdmfx3plew9nl58e8vzwppgegzsmm4y477ycgnqcn2vpknyr3x7zm3eqd6yjrfeygt6582fp4fxpzjp5qdm3g6ncydqpq9g47p77p7cervten3snr0tr2zcptxurpfjgx6p2ux0up8a88qx8m0q6q2yreusmwe862h7rjshm8yyzmse5xsc9ydnkdjt3kz2au3lwqujsz0wy44yvvae99xxtcxejh96vjj5gcej9vwkkzq6k329lexv4qqv9rrz89r5v4qn3vd0sq3c8n8ve84gfdx75rse0xdthm9eafen5wfmc2v8ektj4yz6qlk9dm89q5xzy9vvyscc3vlrmwzfkt09eq9h3npzxr92ths4fn3zct5x9yrv5k87st3s3pqft52qplqtjlzgkpq4pp967mvtxejnnjnsf6y9yqfavh9xqgjehk0pl8sxf8z3pr3kf90esvw6fc9y8j52qnxyrrtfwk8rjj686nfp7matvx7w8cyewnz466wdl2k6l97zpe43s8t0rf32qufadeh96jz427ajnx02xzwaamvsqy65ppwpc639j244kxcpqqej9scfz5k3znxmeprr4rpdnevl6sktult2geu7psahqtpyau0pztpjlvap4zvpxdj0tqa9763pq7c626qcrs69yjyzd48pw670m7fmzh2a3kjger7xuhz6l8se2zqtsxz2e9vlshjjh3n6fz4xzpwqtcrt8f5jnnt8nqk7hj236d7rt5dzxt8sujy025uexsuqtdgfwm8v2j8fh90whg9kxhpswctytua5kete82c90jevuqytaxlqtped4kuu4wzsawnkhw3000xzp9uvtrxwerddlvzknzz3lueydzkzfg8qswae65e8lefj8feywjp9el06r3murqlzd27lm70z289re5zp3ftxsy2fmp0rnvuu2h04qywtgwp0s9w0tqzy8l7jz88mn34qgjglhrpj6tp2l02467twzx3jnt9204pvfwy7rxyucqvajxe5hddf8vlxlfza262fux4ggpfqh59zyjl8jm9vx064nhhcv52d39gtyntg9vsxx0gzamzzruyqf8mhed9l2hgzvgvnmzrjt856phzmuymy9edafdxx27st3ehjncz2u39h3jgars8y98p9pmqjpcajuryc6pgul2qznyxdp79jcnt4cwfzxkuyphc2n5krhd0628lzhs8d2y4et3579sfc65y0kf6u7rve8wf4yswuh74jqrhfue0rgg2qhcpxvt9mexnac0fm8f5w5g4fy92hheyqvens9xpc9t0vz3sqcjamkp2ewtvqg4dhnwxapzv2zvervr8rfzmvzau6r27q8dg6rj74az6grle535tlq0s7xyylxud3xn5znfdxf0ju3jhyxxe7zy9yxdp9zp6v2e26zydsdymk5cgppt0qegkk995l6vjxt9f7t4wrch7vd3ljxu3wkyvppg29zw4ee29fqqwm84p5edjpn4fnqm3fsr5nhnnz6ft29e020chr0v7s64ppeyl36nu63zq8lc0f7ly0jx4495vv49ayqxypmzxadnd66xmxwxs7vwlczdkmtetymgkws09rtzkg903g4qpyn3nr6uk8ch69ksr5kc268e5r3dwnnw9uupgch34n2sn85hc3xt3ggys5x8sqmr3u3gllg0y3yq5fg0pmkrvafr8qfwtdve55gdlaavdqeqq2fq04sznlnpa3xctc7rtj5gc54sugwjn5gzr6jcczu95ynpeefsd0r7ngkq3r7vhupsk7uu57dqv4x2fme
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-09-22T18:18:37Z"
  mac: ENC[AES256_GCM,data:BJDl5gtmAc0ngX4tzDW0NO+wRusRanv+S5XogVY9PD8GG1JG71/MbOr/22rmudsjoBR+GnqZ0q0fic+bXyBu0t4pDLPcjxDvdBmcIngPruq6IQO/zGjZqp61tRINm/2R87ZK+R1ycheiInOKwrRDRlXWQWtL+7TXUIOch74WdjQ=,iv:NYZ7gHvsbAjNgyuLf1mQjmN5cEatea+L7T3L3Ivol0E=,tag:HEHvczT3Ir6H4lMFufQhmQ==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
