# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:JtzDU18RsGTnnjjjEcLdS1U4JNGCsVnmh3OmqzdQXDXKoq772u74mg==,iv:7+U10FlSodovPhpMstP8sg7an3S6ZXRCG8YihV67t6U=,tag:isLAop9vXbcZPlH/8QrogQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdUlIRk4zMUxvaDRKcmxU
        QnUyMzI5NEllK1U5ejZXTU1NL05ndE9tbGw4CjNUbElXSUJueUJtTW1mMVNmc0dp
        anExWWg2R01iQ0haVW9YZmZFNGkyZHcKLS0tIHhTZ0g4cnlVUVM4MnlEaTFac0JY
        Qnkzb05LNXFQVTJwQjRvTExibFRRK0kKaTbuQVmae/UHEn/rISV3BzV1QgdPqbBm
        rvW2xx2IGyo2yA3XGP7uzSyLstJ+e7+ebiZjdK3Y31r74TB/N9n1Yw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yum2rd54mjqlzzpklr209h8qukjngtj5pnn74ugwntzkl6d9fvfqrrzmns
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGg5NE5CU29L
        TklDY1owTkY3YUVkNXRFOEtKei9HZ25UVTVZSDY3b1RlRU80TmJCeFJRTVlJRFRy
        anM3elhUQTcyZDdBOWJRRzArQzlpVTI2Z0pXWitDSFJDMUdxL2NBaXRtNUxFUHdY
        SGUrVjVuSzJPZ2JLWlllQkE1TjRJS01wb3YvaGJmYUJ6R0JYNy9MS3BxT3ArZ2c1
        ZnVVUXk0ZU1Uc1hMa3k1SVR0MUtQdnFMMkNBaG9wZmdReGh2T3M0aGxxODVqSzBq
        WnZSUjl6cVIvcHJpYmt0ZlNHSDcwMkJpcnRLMmFxMmZadHptWW1ZQmE1VC9nU1hB
        ME9IdUZ3TTk4bFRLazY2bHdWeldlUHFWbFFyYkEvOEw4TXprUXV2anNiZXRtWUpN
        RnhoWGJNZGN3TE1TSVpiRHRlak54c1pIZnJESjFjTlZ6QjFlb0ZWMmZZRmM0MXZM
        NytvS2NRS3U5cmFielMrUW9Kb2JpWS9NQVV0MUpVQi9JcjBBTHJQbFpYT3VLclo4
        UE1pdG5SUXBiYy9NK0x6Q3B2bjRER2JRZCtLR3NPam9uR2x0VDg5UmNKenR1bitM
        VXhhNnE1c2FueWc4YnY4UWQwT0hwSTZtQXAxWEl4TVhlU0M2Nlc2cEhpaUhlUlRI
        eXJxNDhtcnZnVkkwaEdZaXV6NlllU1o1dlVYY3NEN1FsZ3VZb0RZYnNMQzV6eDAv
        UHh4aGw4Q2dQblc4TFNDb21tNmpEbVFRY0JpbWxtRWo1K0lSWGlJWTZ6dFhyNFd5
        ZngzNkFTa1pCUzNHVVpzM2pQVFdpK3pha20zclBkVlRyTHVFRENXczIxWXloL3lV
        aUtmYXZkWnVUQkZwK2tMRVNSZ2JyZjVwT2NlYTRnT21RNG50MkcweFhEU3k5dXlF
        VHdWRS9iaXdEZjQvOWZzNUw2VUFWTHptQUJEZ3Z1Y3lkcEJRMWFMNmZsRW5QSjlu
        MTdvZlRsSW9KTlhML254cVloMUNTTERBSnUwZ05JRVh3T1d4dVlab3RKVEF4cEIv
        dmFDcTZhaE9kalB4OGFUY1pjNGhaRm82bnMzMHJRZmcrdVg1a0VZUHRWUUpndC9u
        a0hvWWVCQVdxQlJHUHRsZkdpK2N2WEYyU1VRVFMzN1JYc3JVSm43ayszeHFEY1M0
        c3BxZmo5dTMwb2p3UlNCdkNsM01wRUNtY2NCem8yalJiUERIeWtKbFRxYWppREZT
        TUN2OXVla1BneWZPYnpteUozam5lK1R0Z1k2d2YybUVUQ3BLUWM3QnBVYmZrSkRk
        a3VSRnVVL0tudjY4anpyT0doWWppQ1dPNlAvWXNLcDNoemlvd2V3RStia3J2c3BN
        SXY5RDVDdkc1a041M2YzcWxxak5zbklwWEtrVVNROEVycHQwZWYvd1BqNXk4clFW
        RE9kQlRjRzVQQ1hWNEQ5dER1MTdMQ01kZ1M5dS8xSkwyVnFndlhuOXFWYzRFQ1hQ
        MnNaTUpYZTRUS0lraEJ3WVNoREtZT0Q1Vk84NFUzcDhIOUUrODl4dmZ1QzhXOWN5
        N1ZMUy9pS3M5RWpzMDBaMTJzMFJoZGFFK1ZhYmNpM2VjZmNPRmUxMkkwU2ZEeCs5
        eHkwSjBWQ2g1SGVTMkY4dS9WaVpjWGRGUFFFK1c5SWFXak0xYVdUOFRpVnIwNG95
        L0k2ckd2aCtyeTFjOXVRTWFjUWF6dnZXMTZPMmg4cWUrRmJ5Y3ErY0Q4dnN4elBk
        N3VNMVdXSkpjdjNXeVRlQmJNay9NSVJMRjJqN0hYeGR4L3hBak1sUHltYnNKNHFs
        NDAydkU0d21iNjA5bmRLbWFxaXNqcmpLc1NxL0dSZ2IvQUcxb21xMG5ObzRITEVn
        dTlMODNPMGFvNkhJWFRqZ0NMbTJ6TktQYVhncUZYangybHVSWHBqVHk0M21SS2Qw
        b1d0RnBDZ0c4UnYxaFRXUWRBRmMzaU5tOEdkRDVFQWIzdktTbTVRaWhvaVBVZwpp
        ZDRQYXV4SlFaOWdyWUdOa29nY0pGQjZQaGYrbEpMRHZoYW5VR2xVK1hFCi0tLSBJ
        cVppU3RPQ3ZjWGRNbGlRRlY2ZzhjMHhTbS9HcmVNV2ZDT2FGUEZSRjdZCln8JOIv
        mz6z0YpMRwOt89nyEfiz69ouCAOq7DdOFAoRqv1ByxEE9Q9PylCMzT8/3fcWwTd6
        tcvg9siuZAujLGs=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq17jrq9vucnth9v4e4gx5zvpsr6szqlcnp9mwt0rmyfyzeww97dyejlxsuvgnu4spgqgzwp9ms0dvrz4gtvc9lw6sxnjywpkq773nptcfqgvccxf6tnfq24eq4prfez8azp7k739mdcdmfx3plew9nl58e8vzwppgegzsmm4y477ycgnqcn2vpknyr3x7zm3eqd6yjrfeygt6582fp4fxpzjp5qdm3g6ncydqpq9g47p77p7cervten3snr0tr2zcptxurpfjgx6p2ux0up8a88qx8m0q6q2yreusmwe862h7rjshm8yyzmse5xsc9ydnkdjt3kz2au3lwqujsz0wy44yvvae99xxtcxejh96vjj5gcej9vwkkzq6k329lexv4qqv9rrz89r5v4qn3vd0sq3c8n8ve84gfdx75rse0xdthm9eafen5wfmc2v8ektj4yz6qlk9dm89q5xzy9vvyscc3vlrmwzfkt09eq9h3npzxr92ths4fn3zct5x9yrv5k87st3s3pqft52qplqtjlzgkpq4pp967mvtxejnnjnsf6y9yqfavh9xqgjehk0pl8sxf8z3pr3kf90esvw6fc9y8j52qnxyrrtfwk8rjj686nfp7matvx7w8cyewnz466wdl2k6l97zpe43s8t0rf32qufadeh96jz427ajnx02xzwaamvsqy65ppwpc639j244kxcpqqej9scfz5k3znxmeprr4rpdnevl6sktult2geu7psahqtpyau0pztpjlvap4zvpxdj0tqa9763pq7c626qcrs69yjyzd48pw670m7fmzh2a3kjger7xuhz6l8se2zqtsxz2e9vlshjjh3n6fz4xzpwqtcrt8f5jnnt8nqk7hj236d7rt5dzxt8sujy025uexsuqtdgfwm8v2j8fh90whg9kxhpswctytua5kete82c90jevuqytaxlqtped4kuu4wzsawnkhw3000xzp9uvtrxwerddlvzknzz3lueydzkzfg8qswae65e8lefj8feywjp9el06r3murqlzd27lm70z289re5zp3ftxsy2fmp0rnvuu2h04qywtgwp0s9w0tqzy8l7jz88mn34qgjglhrpj6tp2l02467twzx3jnt9204pvfwy7rxyucqvajxe5hddf8vlxlfza262fux4ggpfqh59zyjl8jm9vx064nhhcv52d39gtyntg9vsxx0gzamzzruyqf8mhed9l2hgzvgvnmzrjt856phzmuymy9edafdxx27st3ehjncz2u39h3jgars8y98p9pmqjpcajuryc6pgul2qznyxdp79jcnt4cwfzxkuyphc2n5krhd0628lzhs8d2y4et3579sfc65y0kf6u7rve8wf4yswuh74jqrhfue0rgg2qhcpxvt9mexnac0fm8f5w5g4fy92hheyqvens9xpc9t0vz3sqcjamkp2ewtvqg4dhnwxapzv2zvervr8rfzmvzau6r27q8dg6rj74az6grle535tlq0s7xyylxud3xn5znfdxf0ju3jhyxxe7zy9yxdp9zp6v2e26zydsdymk5cgppt0qegkk995l6vjxt9f7t4wrch7vd3ljxu3wkyvppg29zw4ee29fqqwm84p5edjpn4fnqm3fsr5nhnnz6ft29e020chr0v7s64ppeyl36nu63zq8lc0f7ly0jx4495vv49ayqxypmzxadnd66xmxwxs7vwlczdkmtetymgkws09rtzkg903g4qpyn3nr6uk8ch69ksr5kc268e5r3dwnnw9uupgch34n2sn85hc3xt3ggys5x8sqmr3u3gllg0y3yq5fg0pmkrvafr8qfwtdve55gdlaavdqeqq2fq04sznlnpa3xctc7rtj5gc54sugwjn5gzr6jcczu95ynpeefsd0r7ngkq3r7vhupsk7uu57dqv4x2fme
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-09-22T18:18:37Z"
  mac: ENC[AES256_GCM,data:BJDl5gtmAc0ngX4tzDW0NO+wRusRanv+S5XogVY9PD8GG1JG71/MbOr/22rmudsjoBR+GnqZ0q0fic+bXyBu0t4pDLPcjxDvdBmcIngPruq6IQO/zGjZqp61tRINm/2R87ZK+R1ycheiInOKwrRDRlXWQWtL+7TXUIOch74WdjQ=,iv:NYZ7gHvsbAjNgyuLf1mQjmN5cEatea+L7T3L3Ivol0E=,tag:HEHvczT3Ir6H4lMFufQhmQ==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
