# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.20.200:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.20.200"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-01"
    ipAddress: "192.168.20.231"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    # Control Base: 903b2da78f99adef03cbbd4df6714563823f63218508800751560d3bc3557e40
    talosImageURL: factory.talos.dev/installer/903b2da78f99adef03cbbd4df6714563823f63218508800751560d3bc3557e40
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:9e:c7:a2"
        dhcp: false
        addresses:
          - "192.168.20.231/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
        vip:
          ip: "192.168.20.200"
  - hostname: "k8s-02"
    ipAddress: "192.168.20.232"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    # Control Base: 903b2da78f99adef03cbbd4df6714563823f63218508800751560d3bc3557e40
    talosImageURL: factory.talos.dev/installer/903b2da78f99adef03cbbd4df6714563823f63218508800751560d3bc3557e40
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:9e:b5:c8"
        dhcp: false
        addresses:
          - "192.168.20.232/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
        vip:
          ip: "192.168.20.200"
  - hostname: "k8s-03"
    ipAddress: "192.168.20.233"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    # Control Base: 903b2da78f99adef03cbbd4df6714563823f63218508800751560d3bc3557e40
    talosImageURL: factory.talos.dev/installer/903b2da78f99adef03cbbd4df6714563823f63218508800751560d3bc3557e40
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:9e:89:bb"
        dhcp: false
        addresses:
          - "192.168.20.233/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
        vip:
          ip: "192.168.20.200"
  - hostname: "k8s-04"
    ipAddress: "192.168.20.234"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    # Worker Base: faaee25b563caa1f0ced722895615fd8317fcd782fd3259458ded2f66e27c2c0
    talosImageURL: factory.talos.dev/installer/faaee25b563caa1f0ced722895615fd8317fcd782fd3259458ded2f66e27c2c0
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:9e:46:17"
        dhcp: false
        addresses:
          - "192.168.20.234/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
  - hostname: "k8s-05"
    ipAddress: "192.168.20.235"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    # Worker Base: faaee25b563caa1f0ced722895615fd8317fcd782fd3259458ded2f66e27c2c0
    talosImageURL: factory.talos.dev/installer/faaee25b563caa1f0ced722895615fd8317fcd782fd3259458ded2f66e27c2c0
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:9e:7e:65"
        dhcp: false
        addresses:
          - "192.168.20.235/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
  - hostname: "k8s-06"
    ipAddress: "192.168.20.236"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    # Worker GPU - Nvidia LTS Proprietary (535.247.01): 33ed8d9cbf88bf4644714b37d5f74775b5091f40b032e5ad6494f901baa1aae1
    # Worker GPU - Nvidia Production Proprietary (570.172.08): f02229dc4938048075a88a165c320b186a24ea17ceeb0045b58535ca4c3508c5
    talosImageURL: factory.talos.dev/installer/f02229dc4938048075a88a165c320b186a24ea17ceeb0045b58535ca4c3508c5
    patches:
      - "@./patches/gpu/machine-kernel.yaml"
      - "@./patches/gpu/machine-sysctls.yaml"
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:9e:e9:f1"
        dhcp: false
        addresses:
          - "192.168.20.236/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

# Worker patches
worker:
  patches:
    - "@./patches/worker/machine-labels.yaml"
