# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.20.200:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.20.200"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-01"
    ipAddress: "192.168.20.231"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    # Control Base
    talosImageURL: factory.talos.dev/installer/0d16f4518a8f8f40e51d2c64c455f4afe246b6c847b35fa540f4be0793d03be1
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:9e:c7:a2"
        dhcp: false
        addresses:
          - "192.168.20.231/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
        vip:
          ip: "192.168.20.200"
  - hostname: "k8s-02"
    ipAddress: "192.168.20.232"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    # Control Base
    talosImageURL: factory.talos.dev/installer/0d16f4518a8f8f40e51d2c64c455f4afe246b6c847b35fa540f4be0793d03be1
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:9e:b5:c8"
        dhcp: false
        addresses:
          - "192.168.20.232/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
        vip:
          ip: "192.168.20.200"
  - hostname: "k8s-03"
    ipAddress: "192.168.20.233"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    # Control Base
    talosImageURL: factory.talos.dev/installer/0d16f4518a8f8f40e51d2c64c455f4afe246b6c847b35fa540f4be0793d03be1
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:9e:89:bb"
        dhcp: false
        addresses:
          - "192.168.20.233/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
        vip:
          ip: "192.168.20.200"
  # - hostname: "k8s-04"
  #   ipAddress: "192.168.20.234"
  #   installDisk: "/dev/sda"
  #   machineSpec:
  #     secureboot: false
  #   # Worker Base
  #   talosImageURL: factory.talos.dev/installer/f9af9a87b26042e714d80c06ae619b25e81b16da5842cc64285e44e144229688
  #   controlPlane: false
  #   networkInterfaces:
  #     - deviceSelector:
  #         hardwareAddr: "00:50:56:9e:46:17"
  #       dhcp: false
  #       addresses:
  #         - "192.168.20.234/24"
  #       routes:
  #         - network: "0.0.0.0/0"
  #           gateway: "192.168.20.1"
  #       mtu: 1500
  - hostname: "k8s-05"
    ipAddress: "192.168.20.235"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    # Worker Base
    talosImageURL: factory.talos.dev/installer/f9af9a87b26042e714d80c06ae619b25e81b16da5842cc64285e44e144229688
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:9e:7e:65"
        dhcp: false
        addresses:
          - "192.168.20.235/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
  - hostname: "k8s-06"
    ipAddress: "192.168.20.236"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    # Worker GPU - Nvidia Production Proprietary (570.172.08)
    talosImageURL: factory.talos.dev/installer/8ecd8e08742f85d1181333f71fa291714e32fe51df7c0b6348703c9b34b17a3f
    patches:
      - "@./patches/gpu/machine-kernel.yaml"
      - "@./patches/gpu/machine-sysctls.yaml"
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:9e:e9:f1"
        dhcp: false
        addresses:
          - "192.168.20.236/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-logging.yaml"
  - "@./patches/global/machine-network.yaml"
  # - "@./patches/global/machine-schematic.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  # - |-
  #   machine:
  #     logging:
  #       destinations:
  #         - endpoint: "udp://127.0.0.1:12345/"
  #           format: "json_lines"
  #           extraTags:
  #             server: '{{ .Node.Hostname }}'

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

# Worker patches
worker:
  patches:
    - "@./patches/worker/machine-kubelet.yaml"
    - "@./patches/worker/machine-labels.yaml"
