---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: epg-matcharr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: epg-matcharr-secret
    template:
      data:
        DISPATCHARR_TOKEN: "{{ .DISPATCHARR_EPGMATCHARR_API_KEY }}"
        EMBY_API_KEY: "{{ .EMBY_EPGMATCHARR_API_KEY }}"
  dataFrom:
    - extract:
        key: dispatcharr
    - extract:
        key: emby
