---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app epg-matcharr
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      *app :
        containers:
          app:
            image:
              repository: ghcr.io/jstevenscl/epgmatcharr
              tag: v0.3.06@sha256:97ae105af615196c4c2daf7b2998aa153ffc436eae99b611410ce2a3fd326c10
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 8192Mi
            env:
              DISPATCHARR_URL: http://dispatcharr.default.svc:9191
              EMBY_URL: http://emby.default.svc:8096
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: &port 8281
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${INTERNAL_SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/data
      cache:
        type: nfs
        server: 192.168.20.21
        path: /mnt/tank/media/plex
        globalMounts:
          - path: /app/data/epg_guru_cache
            subPath: dispatcharr/epg-matcharr
