---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: authentik-hpa-maxed-out
spec:
  matchers:
    - name: alertname
      value: KubeHpaMaxedOut
    - name: horizontalpodautoscaler
      value: authentik-worker
      matchType: "=~"
---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: etc-db-fragmented
spec:
  matchers:
    - name: alertname
      value: etcdDatabaseHighFragmentationRatio
---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: descheduler-evicted-pods
spec:
  matchers:
    - name: alertname
      value: DeschedulerEvictedPods
---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: renovate-dependency-issues
spec:
  matchers:
    - name: alertname
      value: RenovateDependencyIssues
---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: k8s-04-smart-errors
spec:
  matchers:
    - name: alertname
      value: SmartDeviceMediaErrors
    - name: instance
      value: k8s-04.talos.internal
    - name: device
      value: nvme0
---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: longhorn-disk-storage-warning
spec:
  matchers:
    - name: alertname
      value: LonghornDiskStorageWarning
