---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: graphite-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: graphite-exporter
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      graphite-exporter:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/prom/graphite-exporter
              tag: v0.16.0@sha256:5728ca2557de1ae2723ff5cd2b9747ff505e0f8a762140b3b7828cb9949aeb25
            env:
              TZ: America/Chicago
            args: [ "--graphite.mapping-config=/tmp/graphite-mapping.conf", "--graphite.mapping-strict-match" ]
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /metrics
                    port: &port 9108
                  initialDelaySeconds: 15
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            # securityContext:
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: true
            #   capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    # defaultPodOptions:
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 1000
    #     runAsGroup: 1000
    #     fsGroup: 1000
    #     fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.20.229
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: *port
          metrics:
            port: 2003
            targetPort: 9109
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${INTERNAL_SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
    serviceMonitor:
      app:
        enabled: true
        endpoints:
          - port: http
    persistence:
      config-file:
        type: configMap
        name: graphite-exporter
        globalMounts:
          - path: /tmp/graphite-mapping.conf
            subPath: graphite-mapping.conf
