---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: graphite-exporter
spec:
  staticConfigs:
    - targets:
        - graphite-exporter.${INTERNAL_SECRET_DOMAIN}:9108
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: truenas
