---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: infrastructure
value: 999999
globalDefault: false
description: "This priority class should be used for high priority infrastructure only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: home-prod
value: 555555
globalDefault: false
description: "This priority class should be used for high priority 'prod' workloads."
