---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: syncthing
  values:
    controllers:
      syncthing:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/syncthing/syncthing
              tag: 2.0.10@sha256:3faeb52baa7de3fbe7007cecc6829a4bc71cc6ac62d3967459a8228979c38943
            env:
              TZ: America/Chicago
              HOSTNAME: syncthing
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8384
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: syncthing
        ports:
          http:
            port: *port
            primary: true
      listen:
        controller: syncthing
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "192.168.20.228"
        externalTrafficPolicy: Local
        ports:
          listen:
            port: 22000
            protocol: TCP
            targetPort: 22000
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
            targetPort: 21027
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${INTERNAL_SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 8384
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      syncthing:
        type: nfs
        server: 192.168.20.21
        path: /mnt/tank/services/syncthing
