---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless
spec:
  timeout: 5m
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      paperless:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.20.15@sha256:6c86cad803970ea782683a8e80e7403444c5bf3cf70de63b4d3c8e87500db92f
            env:
              # USERMAP_UID: &uid 1000
              # USERMAP_GID: *uid
              # General Settings
              PAPERLESS_TIME_ZONE: America/Chicago
              PAPERLESS_APP_TITLE: 'Document Archive'
              PAPERLESS_URL: 'https://{{ .Release.Name }}.${INTERNAL_SECRET_DOMAIN}'
              PAPERLESS_PORT: &port 8000
              # Tika/Gotenberg Settings
              PAPERLESS_TIKA_ENABLED: 1
              PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg.default.svc:3000
              PAPERLESS_TIKA_ENDPOINT: http://paperless-tika.default.svc:9998
              # PostgreSQL Settings
              PAPERLESS_DBENGINE: postgresql
              PAPERLESS_DBHOST: pooler-rw.database.svc
              PAPERLESS_DBNAME: paperless
              PAPERLESS_DBUSER: paperless
              PGSSLMODE: verify-full
              PGSSLROOTCERT: /var/run/secrets/root-ca/ca.crt
              PGSSLCERT: /var/run/secrets/postgresql/tls.crt
              PGSSLKEY: /var/run/secrets/postgresql/tls.key
              PGPOOLSIZE: 1
              # Redis Settings
              PAPERLESS_REDIS:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-dragonfly"
                    key: url
              # File Consumption Settings
              PAPERLESS_CONSUMER_POLLING: 60
              PAPERLESS_DATE_PARSER_LANGUAGES: en
              # Email Settings
              PAPERLESS_EMAIL_USE_TLS: true
              # Barcode Settings
              PAPERLESS_CONSUMER_ENABLE_BARCODES: true
              PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: true
              PAPERLESS_CONSUMER_ASN_BARCODE_PREFIX: ASN
              PAPERLESS_CONSUMER_ENABLE_TAG_BARCODE: true
              PAPERLESS_CONSUMER_TAG_BARCODE_MAPPING: '{"ASN01.*": "ASN-01", "ASN02.*": "ASN-02"}'
              # Direct User Settings
              # PAPERLESS_DISABLE_REGULAR_LOGIN: true
              PAPERLESS_ACCOUNT_ALLOW_SIGNUPS: false
              PAPERLESS_ACCOUNT_DEFAULT_GROUPS: 'Standard User'
              # OAuth User Settings
              # PAPERLESS_SOCIAL_AUTO_SIGNUP: true
              PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: true
              PAPERLESS_SOCIAL_ACCOUNT_DEFAULT_GROUPS: 'Standard User'
              PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
              # PAPERLESS_REDIRECT_LOGIN_TO_SSO: true
              # PAPERLESS_LOGOUT_REDIRECT_URL: 'https://auth.${SECRET_DOMAIN}/application/o/{{ .Release.Name }}/end-session/'
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: false
                type: HTTP
              readiness: *probes
              startup:
                enabled: false
                type: HTTP
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            # securityContext: &sc
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: true
            #   capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 959m
                memory: 2026Mi
              limits:
                memory: 2026Mi
      gotenberg:
        containers:
          app:
            image:
              repository: ghcr.io/mchestr/gotenberg
              tag: 8.17.3
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 100Mi
            env:
              DISABLE_GOOGLE_CHROME: "1"
            # securityContext: *sc
      tika:
        containers:
          app:
            image:
              repository: docker.io/apache/tika
              tag: 3.3.0.0-full
            # securityContext: *sc
            resources:
              requests:
                cpu: 10m
                memory: 300Mi
              limits:
                memory: 300Mi
    defaultPodOptions:
      hostUsers: true
      priorityClassName: home-prod
      securityContext:
        # runAsNonRoot: true
        # runAsUser: *uid
        # runAsGroup: *uid
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        # seccompProfile: { type: "RuntimeDefault" }
    service:
      paperless:
        controller: *app
        ports:
          http:
            port: *port
      gotenberg:
        controller: gotenberg
        ports:
          http:
            port: 3000
      tika:
        controller: tika
        ports:
          http:
            port: 9998

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${INTERNAL_SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          paperless:
            app:
              - path: "/usr/src/paperless/data"
      media:
        type: nfs
        server: 192.168.20.21
        path: /mnt/tank/services/paperless
        advancedMounts:
          paperless:
            app:
              - path: "/usr/src/paperless/media"
                subPath: media
              - path: "/usr/src/paperless/consume"
                subPath: consume
              - path: "/usr/src/paperless/export"
                subPath: export
      # tmp:
      #   type: emptyDir
      #   medium: Memory
      #   sizeLimit: 16Mi
      #   globalMounts:
      #     - subPath: tmp
      #       path: /tmp
      #   advancedMounts:
      #     paperless:
      #       app:
      #         - subPath: "run"
      #           path: "/run"
      #         - subPath: "apt"
      #           path: "/var/lib/apt"
