---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: longhorn-secret
    template:
      data:
        LONGHORN_BACKUP_TARGET: "{{ .BACKUP_TARGET }}"
  dataFrom:
    - extract:
        key: longhorn
