---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: longhorn
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.11.1
    # digest: REPLACE WHEN FLUX-LOCAL #1101 IS RESOLVED
    # digest: sha256:1565cc92017277ac14f3e55b326f7aeaad84c4ac1f4758de9be1ea89ff90655a
  url: oci://ghcr.io/home-operations/charts-mirror/longhorn
