kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-single-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
retentionPolicy: Retain
volumeBindingMode: "WaitForFirstConsumer"
parameters:
  dataLocality: "strict-local"
  numberOfReplicas: "1"
