---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ksgate
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://ghcr.io/ksgate/charts/ksgate
  ref:
    tag: 0.6.2
    # digest: REPLACE WHEN FLUX-LOCAL #1101 IS RESOLVED
    # digest: sha256:89c2357f030a92dca37a812e2a7bff2f311fb3711cb2c09012c2bdbb3051ab69
