---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: reflector
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 10.0.40
    # digest: REPLACE WHEN FLUX-LOCAL #1101 IS RESOLVED
    # digest: sha256:6d15b24661a79d5d0f45f9896346324eafa96a20123ab720eb043fe30b9c5f89
  url: oci://ghcr.io/emberstack/helm-charts/reflector
