{
 "title": "Dispatcharr",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "channel",
    "label": "Active Channel",
    "query": {
     "query": "label_values(dispatcharr_stream_metadata,channel_number)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instance Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dispatcharr_info", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dispatcharr_exporter_info", "legendFormat": "__auto" }
   ]
  },
  { "title": "Active Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Streams",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_join(\n  dispatcharr_stream_uptime_seconds\n  * on(channel_uuid, channel_number) group_left(channel_name, logo_url, state, provider, profile_name, resolution)\n      dispatcharr_stream_metadata,\n  \"provider_full\",\n  \" \",\n  \"provider\",\n  \"profile_name\"\n)"
    },
    {
     "expr": "label_join(\n  dispatcharr_stream_programming{current_subtitle!=\"\"}\n  * on(channel_uuid, channel_number) group_left(channel_name, logo_url, state, provider, profile_name, resolution)\n      dispatcharr_stream_metadata,\n  \"program_title_full\",\n  \" - \",\n  \"current_title\",\n  \"current_subtitle\"\n)\nor\nlabel_join(\n  dispatcharr_stream_programming{current_subtitle=\"\"}\n  * on(channel_uuid, channel_number) group_left(channel_name, logo_url, state, provider, profile_name, resolution)\n      dispatcharr_stream_metadata,\n  \"program_title_full\",\n  \"\",\n  \"current_title\"\n)"
    },
    {
     "expr": "dispatcharr_stream_current_bitrate_bps\n* on(channel_uuid, channel_number) group_left(channel_name, logo_url, state, provider, profile_name, resolution)\n    dispatcharr_stream_metadata"
    },
    {
     "expr": "dispatcharr_stream_buffering_speed\n* on(channel_uuid, channel_number) group_left(channel_name, logo_url, state, provider, profile_name, resolution)\n    dispatcharr_stream_metadata"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "dispatcharr_client_connection_duration_seconds\n* on(client_id, channel_uuid) group_left(ip_address)\n  dispatcharr_client_info\n* on(channel_uuid) group_left(channel_name)\n  dispatcharr_stream_metadata",
     "legendFormat": "__auto"
    },
    {
     "expr": "dispatcharr_client_bytes_sent\n* on(client_id, channel_uuid) group_left(ip_address)\n  dispatcharr_client_info\n* on(channel_uuid) group_left(channel_name)\n  dispatcharr_stream_metadata",
     "legendFormat": "__auto"
    },
    {
     "expr": "dispatcharr_client_current_transfer_rate_bps\n* on(client_id, channel_uuid) group_left(ip_address)\n  dispatcharr_client_info\n* on(channel_uuid) group_left(channel_name)\n  dispatcharr_stream_metadata",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Providers & Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dispatcharr_profile_connection_usage\n  unless on(profile_id, profile_name, account_name)\n  (dispatcharr_profile_max_connections == 0)",
     "legendFormat": "{{account_name}} {{profile_name}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dispatcharr_profile_connections",
     "legendFormat": "{{account_name}} - {{profile_name}}"
    },
    {
     "expr": "sum(dispatcharr_profile_connections)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Expiry",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(dispatcharr_profile_days_to_expiry != -1)",
     "legendFormat": "{{account_name}} {{profile_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dispatcharr_active_clients", "legendFormat": "Active Clients" },
    {
     "expr": "dispatcharr_m3u_accounts{status=\"total\"}",
     "legendFormat": "M3U Accounts"
    },
    {
     "expr": "dispatcharr_epg_sources{status=\"total\"}",
     "legendFormat": "EPG Sources"
    },
    { "expr": "dispatcharr_channels", "legendFormat": "Exported Channels" }
   ]
  },
  {
   "title": "Incoming Streams",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "expr": "dispatcharr_m3u_account_stream_count{status=\"success\"}",
     "legendFormat": "{{account_name}}"
    }
   ]
  },
  { "title": "Sources & Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "M3U Accounts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "dispatcharr_m3u_account_stream_count\n* on(account_id, account_name) group_left(account_type, is_active, status)\n  dispatcharr_m3u_account_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EPG Sources",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "dispatcharr_epg_source_priority",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "User Activity",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 30 },
   "targets": [
    {
     "expr": "dispatcharr_user_active_streams\n* on(user_id) group_left(username, user_level, is_staff)\n  dispatcharr_user_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Codec Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "count by(video_codec) (dispatcharr_stream_metadata)",
     "legendFormat": "{{video_codec}}"
    }
   ]
  },
  {
   "title": "Stream Profiles",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 30 },
   "targets": [
    {
     "expr": "count by(stream_profile) (dispatcharr_stream_metadata)",
     "legendFormat": "{{stream_profile}}"
    }
   ]
  },
  {
   "title": "Available Streams For Current Channels",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dispatcharr_stream_available_streams\n* on(channel_uuid, channel_number) group_left(channel_name)\n  dispatcharr_stream_metadata",
     "legendFormat": "{{channel_name}}"
    }
   ]
  }
 ]
}