apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:vCxCRnRChcamwdi7eok=,iv:PS3knioFGpWv51x86aJLPR6mZYBAFXnCBOykjiqOflc=,tag:kZAdKMnbdnED5VgiuUYVdQ==,type:str]
  DYNAMIC_DNS: ENC[AES256_GCM,data:/OHlXlBDT5sq/YVaKVXX+vS6/wzJKw==,iv:pEsI/WztlJr7JaARkvJ1P8SM2NgbziSp2lHG5MuVUSQ=,tag:z4dXqHuYFH7WStbOc/HDgA==,type:str]
sops:
  age:
    - recipient: age1yum2rd54mjqlzzpklr209h8qukjngtj5pnn74ugwntzkl6d9fvfqrrzmns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK1Z0NGRMcGFyKy9wZ3V0
        K29sZTJxbkdKc3lzUkhmL2VXMjlVNUhkUTEwClhHejVDMnhjOUtlZElkSUowVVNW
        cFZMa3NsM3I2d3RGYmxzTHRhTGx3OUEKLS0tIHNvZFNPa2diMUJjdlRnUzhBdnc3
        aFZiZ2NPcmVJYWVRUGkxbG4yWjY1WkUKIQsBDMLGEKV/p8SJ2eyfmx3zEStOiCwu
        YFf8Uoe0yiiX29u+kUHzHg4vk9laIsj9PYBRH+j4TMAN1lPmWykTfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-24T14:41:18Z"
  mac: ENC[AES256_GCM,data:vb4DsX9/unRAAjkyIZueb0s4FzycUPqVQB1n2q9Omk5gdEVTdJDQopQoFPNyiZIehbadpR4Cszt20u6i768Xryix8OkyJslKpd3wVOHiMEWSS3STkZO1Q8joXYaENHZj8cC/na3lypMbkXJl/Em7OPihP6wVNfGRvq+GmfUsH3M=,iv:h78OyhA5merBvuXhMpOcF15Exda9ZfhfXFGmB/CEqD0=,tag:bpOHqY0SfNF+jrKgerV8Bg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
