apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:vCxCRnRChcamwdi7eok=,iv:PS3knioFGpWv51x86aJLPR6mZYBAFXnCBOykjiqOflc=,tag:kZAdKMnbdnED5VgiuUYVdQ==,type:str]
  INTERNAL_SECRET_DOMAIN: ENC[AES256_GCM,data:icpzw36OLqv36UhP93zCoJPYIRMYykk=,iv:4kxW0fO2RZf+IAI+7NXg8OWe34XD4cB+rlKTF/uLkyk=,tag:Ly5iw+gQkzzKqkLnxNRcPQ==,type:str]
  DYNAMIC_DNS: ENC[AES256_GCM,data:/OHlXlBDT5sq/YVaKVXX+vS6/wzJKw==,iv:pEsI/WztlJr7JaARkvJ1P8SM2NgbziSp2lHG5MuVUSQ=,tag:z4dXqHuYFH7WStbOc/HDgA==,type:str]
  VPS_DYNAMIC_DNS: ENC[AES256_GCM,data:ccgtj4MV5GsCmPpN/2r9nAO46Y3rowyhT6Ei9iA=,iv:gaaBv+CHC51zpgTJt2WNVkeUOKk4KULmYojEbvKLEAY=,tag:kxDQ2GuyA/zcDBLLW+0ziQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScGFLeTBweS93d01Zbmh4
        aHVVREZtMGNTY3ZVQUUwZDhuWkZDM0Rtb3lFCkJuaGxWVFJ2YndyRGczbXI1VlJj
        S1E0OWNtN2FjVkNQbzFIT0lYNi92RjAKLS0tIHNJdWxlUEZHbllrcjM0VXRuZk9I
        eFpsdDBpTHZKd0szV3lHdkkvUHdoeG8KZtJqTcTP0iVfwwLefptfZA3qHrs8D/ld
        IF0etGmzICudgvHkDlNyVa+BHltvf+xRB9eGfDIDF8kJNtLspWrrbA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yum2rd54mjqlzzpklr209h8qukjngtj5pnn74ugwntzkl6d9fvfqrrzmns
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5ICtsVlF5S2pk
        a1NaMU5kZFlheG9tMUZLZXNTMHBrbUljZ1pTWXF6ck5qU1RwN2ptR1BnRk1hd1la
        dmZGWHNxeVU4THpzMStSZk5CVXgxWHN2SWdGNEE1WGo5V2ZobmpDUHYrbTZQanNy
        clVzWTFoUjlXeWZ4S2JGbit1ci9xbjU0c2RYMGQ5SlluQ2hiSzZaYk9Ja3ZJUFZq
        WnQvL3NjRytYTXFiZkJycExQc1BPTzhGdmgyVEFzODZheDk3cUFCdlB2SVlBOTJa
        YmpUeXpGY2RiOUVkSUpEaGozMVZscEVZdGZPU2JwOHZESU5PbDJYYjZrT1M2Nnky
        ekxLWXRpREJ4M1g2cGhSVFZ0Q3BoUzQ1Q2M3S0xnYVVRbjNWK3NkS2xZYXFxY1lx
        R2lPUFprRFZYRFdCNmxkQ2NDTDY2QW1uNm10eE5WelVqaHREbnUrNTNrVG1oL01m
        K0l1NmZ5V096R0p4UWFxa3ZtVnlaM3FDTUhJV0xKVVpTUXJNR1ZXZ1FHSzlwMlZE
        NDNZeEpzOXFPK2F4S0JQOStuZWVDY3RPM21oODd2SEpRRjh1N1czRmFGSlFBRW1x
        ZzZRSUZMMnlkWUJGaFNUQ0dlZFcyTEc0MGNDYkhnOXF2SzBrOVVsanBrM2RxRVpS
        aGlYcERVWnd3ZWVCK2VXVlovb0hyMDdLeEFYZjJ1VWpQVFlzSzFPQmhEb3hnNWE5
        WEV4RTh0TjVheXpXMFV0bGZWTEpFbzhiMUROWTJ4UWNPMDE2alBBU20wYlgwSUFT
        L2xMNXluUjIrVDB5Vi84QUFTRUd5aFhrc2dacWxqOGNHMGdGU3h6QWwzUk5VMmw1
        V0x2MG1DQTUxWWlINFhEeGM1WldGdmk5Ly9tM3dBdkd5ei9FUUFHb2F2T2NpeWVN
        ak8wRFN1azZHTmxiUWZpU2hzbVFpeEtmVE53L2MyVEVvdEVPVlp0djM0VEo5SUFQ
        dS9IOEJsdklheko1K0V0NUFYZUV0QVVrd3RlU3NuS0dGdWFVVWxxdm90M0EyRUdY
        VXRmZUVEa0xtL3RzNTBiVldMUnA0RFdUT21hVUtLSFNlTGFFRXZ5WVFjVlk5TFBt
        WERLYWJ5eW1pelAyWWpORDUrTDV0K3BQTnVWVEU2dkU0SXhXK0RUSlFuM2N0NHBm
        RmJmaStjdExQMHByL0tzTHg1cTA3ME1mVHFnZjlXMHBIZ2g5LzBTL3NUWEZialE3
        U0VZQXhMbE9VT2h5Vi9RdWVUK0tHaUU0M3VDTTZUWHhWSHhoZDVleE83Q1NjN3Nt
        TEJTbWVoN2tVc2VvOWgzOXE4Nit4d2JEMSs1MUJtR05VbXVBOVNDVHE2aWh2NDVw
        N21CRmVNV2pnK09rL3J4Ykl0WWwwTWxjaU8vaW9UallOSlgxYU1rajBxczhSUldH
        NmR3WmYxb1VFbklKSno3Zy9zeWM1Z3pjZThMWTNwcjA0Y0piTWt4c3V5SjlmT29Z
        RTV4SjJhS2hsdGQzMU5kQjJ3d1V5dWpva3p4c1hJbXJ4OFFCNXlQTEVsamhsK3ZH
        Z2lQL000elpjdlpxbTdmUmh3YlFrYlVvQk9la2hPdlZzaXIvR3E5M1pkKzA5cS9i
        WGJhK0g4VitXazFMWFZTb0t1OXVzSVRMTUEyVjZ2UmJxekhWVStGTEdaQTVtOThL
        aThYaFFmUlZTa2dzVFNOM01KRm50VCtqTmRMR0JZYnFFa0U1WVhoZnpObERBb3Vw
        SzlPajdtWlA5SXhwYk5ocjU4K2dDMlAzQnh6OW1KSEdxVm4vbmF3RmNmaUtkOHp2
        YmRpc0lYUzdtaVhXRlllMlFLdVZiZjY2NS82UEwySzRqUjY4SWtJNGxwNFFzWlg4
        eGpHLzdSKzF4ZEI1RFRJOHlyNFgzQ0U2QTBvQTh0WkNzN2JHVU9zSDRtSHFmQVpw
        eVZRczBTcURIL0M3OGpIYzhjejVTbzY4OEZ0MzJpanEvQ0crL08vUkgzbVJQQQpS
        UUNpa3N4eDhRbkFOR2RHL1kzL3k5bGtjQUlJQWh0S09UdlBUM0dhaENBCi0tLSBS
        OFRCa056SjdEcnpjSVliWGFyNDFDemp4VjZvZ0U1Q01XdXZSZFp1enZvCk2l6Ke7
        V7GW11LiOn90cL4yKbAT5052amxN8KFtq1Yy6o6kl/6Rb+GSKctgJpYrQMK/kAg/
        mggk02ouz39DliM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq17jrq9vucnth9v4e4gx5zvpsr6szqlcnp9mwt0rmyfyzeww97dyejlxsuvgnu4spgqgzwp9ms0dvrz4gtvc9lw6sxnjywpkq773nptcfqgvccxf6tnfq24eq4prfez8azp7k739mdcdmfx3plew9nl58e8vzwppgegzsmm4y477ycgnqcn2vpknyr3x7zm3eqd6yjrfeygt6582fp4fxpzjp5qdm3g6ncydqpq9g47p77p7cervten3snr0tr2zcptxurpfjgx6p2ux0up8a88qx8m0q6q2yreusmwe862h7rjshm8yyzmse5xsc9ydnkdjt3kz2au3lwqujsz0wy44yvvae99xxtcxejh96vjj5gcej9vwkkzq6k329lexv4qqv9rrz89r5v4qn3vd0sq3c8n8ve84gfdx75rse0xdthm9eafen5wfmc2v8ektj4yz6qlk9dm89q5xzy9vvyscc3vlrmwzfkt09eq9h3npzxr92ths4fn3zct5x9yrv5k87st3s3pqft52qplqtjlzgkpq4pp967mvtxejnnjnsf6y9yqfavh9xqgjehk0pl8sxf8z3pr3kf90esvw6fc9y8j52qnxyrrtfwk8rjj686nfp7matvx7w8cyewnz466wdl2k6l97zpe43s8t0rf32qufadeh96jz427ajnx02xzwaamvsqy65ppwpc639j244kxcpqqej9scfz5k3znxmeprr4rpdnevl6sktult2geu7psahqtpyau0pztpjlvap4zvpxdj0tqa9763pq7c626qcrs69yjyzd48pw670m7fmzh2a3kjger7xuhz6l8se2zqtsxz2e9vlshjjh3n6fz4xzpwqtcrt8f5jnnt8nqk7hj236d7rt5dzxt8sujy025uexsuqtdgfwm8v2j8fh90whg9kxhpswctytua5kete82c90jevuqytaxlqtped4kuu4wzsawnkhw3000xzp9uvtrxwerddlvzknzz3lueydzkzfg8qswae65e8lefj8feywjp9el06r3murqlzd27lm70z289re5zp3ftxsy2fmp0rnvuu2h04qywtgwp0s9w0tqzy8l7jz88mn34qgjglhrpj6tp2l02467twzx3jnt9204pvfwy7rxyucqvajxe5hddf8vlxlfza262fux4ggpfqh59zyjl8jm9vx064nhhcv52d39gtyntg9vsxx0gzamzzruyqf8mhed9l2hgzvgvnmzrjt856phzmuymy9edafdxx27st3ehjncz2u39h3jgars8y98p9pmqjpcajuryc6pgul2qznyxdp79jcnt4cwfzxkuyphc2n5krhd0628lzhs8d2y4et3579sfc65y0kf6u7rve8wf4yswuh74jqrhfue0rgg2qhcpxvt9mexnac0fm8f5w5g4fy92hheyqvens9xpc9t0vz3sqcjamkp2ewtvqg4dhnwxapzv2zvervr8rfzmvzau6r27q8dg6rj74az6grle535tlq0s7xyylxud3xn5znfdxf0ju3jhyxxe7zy9yxdp9zp6v2e26zydsdymk5cgppt0qegkk995l6vjxt9f7t4wrch7vd3ljxu3wkyvppg29zw4ee29fqqwm84p5edjpn4fnqm3fsr5nhnnz6ft29e020chr0v7s64ppeyl36nu63zq8lc0f7ly0jx4495vv49ayqxypmzxadnd66xmxwxs7vwlczdkmtetymgkws09rtzkg903g4qpyn3nr6uk8ch69ksr5kc268e5r3dwnnw9uupgch34n2sn85hc3xt3ggys5x8sqmr3u3gllg0y3yq5fg0pmkrvafr8qfwtdve55gdlaavdqeqq2fq04sznlnpa3xctc7rtj5gc54sugwjn5gzr6jcczu95ynpeefsd0r7ngkq3r7vhupsk7uu57dqv4x2fme
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-01-26T19:35:33Z"
  mac: ENC[AES256_GCM,data:TRcvELKovjZoLp/UwQdVDZ7tGE0mth1v0lgNcefRJclhyYiP1z1wdQY1UX+/Jsp3zqy5u3lPn7DeneeAwsjX1D1wbaj/YK/o/2ruqhbpmafLeGgBqOCWWspzPXOvtmr4qzJbh9MFMbCNd7PlISg7ZUDujybGRxMDVhFV2hj2IRI=,iv:iCrhtHLlTT+OOZ8ZUBFSRqqBhU6FzlroljZaR/TBRJc=,tag:+z7cEdS8tkHwUkIuHyrnEw==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
