apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:vCxCRnRChcamwdi7eok=,iv:PS3knioFGpWv51x86aJLPR6mZYBAFXnCBOykjiqOflc=,tag:kZAdKMnbdnED5VgiuUYVdQ==,type:str]
  DYNAMIC_DNS: ENC[AES256_GCM,data:OwgMTu30gUvg4syysRhvCmGMaaJhdw==,iv:7OQeVRQOC2Px3BFwi9ztjlJV6GRmeMtS6qRvPu4+wvQ=,tag:42zcI31LnMoQ490mEgpaRg==,type:str]
sops:
  age:
    - recipient: age1yum2rd54mjqlzzpklr209h8qukjngtj5pnn74ugwntzkl6d9fvfqrrzmns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK1Z0NGRMcGFyKy9wZ3V0
        K29sZTJxbkdKc3lzUkhmL2VXMjlVNUhkUTEwClhHejVDMnhjOUtlZElkSUowVVNW
        cFZMa3NsM3I2d3RGYmxzTHRhTGx3OUEKLS0tIHNvZFNPa2diMUJjdlRnUzhBdnc3
        aFZiZ2NPcmVJYWVRUGkxbG4yWjY1WkUKIQsBDMLGEKV/p8SJ2eyfmx3zEStOiCwu
        YFf8Uoe0yiiX29u+kUHzHg4vk9laIsj9PYBRH+j4TMAN1lPmWykTfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-24T14:19:40Z"
  mac: ENC[AES256_GCM,data:8UkxYY9oeYpF/WE2QhViTrAp6snh1KcqAuvVnTZp8W31O2XpovAoeF9AahNmqJ2Wd6JPnBNIpxK9s/PlQT9q6m1GPS3YNeyUWdANqjDve1+zpf68+meABRIOYlYv+6SSabO+MeXlZ0EaJba4luuMBssznYrWf+1b1Lt9o+bYCl8=,iv:HX6zVCRkNLATMZFWQrVPHiE1xGnb3rkoUosJ2szohts=,tag:73+DMeMNEzKLO3X1bDoi6Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
