apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:vCxCRnRChcamwdi7eok=,iv:PS3knioFGpWv51x86aJLPR6mZYBAFXnCBOykjiqOflc=,tag:kZAdKMnbdnED5VgiuUYVdQ==,type:str]
  INTERNAL_SECRET_DOMAIN: ENC[AES256_GCM,data:icpzw36OLqv36UhP93zCoJPYIRMYykk=,iv:4kxW0fO2RZf+IAI+7NXg8OWe34XD4cB+rlKTF/uLkyk=,tag:Ly5iw+gQkzzKqkLnxNRcPQ==,type:str]
  DYNAMIC_DNS: ENC[AES256_GCM,data:/OHlXlBDT5sq/YVaKVXX+vS6/wzJKw==,iv:pEsI/WztlJr7JaARkvJ1P8SM2NgbziSp2lHG5MuVUSQ=,tag:z4dXqHuYFH7WStbOc/HDgA==,type:str]
sops:
  age:
    - recipient: age1yum2rd54mjqlzzpklr209h8qukjngtj5pnn74ugwntzkl6d9fvfqrrzmns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK1Z0NGRMcGFyKy9wZ3V0
        K29sZTJxbkdKc3lzUkhmL2VXMjlVNUhkUTEwClhHejVDMnhjOUtlZElkSUowVVNW
        cFZMa3NsM3I2d3RGYmxzTHRhTGx3OUEKLS0tIHNvZFNPa2diMUJjdlRnUzhBdnc3
        aFZiZ2NPcmVJYWVRUGkxbG4yWjY1WkUKIQsBDMLGEKV/p8SJ2eyfmx3zEStOiCwu
        YFf8Uoe0yiiX29u+kUHzHg4vk9laIsj9PYBRH+j4TMAN1lPmWykTfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-26T15:36:53Z"
  mac: ENC[AES256_GCM,data:cm8E9/bcEuToadf5rjYlBCBODzESPlLwzhCRSukX0x79cd/3sDSjIk0sWcX0whMoG9TaYS/+DLwg33AiZxZLRz3mCN7KZ00fbdgGzbukrvMo9ZTI2mZbu+diT3wz/rgbKm3PNPnsNKyQINdSU94hA5NdqhkYL0fDC3eqgYO7fik=,iv:ayVoFuZGMuK7LAdU7eyGaTu7y1+VK3q9CNVMLsGNZdY=,tag:MN+1PhgfprqyrozC0WEIHw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
