apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:vCxCRnRChcamwdi7eok=,iv:PS3knioFGpWv51x86aJLPR6mZYBAFXnCBOykjiqOflc=,tag:kZAdKMnbdnED5VgiuUYVdQ==,type:str]
sops:
  age:
    - recipient: age1yum2rd54mjqlzzpklr209h8qukjngtj5pnn74ugwntzkl6d9fvfqrrzmns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK1Z0NGRMcGFyKy9wZ3V0
        K29sZTJxbkdKc3lzUkhmL2VXMjlVNUhkUTEwClhHejVDMnhjOUtlZElkSUowVVNW
        cFZMa3NsM3I2d3RGYmxzTHRhTGx3OUEKLS0tIHNvZFNPa2diMUJjdlRnUzhBdnc3
        aFZiZ2NPcmVJYWVRUGkxbG4yWjY1WkUKIQsBDMLGEKV/p8SJ2eyfmx3zEStOiCwu
        YFf8Uoe0yiiX29u+kUHzHg4vk9laIsj9PYBRH+j4TMAN1lPmWykTfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-22T18:18:37Z"
  mac: ENC[AES256_GCM,data:ZMTdZoCMurJrjaAGcFL7/9mBC1bWqFV+S/94mm1FM6QIzxizjR9/ammjoRJqx8xmcZRw8JJ+KbX47NHMbmw+VVh9JcVlhLxZ/nqn44L/RJ4IcM5VfpUnaVMGVEnNbG5jTuBGqu4NyHkoIzze+oxIWlsuPcv34CJbSal+RVEs6kY=,iv:A58UqybiJoXLjpo3+WGG4n0scpGhXiHmx1zU59JnP+Y=,tag:iiqjOYwN6t3raE00K1XhSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
