apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:vCxCRnRChcamwdi7eok=,iv:PS3knioFGpWv51x86aJLPR6mZYBAFXnCBOykjiqOflc=,tag:kZAdKMnbdnED5VgiuUYVdQ==,type:str]
  INTERNAL_SECRET_DOMAIN: ENC[AES256_GCM,data:icpzw36OLqv36UhP93zCoJPYIRMYykk=,iv:4kxW0fO2RZf+IAI+7NXg8OWe34XD4cB+rlKTF/uLkyk=,tag:Ly5iw+gQkzzKqkLnxNRcPQ==,type:str]
  DYNAMIC_DNS: ENC[AES256_GCM,data:/OHlXlBDT5sq/YVaKVXX+vS6/wzJKw==,iv:pEsI/WztlJr7JaARkvJ1P8SM2NgbziSp2lHG5MuVUSQ=,tag:z4dXqHuYFH7WStbOc/HDgA==,type:str]
  VPS_DYNAMIC_DNS: ENC[AES256_GCM,data:ccgtj4MV5GsCmPpN/2r9nAO46Y3rowyhT6Ei9iA=,iv:gaaBv+CHC51zpgTJt2WNVkeUOKk4KULmYojEbvKLEAY=,tag:kxDQ2GuyA/zcDBLLW+0ziQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGZCSXRCOWZn
        NEdpQmRHb0kxSFp6QkdaOEcrbEJzR3FRTzcvRitnTk11MmJSc1ErY2dvSmZFcVUr
        UCtIVTdmYzdSdjJDQUJpeEJnV01aWlozaXRML1d6RWozN1pPQVhGcUpSN3BpSE8v
        cnJaWW5lVFI0Uk80Zk94aG1MV2VHQURqMjlza3ZUcm84TjhzTGVGdVBmNmJkTHlj
        eDJ0dm9MaHYrVlVDanY0UTlTVG9BTHZsT0xrUkU3Q1F4VmgvV3UzRHBWQ3I4djdT
        cmVDa3lwVXJRbkVFdTF3NDc4dkkxMkxoSnM4VUNxL2JHemMxYlExREJkZFZFWVhL
        MjBxREs5cjJLdnZPWTlVWmJFaUpabU1VQ1lmemczQkZKRFZDb3FwRW1jYjRHcFJO
        TTNPRllaV1QwZ2hJVEN0ZEpQN29vVlRndzQ3U0ZkK2lrOE9pQUY5SDE0MklGaTJZ
        bmJZZVhGUUhkMnY2WHJWcmdxdGU3Nkk0UWJGR3U5ZzBxejl5cmgyS2F0TXlqU3VD
        dVlHU3g5a2VTSVhpZDRab1hwUkdjb0JGZlR3S1N6eTBlbWY2Z2JjTmZoa2dkbDg2
        NmlNdDl1M05ocUpLWHp4MlZ6Ky9jWU9Cb2x3WUllUUVqTzdUVmoxbU0yTERoYjN5
        UWV4eDlQU0dGSDByT3RYdXZhMEM2MGhaZVNORUkyVG43bGE3TVo3RS9ZNVJHSnd5
        UDEzL09RT3ZBUmd2ZUpDZnVOSmxpTFJISzZwT1NsM2ZsaWdOdW1uMHFyZ3Vqck4r
        ZUpFMFR0Y0pnSGUzdXBSTXl0cU84ZUhwUVB1UklUQ1JVWGhxTmc0N0dGMmRIUGhG
        TmkvclY5VUc0clNod3QyVmVQU216dTBTU2dQV2orOFhJbHFaajZtOElzMGwzLy8x
        a20ycSs5WTVJQlJGczEzYjNTSzlDYnBQSHRpUFpnblBFUk04UldCM3pac2xBZ0c1
        dVJYRkF1OU5UTFJyZWExWEJZQ3hGenYrcTgrVU82Z1pDZ0RDY3Z6V0hMbGFyYVdL
        dVcycDBWODJaa2lqMHZpalBaMEdQbHVudEMzYXpkRGxIcG50UU15UVJWVTRxOE1v
        TG44QlBhTHNNWVNnZDh0U2dhZVhDZ1YvVzZpZTcvcXR3NkN0YlZjQ1lmMDRvODR6
        di9LeW9jL3Q2K25QOFV0TGtJcWdqREc4VldJd2Nmb3lYUWRBUHNQbDNjOXgvWm40
        MkxHb0JFVWJFSlgrcFNWV3ByM041S09zK2NJTS92SWliUk1VY0IwakRuUkZWeGdl
        YkRweStMMUZDRmU1OXY0emZaTGNOZWNZNDZWY3BKUGZCQm9yUjFFVENQVHJrcTJp
        alE5RXllQlFZNTBGbzJmUEM3SGcxRTZFeDRSa1lxaVZ1b1M2S1BEZlRTaG1XVnJY
        SjQrQ0JzZUVjU1lRVFkxeG95NGhQb2xzOXpPOXlkbnFMZ3I1M1RuOENiNTBnMW5S
        dThpSktEYU5qTnRsN1VZVVhjTTltbHNsTEhMcGJSVnJzeW1GdTVlL2I1T2VmUldF
        bjFJSFJGRGFmUnNKbW51SG9ub0ZHVDN3UFRTM1V1V0x3V2lrQjBEb2FFMGVKM1lk
        V1hNQTZBMHY1cWVPbnY2TWNtek84TFpZM1paSGZDdFdtdzE3OW5NL2J6a2JIVlRm
        YzJ0ZmM0cjRLbEpndEZJZWhPR3ZpMzk3SC9kWE5SUmlJNkhuN3Voa3ZUenhpRDRY
        QlNET1N3MCtkRjF0K2Zja0ZVY3YrMGhhdkZwNDVjUEpVMVR4NElxRUp0dnlPWmtL
        Wmk5WDZXbmsvb0tLVVd5ZUF3TldGWDg3Uk1XYUtKUFpDbEpZWHNyeDJEVWFoL3FD
        QlpsUldJejhVK2Z5QmhKeGVMbFJVL0pVYWluU0RYS3c1MGMydG4wdFBYdy96cjRO
        cUhnTEFRZWl0NEhTcXczMmwxNkxGNXFZM0RsMyt3bUNYeisrMUxieCtpZ1FYdwp1
        bVlaa25EQmpUTEpYZ1VoZ3pKcWpDN2dmTmljM3QrSDdlUWxyZkc4T1hBCi0tLSBq
        WmZ3TSs5dzNyVVJ1WVBVc0FYQ0RBTUszQmFUbVMzWXd3bUxlM3R5NVhNCnXQACSG
        Llpa1aHEa0aqDMqTilZMr0rLlwXNOm5NAmfNPZFVJx43QXNyzTeOIlEXK7zg3HHq
        ef70EaTAUVJu92E=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1z3jcsx8evc570sfle3awhzqpnwf87dt3rknwq6s9kwwknd2ymct3xajqd0jm2yqely8eqdjnd9r6asv5k405v0hk3zxleenpeyakz6m5nl9ennu4nqerz5duzq6xurtmv0pd5zqz2wd7uy9apaeec8zf8t8mdjs65cvamx9gpae9uz0kf45lez0wwd42d0qnzlskqjsyc2vmptwtx6xj3amxksyjs45grvjmjaqg7j58ed45g9x88hafqmphx30hrwk9alq73eu3gadzjhy4qg4rwf5xwpwvpvkxjqkzyws3kstmwfav7r9rmuenj2xhwfgwkgeyj5ezytyrylv2mdnny7tg27r9sxg6jvctvs9uctv4eg9dyznfnj679zqz52sztpu84raye0p9d9aadr9cj3j2zpkezttdgzgmljc87d58szj65ydpnr4uc8a6s7edj2puy8x8qydyh7yl0ngdjey0z2v736s527sy5mr0ydgag0p5t3dzrajjsl7jrx9lf3t3nwaguysc9568uryf9sjfj4dpcrps2eyhvdj9rj8uc0eqh3fsscc4pkx0jfcc0wm5j72a33ffwr8yxwmqdrgyemfvcy87vl3mw5fmnz520ddp8fzq8pw2k70e8dmqakkwwkyqlcf23cwgxsvlku42n7zhx5ssd0g2zj0mja5e2cgfjdkpmdy8u08prg878y73vzgs52cpw9y8suunhcefcrccldwewwptaw4n6hrqeaqcz848yesmhym2d2nnzkt4sw9tsjd3pz9tq2teqxq37xncqfuetntcfzauevmjftezravjc03vc05d6jtl9l9lpp5cyswnzgqhxh55l9s4q6nyauevfyg8wrwsk5prlsuzkk2s6zzqyduq5z6lghzsjc9nggvw4lsek65ggayzwx4h0whd87vf96qhmltr4hupt35ughrmhpy7f93rqcvn93jy3t087ammgzv58yeq9m8ejxmxggdn2w48fyjjy4wqtsqun5z6wfrd2z2ej89r6ca9tng6nk5qq8295hye7mrqfmjsx6mevh720gcamjseszs7s7uvkw5zs9ngg90tlsev2qm73rtkpmrct825kquwqdp85utcrfaeerc83qe6k34dccn0j9ntqj7tkyyf8xpl5zgymylvn2d6ksprue8eqf845wdvkpfg8m9jgd4ftqqepqr0vtn3j26ntzgn9h382chnw3snkhvn5mz2wgz2nayslsfv0q8m254thzw4yax8l93z6475dv5efpywv9p9zu6273azs84u5qpnxgactdcekvzuengh8xyreqpxwmsmuca25w9e9rque9ytvufg3p4ngkg74zmrssn5ykmzxgfekp6qwglwpztnjpfps4ueykr78g7cx4srk72ansxxu92ev3agk6lczf6leuk0gep63zs2rtl9ja3uwjvs0c2y97qss3yngpl9rph5z6tz8quxdef8v598sqkxccyu5zw5cyj8sw24q92gwxpjqqc5hwmwree040yrsekx9kycyfyhxsu23jyhfj9jy2yvsle4frpqcerupgwfa8rgpuggzdqvzd34xkwajxzheqt9xxlfw7hd82w5kvp7txty7f2nxxmhqsvzvmxxawnc9659wc94zy6u4c0r8fzd7hzw9krfmktcsfxvjdesx3ym6l9us648f2uqcu9jw7xteft7tptglfsmfafqk523gyrxttmhcddsf5mupzs5nvtk0eqf3nfs4slzhay9dzzrcmyzxd0srzcrqew7f3gl5t9ycnc4sh0yj679dpzd846epwmcwy7exynzc0jqveq53udqhj5d0zxvzfepcpxe0ars97krgngssyvkw2hec0vswsj3q20g8xl5syte9ez3cl2sh5uvaw7080s9kj573lyvwcklu8fvtzwhzq2am6ar
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-01-26T19:35:33Z"
  mac: ENC[AES256_GCM,data:TRcvELKovjZoLp/UwQdVDZ7tGE0mth1v0lgNcefRJclhyYiP1z1wdQY1UX+/Jsp3zqy5u3lPn7DeneeAwsjX1D1wbaj/YK/o/2ruqhbpmafLeGgBqOCWWspzPXOvtmr4qzJbh9MFMbCNd7PlISg7ZUDujybGRxMDVhFV2hj2IRI=,iv:iCrhtHLlTT+OOZ8ZUBFSRqqBhU6FzlroljZaR/TBRJc=,tag:+z7cEdS8tkHwUkIuHyrnEw==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
