apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:vCxCRnRChcamwdi7eok=,iv:PS3knioFGpWv51x86aJLPR6mZYBAFXnCBOykjiqOflc=,tag:kZAdKMnbdnED5VgiuUYVdQ==,type:str]
  INTERNAL_SECRET_DOMAIN: ENC[AES256_GCM,data:icpzw36OLqv36UhP93zCoJPYIRMYykk=,iv:4kxW0fO2RZf+IAI+7NXg8OWe34XD4cB+rlKTF/uLkyk=,tag:Ly5iw+gQkzzKqkLnxNRcPQ==,type:str]
  DYNAMIC_DNS: ENC[AES256_GCM,data:/OHlXlBDT5sq/YVaKVXX+vS6/wzJKw==,iv:pEsI/WztlJr7JaARkvJ1P8SM2NgbziSp2lHG5MuVUSQ=,tag:z4dXqHuYFH7WStbOc/HDgA==,type:str]
  VPS_DYNAMIC_DNS: ENC[AES256_GCM,data:ccgtj4MV5GsCmPpN/2r9nAO46Y3rowyhT6Ei9iA=,iv:gaaBv+CHC51zpgTJt2WNVkeUOKk4KULmYojEbvKLEAY=,tag:kxDQ2GuyA/zcDBLLW+0ziQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEpuSXRwaFA2
        UlJDUmF0em1YUlRlTCtKbWFWZzF6T0Q5RCsxRXVXenhxSm5hVmxLd3J5SWVQUERW
        UytTREFNWUJwV3VZdmpKOVUwY0dzMnNCc0l6VXpzU2VmN1VqZWlsRXF3ZXRleTcy
        SytHT0UwQWNMLzIyRnVXbU1BQXN2QUZwODVBVTdCR1JMQzZjcDZ4ZGhwOVIxNW5D
        Q1hUNkxObTdMQ3dDcE1iWjhsWTR6dVFJT1NvWFQ2dWZtOVRRcEhPdGNWb0FadFA2
        OVhRN0ZSSHZHZkR6ZEpZZUYzVFk5MDdldE1nazVPYVgwakRmQzc5TVAzZDJ6b3NU
        U3I1V24xNGZSeTBNVjFQeTN1bE5GOWVuY3I3d1hkSG1qT3cycnFvMlBBT1dPWUEw
        bDRvbnhKUnZFaXBHVmZnZXRJeml2YTAxemFjRGUyVlR4a2hFMktzKzBXZEorM2ww
        YjRqVkIrOEt5NVJlWnliOE5MTjNwcldXNHIzdWcyRkNiMTBnN0VMNTVPNmFEUTFy
        QnpaTGo3N2w4aVpOT1YvTFplTUlQckg2MzYrSWRsem95RVc4dGlsRkM0bEFNZUNR
        eGNNWVZQMlVFSlBYUUlrMDVKQThEZnpCUnJuUE5BSjNnTkUyS0ZIaHZPMThYYUNx
        N3kxMmlOem12MWJ1QndtQ0l0cUk1dk9ZRldCbWd3SHk4UDFRTTZoeExWU1MxaEYx
        WThMeE5iZDJncEwyRDhYVjM0ODFjTDVjMnJaaHlFZmk2NDdMaHlKU0p0RWRXSjdy
        d01xTW12ZHFoZnV3SVpIRjlVaHRmSWhvekhlYUJ1eTdDMGNZdFNmd3A3aVNZOEZ3
        cERUYlR4Um0zUXRBVW1Nd29oMlhldG1aSktiaEZkRnJ2dGZTQzgySHYvTkpUUVBN
        QkVtQ1F6VWRwdndVaFJBZ1FqNTJ5Z1dVUlpiU0QzdE1qdFFsNlQzK1FsTExKWDlJ
        SG9SM1kvV3NmZ0ZrdG1BNzFCT29ZWjc3azZwRGE2ZlhMMXA3Y05HbjJSNFh4UHlk
        djJ6VkkzTWdJRnpmSlNEeXFZMWxxSHZ0c1BxaWg3RmVmOWhhU0VTZ0ZUbERwZmp6
        dHhQRkJCbjh6QkZHSnVZYnpGdS9aanJHWW5tYXpqQzE4SU1YVmRDRjAxcXJ3bkZV
        Q2FzYnBvY2Y1d0lZMjQ3UWVyQ21GaGducWpmMFhhY2VYRHl3dTh6aXhsVDA1NS9o
        Y2lNVkdsaEtwTWdTTEFaMEF2YTlvZk8rN2h4ZVBOcU1PemNIUGRqY3hlMEZjR2NX
        NVFPL2NuSzcyNTk5RFYzQml1cUYyOU15d3pPcUJwUUx5eWM2Tk5YaXM4YmR1ajRp
        TldzckxsL3ZSc3hOWlhYckNaek5vWS9JQlNIM0J2TzBuZWYxTnNpNDNrSjRZek13
        OHNDbHdVY01ZaVdnSVRsbVRzQVcrUStHbXIvN0x1WEkrdkZoSHAwUU1jUzZTR0RN
        LzgvK3JQYitoV2tZVG9meExNb09RWnZDRjQ2a1AxMjZsUm1Pb0dPN2YwdWR0NHFV
        bElZYlpLVmNhT25hUGJuVlA1c2hrVTNUZWtaVDIrUmtWdnhQYmVBUkNxVzVkRHR5
        aENMUnZZQXhvZVVSQzU2S2xSMVBrbEVnYWdRNHUycDNtUmdVWGlaWGE5VFBsRXdX
        QWVJNVFZMkszLzUvODQxdDA5L0pUVXhDL3BNRlFoNkZuKzZ6TWdHWkdkOWY1Um5Q
        cXJlWmVTd281djhMb0d4L3VIZTNXQUI4Z1hIRnBHaVhHOGt3Vng3N2JRSUF1T3lZ
        TGNFQUJCdy9hbkFNY09Ka0gwQklrYndONndidVJKVXJwbkRLVWRmWGhHNjVzM0tv
        QW9FNFVvMDR4ODBIa2NRT3lRSERHRGoza1R6bkQ2NnFWa3JnK2tWcklqcFphVUU2
        aUV4ODRqelc4RjlheE9QaDBuOUFkRjlCOWVudkQxUVB1NzZHejRzRjlydklidwpU
        Y2FCYWRmZlBVYkJIcGlXaVBRZTJMTkhjTHphVEtUU0txWmVEZm0yOHVVCi0tLSBm
        VUQ5MGJDNExET1dwSVF6bXdxTkFCOUZzZkhzUVhyNmx5alhhNnlhY3ZVCl7xmqcE
        G9OP3lTfKIi/xqNlageLBoPUToIc7Y7r4t4Zw85hakiylxuRaj4RmiVH/JXKzuZJ
        M+0SsIU/mWEXII0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq17jrq9vucnth9v4e4gx5zvpsr6szqlcnp9mwt0rmyfyzeww97dyejlxsuvgnu4spgqgzwp9ms0dvrz4gtvc9lw6sxnjywpkq773nptcfqgvccxf6tnfq24eq4prfez8azp7k739mdcdmfx3plew9nl58e8vzwppgegzsmm4y477ycgnqcn2vpknyr3x7zm3eqd6yjrfeygt6582fp4fxpzjp5qdm3g6ncydqpq9g47p77p7cervten3snr0tr2zcptxurpfjgx6p2ux0up8a88qx8m0q6q2yreusmwe862h7rjshm8yyzmse5xsc9ydnkdjt3kz2au3lwqujsz0wy44yvvae99xxtcxejh96vjj5gcej9vwkkzq6k329lexv4qqv9rrz89r5v4qn3vd0sq3c8n8ve84gfdx75rse0xdthm9eafen5wfmc2v8ektj4yz6qlk9dm89q5xzy9vvyscc3vlrmwzfkt09eq9h3npzxr92ths4fn3zct5x9yrv5k87st3s3pqft52qplqtjlzgkpq4pp967mvtxejnnjnsf6y9yqfavh9xqgjehk0pl8sxf8z3pr3kf90esvw6fc9y8j52qnxyrrtfwk8rjj686nfp7matvx7w8cyewnz466wdl2k6l97zpe43s8t0rf32qufadeh96jz427ajnx02xzwaamvsqy65ppwpc639j244kxcpqqej9scfz5k3znxmeprr4rpdnevl6sktult2geu7psahqtpyau0pztpjlvap4zvpxdj0tqa9763pq7c626qcrs69yjyzd48pw670m7fmzh2a3kjger7xuhz6l8se2zqtsxz2e9vlshjjh3n6fz4xzpwqtcrt8f5jnnt8nqk7hj236d7rt5dzxt8sujy025uexsuqtdgfwm8v2j8fh90whg9kxhpswctytua5kete82c90jevuqytaxlqtped4kuu4wzsawnkhw3000xzp9uvtrxwerddlvzknzz3lueydzkzfg8qswae65e8lefj8feywjp9el06r3murqlzd27lm70z289re5zp3ftxsy2fmp0rnvuu2h04qywtgwp0s9w0tqzy8l7jz88mn34qgjglhrpj6tp2l02467twzx3jnt9204pvfwy7rxyucqvajxe5hddf8vlxlfza262fux4ggpfqh59zyjl8jm9vx064nhhcv52d39gtyntg9vsxx0gzamzzruyqf8mhed9l2hgzvgvnmzrjt856phzmuymy9edafdxx27st3ehjncz2u39h3jgars8y98p9pmqjpcajuryc6pgul2qznyxdp79jcnt4cwfzxkuyphc2n5krhd0628lzhs8d2y4et3579sfc65y0kf6u7rve8wf4yswuh74jqrhfue0rgg2qhcpxvt9mexnac0fm8f5w5g4fy92hheyqvens9xpc9t0vz3sqcjamkp2ewtvqg4dhnwxapzv2zvervr8rfzmvzau6r27q8dg6rj74az6grle535tlq0s7xyylxud3xn5znfdxf0ju3jhyxxe7zy9yxdp9zp6v2e26zydsdymk5cgppt0qegkk995l6vjxt9f7t4wrch7vd3ljxu3wkyvppg29zw4ee29fqqwm84p5edjpn4fnqm3fsr5nhnnz6ft29e020chr0v7s64ppeyl36nu63zq8lc0f7ly0jx4495vv49ayqxypmzxadnd66xmxwxs7vwlczdkmtetymgkws09rtzkg903g4qpyn3nr6uk8ch69ksr5kc268e5r3dwnnw9uupgch34n2sn85hc3xt3ggys5x8sqmr3u3gllg0y3yq5fg0pmkrvafr8qfwtdve55gdlaavdqeqq2fq04sznlnpa3xctc7rtj5gc54sugwjn5gzr6jcczu95ynpeefsd0r7ngkq3r7vhupsk7uu57dqv4x2fme
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-01-26T19:35:33Z"
  mac: ENC[AES256_GCM,data:TRcvELKovjZoLp/UwQdVDZ7tGE0mth1v0lgNcefRJclhyYiP1z1wdQY1UX+/Jsp3zqy5u3lPn7DeneeAwsjX1D1wbaj/YK/o/2ruqhbpmafLeGgBqOCWWspzPXOvtmr4qzJbh9MFMbCNd7PlISg7ZUDujybGRxMDVhFV2hj2IRI=,iv:iCrhtHLlTT+OOZ8ZUBFSRqqBhU6FzlroljZaR/TBRJc=,tag:+z7cEdS8tkHwUkIuHyrnEw==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
