apiVersion: v1
kind: Secret
metadata:
  name: sops-age-pq
stringData:
  age.agekey: ENC[AES256_GCM,data:qyYkADsauPO3+gevW2vtguJ1pjzPF8XAwM8+6l1WVgjMy6vrH72/Z15gOcVj6rOZAtoskKIscATBRqk0YI01GobFs185U0kXpyqkNTg=,iv:U0oppeP01RtaWBrUISDJIqgxVu2PhDtDRbIqTjlqGwI=,tag:AUVTAs6/4+xe+Qh0eN3S0g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHY3Y3p0d2hN
        Slpza2pDQmlyR3hxY1NTYy9EYUZ6SjdseW92OE83cFlpTG40OXk4b01qNUNXaElY
        cVBycFFuKzNiMUQwMk5NelVNb016d2hGNHhpSWNXbEpnM0piRGJDeFZXZWl0UnQ0
        NVVpaXJneGUvRUYzalNWT3JZWUJaRFBuTCs5RnNja2s4b0VqSTNXOEpQTklxNjl5
        b3Y2SHFORzI2VDgzc2ZJd0dLZEdUK3g3MVFWdUI3TlFDbGNSR3N6YTFSblIzaWs5
        aVNGODRVSmhSaVhxQy9hWVJVY1N5dXRSMnlaMFl0cnRwNEttK1ZIUnF5SUp1SElO
        WFVNY3JuMU85ZTNhMHc3Uytvcm4zL1lPaUtrVVlXeGNJYWpNSFhzaUcwNGdtNndw
        Z0MrT3hJY3kxYnVwc1FGRU95dElEb3crM25KWFNFMS9RSFlud2ovZCt1QWhyTGJM
        Z2JmdnJNZ2puV0hEWG1zRy9NdjdXNE53QWZKc3c1UENxTHVvMXRHUFhSdzFpVzdR
        aTZZRzdTakJqeHFZVTRocU9Hcld2cVRGcTkwUVQ5aTZ5NmVWNmlqTnFKTHozSyth
        blM0Z3JMOGdkQ2N5YmZIRHh4Tyt3V0FIcjNHOGxrUEdNSndlNWw1VS9NdkJJb0tx
        Wjg5VjBsWnZqclI0VFZhL1dRMXpRbWhtRlpLRGlDSnNCcGlnWFlaSXJoRGl0VG9n
        ZE1qRlhtNmhrUU5yR0RaV3Ztb09OZVRaQ0N1dy96SDJTbm44VnFBM3FqV2Z5bm0r
        emcyd3RxUXdQMCtSK2xMV2tURmFkQWJWb3ZSYlRxWkNOWXp5Nk84UVRPZE9NR2F6
        QjlEOSswc0x5bS9kazNPOHEySUJNc2JHaW1nUi9SL1ZhdmFJM25Nanhhb0NaTUN6
        Rkxibk13VWhTLzV2Nzh6dFZXblJLcjU5UVJkS2NZU1RmMXUwWHp2SHp2eXdINUVx
        eGl3amYyWTY0TjV6aEhqazM0Q1FsNEhjSWd4SVJXUVBVSEhLT25zMlJuNXZSektx
        cnFCaXJ4T3N5Mi9FNGlaRC9FMlZTeExBaGtOUWVpdjhPNTFUTnJjVHlSamg4d0dR
        b2RqdThXRWNOUFZBKzc3bE1TQTNycDIwbmZ5c0lqdVhuQjdIRlZNdUxYZktmSGtJ
        YXp5dzNDSlRhK0szSlErdGtoMThQd28wQmtIWXp6NXRjdzhoak1Qd2lYMTRqcjE5
        b3VjMTF5a2VSWk9wRHVJR2QvUFEvUjZEUHptdzF2YmVZOHJZSXRWU2ZvaXZyZzA4
        V0pRMU95NzRzUzRJV3cxSWYzSUtOanIvOUNKbEdIbklnZENGMkJkL2NsZWU0dHZK
        aW96aGowTHY3a3UyZ0EvU2xhRThSYU5zbThqRFNONzNURFRqUkVwNm5mdnFHVm01
        WTNOYjJRZ2hFakxFZ25EUkFoVXQrb01KaUl4TzM4V0lRWHBJU3V3MVBIZllYai9T
        NFJ5VWdEZTc0L2E4SjRTaHZRRTVsZjhhdUJsM3R1L1Rsb0hLd0t1d2d5RHRPNE5E
        Wk05RlR3L3BTZFRTTlNSSDBjVThwTFNUcGRnSlh3eDQvOU5zTERLcGFNY3o5U3pZ
        WFhKbzc0YmxhZEhEWG9zbE9vOEJRbVhOdE1LeTh3Mkd6a2QrcTZPQ3pLbHZQakk4
        TnN4KzJSRUVTak5nV2M2aTBrUUpGTzBmQ093MTc3STZ5MVR0WWFVVmprV2M5K2Zr
        d0t4Wk5uTWJhQmI5QmlDcTlsTm45ZTN5a21HUzNJYlk1SW5pcmlDa2Npeng2MGow
        NlhiS0NTQ1QvOE0yUzE2TDFpbmhWcm8yVklwQ2hLb2ptSURBei9FTzdXSDZKbk83
        MXBvNTdIYXBHOUJyd0s0SkVQK3FEU1VYblZrdStBT29CVitaY1NiSzJubWdKNzJa
        cURWdWM2bU81bkV2VFVSQ3RXZ1QyNFNvUXk3ZU40VXNpT1FWZ0E2Wk9KTVZRZwpU
        VTNDcml2ckFaakNURDYweWZETzdPQTFSbzlybXZYUHh1WnFIMytUWDBRCi0tLSBw
        TkZsUzFQemF5YXJ6OHY1YWdiQUVVdXBibWUveVRsR1RoSUVPckxETVBBCoHJNYeq
        GxK0jorkXznFL5zbjbipK7kPVF7pyzo0o2c2F1s7i88GzfZftihG9ERuVUuxoMww
        +FrRcrGe95hvjgY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq17jrq9vucnth9v4e4gx5zvpsr6szqlcnp9mwt0rmyfyzeww97dyejlxsuvgnu4spgqgzwp9ms0dvrz4gtvc9lw6sxnjywpkq773nptcfqgvccxf6tnfq24eq4prfez8azp7k739mdcdmfx3plew9nl58e8vzwppgegzsmm4y477ycgnqcn2vpknyr3x7zm3eqd6yjrfeygt6582fp4fxpzjp5qdm3g6ncydqpq9g47p77p7cervten3snr0tr2zcptxurpfjgx6p2ux0up8a88qx8m0q6q2yreusmwe862h7rjshm8yyzmse5xsc9ydnkdjt3kz2au3lwqujsz0wy44yvvae99xxtcxejh96vjj5gcej9vwkkzq6k329lexv4qqv9rrz89r5v4qn3vd0sq3c8n8ve84gfdx75rse0xdthm9eafen5wfmc2v8ektj4yz6qlk9dm89q5xzy9vvyscc3vlrmwzfkt09eq9h3npzxr92ths4fn3zct5x9yrv5k87st3s3pqft52qplqtjlzgkpq4pp967mvtxejnnjnsf6y9yqfavh9xqgjehk0pl8sxf8z3pr3kf90esvw6fc9y8j52qnxyrrtfwk8rjj686nfp7matvx7w8cyewnz466wdl2k6l97zpe43s8t0rf32qufadeh96jz427ajnx02xzwaamvsqy65ppwpc639j244kxcpqqej9scfz5k3znxmeprr4rpdnevl6sktult2geu7psahqtpyau0pztpjlvap4zvpxdj0tqa9763pq7c626qcrs69yjyzd48pw670m7fmzh2a3kjger7xuhz6l8se2zqtsxz2e9vlshjjh3n6fz4xzpwqtcrt8f5jnnt8nqk7hj236d7rt5dzxt8sujy025uexsuqtdgfwm8v2j8fh90whg9kxhpswctytua5kete82c90jevuqytaxlqtped4kuu4wzsawnkhw3000xzp9uvtrxwerddlvzknzz3lueydzkzfg8qswae65e8lefj8feywjp9el06r3murqlzd27lm70z289re5zp3ftxsy2fmp0rnvuu2h04qywtgwp0s9w0tqzy8l7jz88mn34qgjglhrpj6tp2l02467twzx3jnt9204pvfwy7rxyucqvajxe5hddf8vlxlfza262fux4ggpfqh59zyjl8jm9vx064nhhcv52d39gtyntg9vsxx0gzamzzruyqf8mhed9l2hgzvgvnmzrjt856phzmuymy9edafdxx27st3ehjncz2u39h3jgars8y98p9pmqjpcajuryc6pgul2qznyxdp79jcnt4cwfzxkuyphc2n5krhd0628lzhs8d2y4et3579sfc65y0kf6u7rve8wf4yswuh74jqrhfue0rgg2qhcpxvt9mexnac0fm8f5w5g4fy92hheyqvens9xpc9t0vz3sqcjamkp2ewtvqg4dhnwxapzv2zvervr8rfzmvzau6r27q8dg6rj74az6grle535tlq0s7xyylxud3xn5znfdxf0ju3jhyxxe7zy9yxdp9zp6v2e26zydsdymk5cgppt0qegkk995l6vjxt9f7t4wrch7vd3ljxu3wkyvppg29zw4ee29fqqwm84p5edjpn4fnqm3fsr5nhnnz6ft29e020chr0v7s64ppeyl36nu63zq8lc0f7ly0jx4495vv49ayqxypmzxadnd66xmxwxs7vwlczdkmtetymgkws09rtzkg903g4qpyn3nr6uk8ch69ksr5kc268e5r3dwnnw9uupgch34n2sn85hc3xt3ggys5x8sqmr3u3gllg0y3yq5fg0pmkrvafr8qfwtdve55gdlaavdqeqq2fq04sznlnpa3xctc7rtj5gc54sugwjn5gzr6jcczu95ynpeefsd0r7ngkq3r7vhupsk7uu57dqv4x2fme
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T20:27:36Z"
  mac: ENC[AES256_GCM,data:Fja8vT7sKl/pOOpcsrbK5FLbO20+77v/LBoEsmGEvUFPQKYIpMQtslSmXeJT0RJ69MKuDIa0G4LrFQpEi9Ux22oTaEPw6Z+1XSRLjXtxRylod9L6IM3lbCMmwqwAHRdhoeSh69VAqiM18dK3P/u8PYJNRdFA4P1PSFlGhwuHONk=,iv:cafRcdnvzRmD3PgCXiyN9PgUw4MAsZK2NC3pQqTN++M=,tag:gQRn9jQ5ebR88dP9ufAkCw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
