apiVersion: v1
kind: Secret
metadata:
  name: sops-age-pq
stringData:
  age.agekey: ENC[AES256_GCM,data:qyYkADsauPO3+gevW2vtguJ1pjzPF8XAwM8+6l1WVgjMy6vrH72/Z15gOcVj6rOZAtoskKIscATBRqk0YI01GobFs185U0kXpyqkNTg=,iv:U0oppeP01RtaWBrUISDJIqgxVu2PhDtDRbIqTjlqGwI=,tag:AUVTAs6/4+xe+Qh0eN3S0g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEZBcnB4RHBs
        cE5meStrS3lOVDBKNTRKaWV0eVNLZW5NUTJxQmJabDRQWmJ0UVN1aGwrRnZVdUpG
        ZVNieE5hVzgwLzM3OFloQk8yRzFleld6Um81WXB3RkRPa3c2SzR2WklZNGMzV3dr
        ZUk1bU1Nd3dIVGdKcE5ScHFWS1FjWG96MENsdFVrMUxYNEQvQ3hHbmNNSXQwUS9I
        cTVoRnNteU83TjFyeUUzVnFSZkNNSHUrRlphaUFBZ2lZWVpNSERheVRpd0lWMVFF
        ME5wbXlXdFBrWGxTYjY3UC9TYnlFT0xKTG9MUmVKdFIwN2hTQUN3YnhJalN3UmtW
        Yjd6YStMTGFGV3B3ZDJrcXhHWkd0TmpUV2RIVVlzTzI0dG1mNFZ0WVZGMjYrWWFy
        LzMwcnlETlM4cTBLY3dEVm53OERqdWRhOHcxalgrcmkxYkZpTGNZekY1Zjc4c2Mw
        YlpsQzFaRE1iV2VINTlFZ1hRcHZXNU5RUEtOTDIycHdFektRa1FiaW9GWVJNYjJ6
        S2ZDVzZsTXRIS01XQ3RrNUUwTmhXMVJsNkM4K1pUYnVEek5lc0lzcmpzOTIzbEUr
        Z1g4Y01xeWJUL05icGhQK0xiQlFWNytqQXFVL21wOVRJWjFkRzNpK3cwdmpQY2Zr
        Yko1WGErMGppMVhxVFpBY0NZTjBzVjU1MWpZV0xZTXkyNXNhSmFKQ3dubno3VlJj
        c0dUYk9Oc0lpdFNEV1k0cVdtU2Q1bHB3MmlDVDZXTzQ1WEFUY29wR2dCQW1tN2lo
        NW14TkpJMkVXdWlydkZGQmtSZzc2YnBLNjJPcDg2VXMvSEQ1Tm1RcTdKMnBmbEw4
        L3dINnNINU5PeTFjT1FMRGU0eGpjbmJLKzJWTDVPMG04SjVjYXRZQXUyVkZQMGdU
        K1ArTXNMeStPbEZ5NE9SVmZoNW1CQTV5SzJ2bTgrVkJCSWF3aU5KNG9ocnZWVHF0
        eTJsRnBrL2VvaFdpZjk1c3lkM1QzWTBZTUhSTU9aKytIU0dYM3FxNW8vTE14Z29v
        MFUwOFFnblU3WDJNSi9QdU9tUlFoNVh6YXZtR2tDMDRvT1huZ0ZrZkFGeEhRS09T
        RG4wOTVxLzJNY0lzdnErZXdNbTRrajIrWDBTS0dTK0V0djdhcnBkeGRMdXZtMm9v
        UmxwM0hYaENpTVoxQWpZYjV5RnM4N2RteXdjOXVuRmkxVEtXRmhVOVAvbkFhWDhu
        bmc4N0swTDlkRVZMc3ppZ21Tc2VnRWtjUHliUVdSeVZUSzRsVitUZUlqVnJHRW1N
        SjJYczZFRDFSbVlWZ3VuUUhHdWdCbDRwQVd3aXB6SkY0RVdrVEVlVTB2L0NsRG9H
        K056WGMxKzN5bmhXY0xrUnBYQWRDMHJ5UEZIYUh4QWF1Rm0rd21VS3ZnTGZ6bExr
        c2Q1RU9xQXFNR1pvSm5ic0ZjdXZ2T3FWNlU5U0IwSGU4MDBXaDJNZzUrc2hLWjhL
        WkNWeXIvbGVvY094MGJUZGpoNHRkZk9EU0didklsU1ZXNUEzLytZWmVGVVFvWU0x
        blcvL252dGFXWUhFczY2M012eHdVN0lLU29GVjNoQUoxSzJwZWN4aGRsVW42RExK
        dEpPM1hjYjZURTc2Ky9Kb0hvTjhEaGZwL1dLdWJ1ck9qdk1wWmJ1ZzZ4elM1OFRt
        UlRwNlE2RlRhQyt2L1JHbFk5MXNub3cyaGZsbVljQnpTRHliTWRRMnRuZWNWR0ZF
        VUZuWmxxK1piU2cxQ3BIbWxZZktvQjhEM0NEUnIzTEhxdGI1dEtKc0VuMDhJVUw2
        VFJOQVNQYVhCck1qVVRYSlBHUHJmck5Vc3VUb1RhWnUyOVRZQ3FKQno2aDRiVUtH
        SjhoN0oycjI1eVQvelA5K2dTVWZwNzhWZEEyRVlwbWt1SUdMd0lMQXg2WUZsSTlB
        TVQ2QmFPUWRLQzB0UFdEWkRiUkR0Z0cwNWg4cTY2WmdmZlUzWlJzQ0F2T0hVdwpK
        VndDWmFqZFUvVjFkQmUvK0R0S01Ib0VGWkI5V0FOTlNUb2VvenY5Z0hBCi0tLSBH
        MDhkQm5VTXBBMTZrbEwrZHdLVnlMMTNTMURQZHdtRXB1T1JsWGIrM0k0CmD6r533
        XMUfoZMybJCvNCd67rma8BH2Gi6R9Cd5GlFqxbuiP8P7HprXI67qIDmBeWNMarhu
        M3aNUKDebu9Cfhw=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1z3jcsx8evc570sfle3awhzqpnwf87dt3rknwq6s9kwwknd2ymct3xajqd0jm2yqely8eqdjnd9r6asv5k405v0hk3zxleenpeyakz6m5nl9ennu4nqerz5duzq6xurtmv0pd5zqz2wd7uy9apaeec8zf8t8mdjs65cvamx9gpae9uz0kf45lez0wwd42d0qnzlskqjsyc2vmptwtx6xj3amxksyjs45grvjmjaqg7j58ed45g9x88hafqmphx30hrwk9alq73eu3gadzjhy4qg4rwf5xwpwvpvkxjqkzyws3kstmwfav7r9rmuenj2xhwfgwkgeyj5ezytyrylv2mdnny7tg27r9sxg6jvctvs9uctv4eg9dyznfnj679zqz52sztpu84raye0p9d9aadr9cj3j2zpkezttdgzgmljc87d58szj65ydpnr4uc8a6s7edj2puy8x8qydyh7yl0ngdjey0z2v736s527sy5mr0ydgag0p5t3dzrajjsl7jrx9lf3t3nwaguysc9568uryf9sjfj4dpcrps2eyhvdj9rj8uc0eqh3fsscc4pkx0jfcc0wm5j72a33ffwr8yxwmqdrgyemfvcy87vl3mw5fmnz520ddp8fzq8pw2k70e8dmqakkwwkyqlcf23cwgxsvlku42n7zhx5ssd0g2zj0mja5e2cgfjdkpmdy8u08prg878y73vzgs52cpw9y8suunhcefcrccldwewwptaw4n6hrqeaqcz848yesmhym2d2nnzkt4sw9tsjd3pz9tq2teqxq37xncqfuetntcfzauevmjftezravjc03vc05d6jtl9l9lpp5cyswnzgqhxh55l9s4q6nyauevfyg8wrwsk5prlsuzkk2s6zzqyduq5z6lghzsjc9nggvw4lsek65ggayzwx4h0whd87vf96qhmltr4hupt35ughrmhpy7f93rqcvn93jy3t087ammgzv58yeq9m8ejxmxggdn2w48fyjjy4wqtsqun5z6wfrd2z2ej89r6ca9tng6nk5qq8295hye7mrqfmjsx6mevh720gcamjseszs7s7uvkw5zs9ngg90tlsev2qm73rtkpmrct825kquwqdp85utcrfaeerc83qe6k34dccn0j9ntqj7tkyyf8xpl5zgymylvn2d6ksprue8eqf845wdvkpfg8m9jgd4ftqqepqr0vtn3j26ntzgn9h382chnw3snkhvn5mz2wgz2nayslsfv0q8m254thzw4yax8l93z6475dv5efpywv9p9zu6273azs84u5qpnxgactdcekvzuengh8xyreqpxwmsmuca25w9e9rque9ytvufg3p4ngkg74zmrssn5ykmzxgfekp6qwglwpztnjpfps4ueykr78g7cx4srk72ansxxu92ev3agk6lczf6leuk0gep63zs2rtl9ja3uwjvs0c2y97qss3yngpl9rph5z6tz8quxdef8v598sqkxccyu5zw5cyj8sw24q92gwxpjqqc5hwmwree040yrsekx9kycyfyhxsu23jyhfj9jy2yvsle4frpqcerupgwfa8rgpuggzdqvzd34xkwajxzheqt9xxlfw7hd82w5kvp7txty7f2nxxmhqsvzvmxxawnc9659wc94zy6u4c0r8fzd7hzw9krfmktcsfxvjdesx3ym6l9us648f2uqcu9jw7xteft7tptglfsmfafqk523gyrxttmhcddsf5mupzs5nvtk0eqf3nfs4slzhay9dzzrcmyzxd0srzcrqew7f3gl5t9ycnc4sh0yj679dpzd846epwmcwy7exynzc0jqveq53udqhj5d0zxvzfepcpxe0ars97krgngssyvkw2hec0vswsj3q20g8xl5syte9ez3cl2sh5uvaw7080s9kj573lyvwcklu8fvtzwhzq2am6ar
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T20:27:36Z"
  mac: ENC[AES256_GCM,data:Fja8vT7sKl/pOOpcsrbK5FLbO20+77v/LBoEsmGEvUFPQKYIpMQtslSmXeJT0RJ69MKuDIa0G4LrFQpEi9Ux22oTaEPw6Z+1XSRLjXtxRylod9L6IM3lbCMmwqwAHRdhoeSh69VAqiM18dK3P/u8PYJNRdFA4P1PSFlGhwuHONk=,iv:cafRcdnvzRmD3PgCXiyN9PgUw4MAsZK2NC3pQqTN++M=,tag:gQRn9jQ5ebR88dP9ufAkCw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
