---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: fluent-bit
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.57.3
    digest: sha256:f3a67c41eed916324c2943c3af0f4f62e001d9635395c3b1a64fd9e6b76c59c6
  url: oci://ghcr.io/fluent/helm-charts/fluent-bit
