# yaml-language-server: $schema=https://schemas.recyclarr.dev/latest/config-schema.json
### Highly recommend using Visual Studio Code with indent-rainbow plugin. VSC will also leverage the above link to enhance pmm yml edits.

###################################################################################################
#                                                                                                 #
#                              Recyclarr Configuration: Sonarr (v4)                               #
#                                    WEB-1080p and WEB-2160p                                      #
#                                                                                                 #
###################################################################################################

# Instance Definition: https://recyclarr.dev/wiki/yaml/config-reference/basic/
sonarr:
  sonarr-prod:
    base_url: http://sonarr.default.svc.cluster.local
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true

    media_management:
      propers_and_repacks: do_not_prefer

    media_naming:
      episodes:
        anime: default
        daily: default
        rename: true
        standard: default
      season: default
      series: plex-imdb

    quality_definition:
      type: series

    quality_profiles:
      - trash_id: 9d142234e45d6143785ac55f5a9e8dc9 # WEB-1080p (Alternative)
        name: WEB-1080p
        reset_unmatched_scores:
          enabled: true
      - trash_id: dfa5eaae7894077ad6449169b6eb03e0 # WEB-2160p (Alternative)
        name: WEB-2160p
        reset_unmatched_scores:
          enabled: true

    custom_formats:
      ###########################################
      #                                         #
      #         WEB-1080p Modifications         #
      #                                         #
      ###########################################

      ## Golden Rule HD (x265 modifications)
      - trash_ids:
        - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
            - name: WEB-1080p
              score: 0

      ## HDR Groups
      - trash_ids:
        - 505d871304820ba7106b693be6fe4a9e # HDR
        - 0c4b99df9206d2cfac3c05ab897dd62a # HDR10+ Boost
        - 7c3a61a9c6cb04f52f1544be6d44a026 # DV Boost
        - 9b27ab6498ec0f31a3353992e19434ca # DV (w/o HDR fallback)
        assign_scores_to:
          - name: WEB-1080p

      ## Audio Formats
      - trash_ids:
        - 0d7824bb924701997f874e7ff7d4844a # TrueHD Atmos
        - 1808e4b9cee74e064dfae3f1db99dbfe # TrueHD
        - 30f70576671ca933adbdcfc736a69718 # PCM
        - 851bd64e04c9374c51102be3dd9ae4cc # FLAC
        - c429417a57ea8c41d57e6990a8b0033f # DTS-HD MA
        - cfa5fbd8f02a86fc55d8d223d06a5e1f # DTS-HD HRA
        - c1a25cd67b5d2e08287c957b1eb903ec # DTS-ES
        - 9d00418ba386a083fbf4d58235fc37ef # DTS X
        - 5964f2a8b3be407d083498e4459d05d0 # DTS
        - 4232a509ce60c4e208d13825b7c06264 # DD+ ATMOS
        - 63487786a8b01b7f20dd2bc90dd4a477 # DD+
        - dbe00161b08a25ac6154c55f95e6318d # DD
        - b6fbafa7942952a13e17e2b1152b539a # ATMOS (undefined)
        - a50b8a0c62274a7c38b09a9619ba9d86 # AAC
        assign_scores_to:
          - name: WEB-1080p

      ###########################################
      #                                         #
      #         WEB-2160p Modifications         #
      #                                         #
      ###########################################

      ## Allow SDR
      - trash_ids:
        - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
        assign_scores_to:
          - name: WEB-2160p
            score: 0

      ## Audio Formats
      - trash_ids:
        - 0d7824bb924701997f874e7ff7d4844a # TrueHD Atmos
        - 1808e4b9cee74e064dfae3f1db99dbfe # TrueHD
        - 30f70576671ca933adbdcfc736a69718 # PCM
        - 851bd64e04c9374c51102be3dd9ae4cc # FLAC
        - c429417a57ea8c41d57e6990a8b0033f # DTS-HD MA
        - cfa5fbd8f02a86fc55d8d223d06a5e1f # DTS-HD HRA
        - c1a25cd67b5d2e08287c957b1eb903ec # DTS-ES
        - 9d00418ba386a083fbf4d58235fc37ef # DTS X
        - 5964f2a8b3be407d083498e4459d05d0 # DTS
        - 4232a509ce60c4e208d13825b7c06264 # DD+ ATMOS
        - 63487786a8b01b7f20dd2bc90dd4a477 # DD+
        - dbe00161b08a25ac6154c55f95e6318d # DD
        - b6fbafa7942952a13e17e2b1152b539a # ATMOS (undefined)
        - a50b8a0c62274a7c38b09a9619ba9d86 # AAC
        assign_scores_to:
          - name: WEB-2160p
