---
# yaml-language-server: $schema=https://kubernetes-schemas-eov.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-gpt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-gpt-secret
    template:
      data:
        OLLAMA_HOST: "{{ .OLLAMA_BASE_URL }}"
        PAPERLESS_API_TOKEN: "{{ .PAPERLESS_GPT_TOKEN }}"
        OPENAI_API_KEY: "{{ .PAPERLESS_GPT_OPENAI_API_KEY }}"
  dataFrom:
    - extract:
        key: ollama
    - extract:
        key: paperless
    - extract:
        key: paperless-gpt
