---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
components:
  - ../../components/alerts
  - ../../components/common
resources:
  - ./graphite-exporter/ks.yaml
  - ./kopia/ks.yaml
  - ./longhorn/ks.yaml
  - ./openebs/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./volsync/ks.yaml
